<? //dsp_kitchen.php 
//Views of kitchen renovation in Turramurra house.
?>
<div class="story">
	<p>The townhouses at 2721 - 2729 Madison St, Denver CO 80205 <a href="http://www.mapquest.com/maps/map.adp?searchtype=address&country=US&addtohistory=&searchtab=home&address=2729+Madison+St&city=Denver&state=CO&zipcode=80205" target="_blank">Map</a>. The #28 bus into town is at the end of the block. See the <a href="http://www.rtd-denver.com/" target="_blank">RTD site</a> for details.</p>
	<p>The inside pictures and floorplan are of 2721 but the others are either identical or a mirror image.</p>
</div>
<div class="photoAlbum">
   <div class="photoBox">	<div class="imgShadow">   <a href="../imageMgt/index.php?fuseAction=showPhotoAndCaption&amp;photoName=lookingNW.jpg" onclick="SweetAndSour.getPhoto('lookingNW.jpg', 'Looking NW from street.'); return false;">      <img src="../madisonSt/images/lookingNW_sm.jpg" width="150" height="113" alt="" />   </a>	</div>  <div class="caption captionThumb">Looking NW from street.	</div></div>
	<div class="photoBox">	<div class="imgShadow">   <a href="../imageMgt/index.php?fuseAction=showPhotoAndCaption&amp;photoName=lookingSW.jpg" onclick="SweetAndSour.getPhoto('lookingSW.jpg', 'Looking SW from street.'); return false;">      <img src="../madisonSt/images/lookingSW_sm.jpg" width="150" height="113" alt="" />   </a>	</div>   <div class="caption captionThumb">Looking SW from street.	</div></div>
	<div class="photoBox">	<div class="imgShadow">   <a href="images/floorplan.pdf">      <img src="../madisonSt/images/floorplan.gif" width="150" height="120" alt="" />   </a>	</div>   <div class="caption captionThumb">Floorplan (PDF - 17kb)	</div></div>
	<div class="photoBox">	<div class="imgShadow">   <a href="../imageMgt/index.php?fuseAction=showPhotoAndCaption&amp;photoName=kitchen1.jpg" onclick="SweetAndSour.getPhoto('kitchen1.jpg', 'Kitchen - dishwasher, sink, refrigerator.'); return false;">      <img src="../madisonSt/images/kitchen1_sm.jpg" width="150" height="113" alt="" />   </a>	</div>   <div class="caption captionThumb">Kitchen - dishwasher, sink, refrigerator.	</div></div>
	<div class="photoBox">	<div class="imgShadow">   <a href="../imageMgt/index.php?fuseAction=showPhotoAndCaption&amp;photoName=kitchen2.jpg" onclick="SweetAndSour.getPhoto('kitchen2.jpg', 'Kitchen - stove.'); return false;">      <img src="../madisonSt/images/kitchen2_sm.jpg" width="113" height="151" alt="" />   </a>	</div>   <div class="caption captionThumb">Kitchen - stove.	</div></div>
	<div class="photoBox">	<div class="imgShadow">   <a href="../imageMgt/index.php?fuseAction=showPhotoAndCaption&amp;photoName=closet1stBed_1.jpg" onclick="SweetAndSour.getPhoto('closet1stBed_1.jpg', 'Smaller closet main bedroom.'); return false;">      <img src="../madisonSt/images/closet1stBed_1_sm.jpg" width="150" height="113" alt="" />   </a>	</div>   <div class="caption captionThumb">Smaller closet main bedroom.<br /> <br /> <br /> <br /> 	</div></div>
	<div class="photoBox">	<div class="imgShadow">   <a href="../imageMgt/index.php?fuseAction=showPhotoAndCaption&amp;photoName=closet1stBed_2.jpg" onclick="SweetAndSour.getPhoto('closet1stBed_2.jpg', 'Larger closet main bedroom.'); return false;">      <img src="../madisonSt/images/closet1stBed_2_sm.jpg" width="150" height="113" alt="" />   </a>	</div>   <div class="caption captionThumb">Larger closet main bedroom.	</div></div>
	<div class="photoBox">	<div class="imgShadow">   <a href="../imageMgt/index.php?fuseAction=showPhotoAndCaption&amp;photoName=closet2ndBed.jpg" onclick="SweetAndSour.getPhoto('closet2ndBed.jpg', 'Closet second bedroom.'); return false;">      <img src="../madisonSt/images/closet2ndBed_sm.jpg" width="150" height="113" alt="" />   </a>	</div>   <div class="caption captionThumb">Closet second bedroom.	</div></div>
	<div class="photoBox">	<div class="imgShadow">   <a href="../imageMgt/index.php?fuseAction=showPhotoAndCaption&amp;photoName=linenCloset.jpg" onclick="SweetAndSour.getPhoto('linenCloset.jpg', 'Linen closet.'); return false;">      <img src="../madisonSt/images/linenCloset_sm.jpg" width="113" height="151" alt="" />   </a>	</div>   <div class="caption captionThumb">Linen closet.	</div></div>
	<div class="photoBox">	<div class="imgShadow">   <a href="../imageMgt/index.php?fuseAction=showPhotoAndCaption&amp;photoName=bathroom1.jpg" onclick="SweetAndSour.getPhoto('bathroom1.jpg', 'Bathroom.'); return false;">      <img src="../madisonSt/images/bathroom1_sm.jpg" width="113" height="151" alt="" />   </a>	</div>   <div class="caption captionThumb">Bathroom.	</div></div>
	<div class="photoBox">	<div class="imgShadow">   <a href="../imageMgt/index.php?fuseAction=showPhotoAndCaption&amp;photoName=bathroom2.jpg" onclick="SweetAndSour.getPhoto('bathroom2.jpg', 'Bathroom.'); return false;">      <img src="../madisonSt/images/bathroom2_sm.jpg" width="113" height="151" alt="" />   </a>	</div>   <div class="caption captionThumb">Bathroom.	</div></div></div>
</div>
