<? //dsp_letter2a.php ?>

<div class="story">
   <p>22nd April 1995</p>
   <p class="endText">Dear...................</p>
</div>

<h2>Move to Denver</h2>
<div class="story">
   <p>Much to our surprise, we are now in <a href="../wherewelive/index.php?fuseAction=denver">Denver</a>, Colorado which is built on the plain at the edge of the Rocky Mountains. It is often called the <i>Mile High City</i> because it is 1 mile (1600m) above sea level. Denver has about 2 million people making it about 1/2 the size of Sydney.</p>
   <p>We spent a total of 3 weeks in Detroit which was frustrating for Lan as there was nothing to do at work except read manuals. There is lots to see though. Probably the highlight was the Henry Ford museum which has a huge collection of cars (not surprisingly) but also glassware, china, domestic appliances (the pump-it-yourself vacuum cleaner has to be seen to believed), farm & factory machinery, aeroplanes, bicycles, electrical generators and steam engines. We also visited a church in a predominantly black area of the town and it was only <i>slightly</i> different from the one in the <i>Blues Brothers</i> movie.</p>
   <p>We had intended to drive to the Niagara Falls and Toronto on our 4th weekend but Lan went to work on that Friday and was told we had to be on  a 5 pm flight to go to Denver. The travel arrangements were very poorly organised-there are plenty of direct flights but we had to go via Chicago and change airlines and the taxi was called late so that by the time we got to the plane (4:58 pm),  they had already closed the door. Fortunately, they let us on and somehow our baggage made it too.</p>
   <p>Lan's employer CBSI, has contracted her to <i>American Management Systems Inc.</i>, which is makes software. Her project is a telephone billing system which is being sold to several countries around the world. Her collegues (and managers) are mainly in their 20s which makes for a casual, low-key office atmosphere but their inexperience has also been a problem. Lan is also working on VAX equipment rather than IBM, and has had to learn how to drive it.</p>
   <p>There is an economic boom in Colorado and the rental market is very tight. We were lucky to find a 2.5 bedroom townhouse which is just  4km from Lan's work. It seems to be a nice area on the western edge of town, we have view looking south and shops are nearby. We also have a garage which I was surprised to find is unusal - surprised because a garage (or at least a car-port) saves digging the car out of the snow and scraping ice off  the windscreen. We are also fortunate because American rental accomodation includes the refrigerator, closets, and in our case the washing machine & clothes drier (no one use clothes lines but we rigged one up in the largely empty basement). Although one of Lan's brothers will be coming to stay with us, we still have plenty of room for visitors, so come on over.</p>
   <p>Incidentally, there are virtually no real estate agents as we know them in Australia. Most rental accomodation is in huge complexes with up to 20 buildings and 300 appartments and is all owned by a single company. There is an on-site office which handles enquiries, maintenance etc.... Most have a permanent ads in one of the <i>Apartments for Rent</i> magazines but that does not mean anything is available. To their credit, they are all quite attractive from the outside. You see none of the block-shape buildings so common in Australia - like our place in Auburn. Brick is quite unusual in any residential building;  virtually everything is built of timber. One curious feature of the most modern apartments is that although they all have closets, most rooms have no light on the ceiling, so you have to provide your own floor stand lamps to reflect off the ceiling. This gives a soft reflected light but it is vey inefficient. Our 300W lamps give as much light as a single 100W globe up high. All rooms are well endowed with power-points. Light switches are upsidedown for us, although I think "up" for "on"  is more logical.  We are in a much smaller complex of about 50 townhouses in 10 buildings and they are generally owner-occupied. I really enjoying not needing to do any house or garden maintenance.</p>
   <p>Winter came late to Denver this year. For the 3 weeks we have been here, daytime temperature have been over 20&deg;C but then we have another snowstorm every 4-5days. We had a minor hailstorm last night but we have been told that every 2 years or so, they get hailstones as big as tennis balls.</p>
   <p>Lan has aunt in Fort Collins, which is 100 km north of Denver. We have visited her (& her husband & 9 year old Micheal) twice and they came down here once. I've done my best to wear out Micheal but he won. My introduction to driving in snow came when we drove directly to Lan's work from Fort Collins early on Monday morning after Denver has received a 15 cm of snow.</p>
   <p>After 2 weeks of searching for a good used car, I bought a 3-door 1991 Hyundai, and a bundle of trouble. The car is OK but the transaction was very messy, and I ended up filing a complaint with the Dealer Board. Actually the car is quite good with only 40,000km on it (though it has been crashed) but it has an annoying seat belt arrangement. The belt across your shoulder is separate from lap belt and is attached to the top rear corner of the door. This has been done because Americans are too lazy /stupid/ignorant to wear seat belts and this gives at least some protection automatically. The lap belt is fastened manually for extra safety. Not wearing seat belts carries only a $10 fine & no points. It is not required at all in the back seat. They prefer to rely instead on dual (pronounced<i>dool</i>) airbags. Very few motorcyclists wear crash helmet and speed limits are not enforced. You have to have a blood alcohol level over 0.1% to make sure your licence revoked.</p>
   <p>Furniture has also been a problem. There are virtually nothing which is simple (& therefore cheap). There is no pine furniture and no equivalent to Ikea/Freedom. For the 1st week our only furniture was an  inflatable mattress but we've since bought a futon sofa/bed, a 2nd-hand coffee table and a small wooden dining set, and a potted palm. We brought cooking gear with us, but we've had to buy a set of plates/bowls/mugs which Lan really likes-made in Italy.</p>
   <p>I also bought a 2nd-hand TV and we can get only 3 channels free to air  (at almosr US$1.00/day we elected not to bother with cable TV). Fortunately, one is the Public Broadscasting Service which is like the ABC but run like 2MBS with public subscriptions and some volunteers. I was enormoustly relieved to find that PBS runs England's ITN (Channel 4) news at 10 pm each night as it  has a far more balanced view of the world. There are other free-to-air stations, notably CBS & ABC but we can't really get them.</p>
   <p>Next: <a class="next" href="index.php?fuseAction=letter2b">First impressions</a></p>
</div>
<div class="photo-gallery">
	<?
	setThumbnail(["DenverLocation.jpg", "StateCapitol1.jpg", "RedRocks1.jpg", "ViewPointNE1.jpg", "ViewPointNW1.jpg", "Hyundai1.jpg", "SeatBelt.jpg"]);
	?>
</div>
