<? //dsp_letter12c.php ?>

<h2>Life in America</h2>
<div class="story">
   <p>The economy continues its dream run with unemployment now down to 4.3%.  Chemical engineers are in really hot demand and average starting salaries for graduates are now US$46,000 (A$73,600 at an exchange rate of 0.625)!  At the other end of the market, McDonalds is now so desperate it is printing a job application form on the bags it puts take-away orders in.</p>
   <p>I read an interesting article questioning the conventional wisdom that a college degree is a guarantee of future economic well-being.  21% of college graduates earn less than the average of those who have only high school education.</p>
   <p>I have been aware that some things are absurdly cheap in America.  Before Thanksgiving in November, the local supermarket had frozen turkeys up to 16 lbs (7.25 kg) for US$4.00 (A$6.40).  If that bird was too small, you could get turkeys up to 25 lbs (11.3 kg) for US$5.00 (A$8.00).  I saw a 19" (48 cm) TV advertised for $149.99 though you had to add local sales tax of 4.0 to 7.5% depending on which store you went to.  I've seen petrol as low as 80.9&#162;/gallon (34A&#162;/litre).  On the other hand, I'm noticing now how expensive a few things are.  Dairy products especially.  Milk at US$1.33 for a quart (946 ml) is almost twice the price of Australia.  The relativities are strange:  3 cartons of milk cost the same as a turkey!</p>
   <p>Lan and I saw <i>Titanic</i> on video with our neighbours.  I've obviously not seen enough violence and suffering on TV to completely desensitize me as I found watching people drown and freeze to death quite disturbing and I had trouble sleeping that night.  Though it was actors in the movie, you know it really did happen.  I've been shocked to hear that various people we know have let children as young as 5 watch it as entertainment.</p>
   <p>I've always thought there are a lot of shops in America.  There are.  Apparently there are 20 sq.ft. of retail space in the US for every person, up from 16 sq.ft. in 1980 compared with 2 sq.ft. in the UK.  Car parks are probably included as they are generally huge here but the difference is still dramatic.</p>
   <p>I prefer American coins as they are smaller/lighter.  The Australian 20&#162; and 50&#162; pieces are way too big.  I do wish the Americans would do as we have done though and force retailers to round off to the nearest 5&#162; so 1&#162; pieces can be eliminated.</p>
   <p>I was listening to JJJ one day and two commentators came on with a sports report.  There was a brief mention of American baseball and that two players were on track to beat the record for the most home runs in a season.  One commentator said to the other <i>"Let me put this question to you: ... Does anyone really care?"</i>  Such is the parochial nature of sport.  Some people obviously do care.  The ball Mark McGwire hit for his 70th home run sold at auction yesterday for US$3 million!  It seems that if you catch a ball it becomes yours and so you keep the proceeds if it is sold.  I don't understand why the baseball league doesn't charge such a person with theft if they refuse to give the ball back.  It seems possession is ten-tenths of the law in this case.</p>
   <p>I heard that the government in the United Arab Emirates was concerned about the spiralling cost of weddings.  There is now a spending limit of US$13,700 and no more than 21 camels can be slaughtered.</p>
   <p>I like American letterboxes which have a flag that comes up when the mail deliverer (ours is female) opens the door to insert the mail.  Neat.  Only Postal Service workers may put things in the letter box so there is little junk mail compared with Sydney since it has to be mailed.  It comes in the weekend newspaper instead.</p>
   <p>Some good news: teen pregnancy fell by 12% from 1991 to 1996, with falls across all ethnic groups.  The drop amongst blacks was 21%.  Partly greater use of contraceptives and partly just-say-no abstinence campaigns.  Still, <i>Newsweek</i> reports <i>"4 out of 10 American teens</i> (I assume girls) <i>&mdash;nearly a million every year&mdash;become pregnant at least once before they turn 20.  Of them, 80% are unmarried."</i></p>
   <p>Sydney recently went to 8 digit phone numbers.  It is now necessary to dial 10 digits in Denver as a second area code has been introduced covering the same area, so you have to dial the 3 digit area code even to call next door.</p>
   <p>More people died on the Oregon trail from accidental gun shot wounds than indian attacks.  The trail took a quarter million settlers across the great plains and the Rockies to Oregon in the 1840s and 1850s before the railway went through.</p>
   <p>I don't think I've ever mentioned that there are sirens around the city which come on to warn of tornadoes or wild storms.  One just went off a few minutes ago though it seems to be perfectly calm outside, so maybe it was just a test.  Tornado season is spring anyway.  I believe they were originally installed in the 50s to warn of imminent nuclear attack.  There was a fascinating documentary on the hydrogen bomb on public TV a few days ago and it mentioned the "duck and cover" campaign intended to minimise casualties and to reduce public fear.  It might have had benefit with the "regular" atomic bomb of the type dropped on Japan but it was soon realised that nothing would save the population of cities if an H-bomb exploded, since it was hundreds of times more powerful.  Simultaneously spectacular and terrifying and a relief that the threat has receded.</p>
   <p>Bumper stickers seen since I got back:</p>
   <ul class="endText">
   	<li><span class="sticker">If you think education is expensive, try ignorance.</span></li>
   	<li><span class="sticker">Have you flogged your crew today?</span> (On the back of a tradesman&rsquo;s vehicle.  Presumably, he is the boss.)</li>
   	<li><span class="sticker">ASK FIRST if the animal wants to be killed</span><br>(Australian readers should note that there is a much more common sticker that says:<br><span class="sticker">ASK FIRST before hunting on private land.</span>)</li>
   	<li><span class="sticker">How&rsquo;s my driving?  Call 1800- EAT-SH**</span><br>(Seen on the back of a pickup truck.  I've added the ** to avoid offending anyone.  Australian readers should note that US phones have letters by the numbers (ABC next to 2, DEF next to 3 etc.) so you can spell dial a number by spelling out words.  Also, many commercial trucks have stickers on the back that say <br><span class="sticker">How&rsquo;s my driving.  Call 1800-4-SAFETY</span><br> or something similar so the drivers know they can be reported for bad driving.)</li>
   	<li><span class="sticker">If you can't change your mind, are you sure you still have one?</span></li>
   	<li><span class="sticker">Give me all your chocolate and no one gets hurt.</span></li>
   </ul>
</div>

<div class="story">
   <p>Go back to:</p>
   <ul class="endText">
   	<li><a href="index.php?fuseAction=letter12a">News</a> (page 1)</li>
   	<li><a href="index.php?fuseAction=letter12b">Adventure to California</a> (page 2)</li>
   </ul>
</div>
