<? //dsp_letter8c.php ?>

<h2>Life in America</h2>
<div class="story">
   <p>The winter just ended was reasonably mild for most of the time.  I continued to take the bus to work and on one day the radio informed me it was -9&deg;F (-22&deg;C).  The bus stop is 12 minutes walk away and by then my hands are frozen.  It is true though that <i>"there is no such thing as bad weather, just inappropriate equipment"</i>!  My hands were cold but with my heavy coat and scarf, the rest of me was warm.</p>
   <p>When it snows during the day, the afternoon traffic is slow and buses can't keep to the normal timetable.  On the way home, my bus stop is right outside my office building and on one such day, a man stood at the bus stop to watch for the approaching bus while his two female colleagues waited inside the building.  When the bus came into view he signalled to them that they should come out and he shouted to them <i>"the bus is about half a block away - it will be here in 40 minutes"</i>! </p>
   <p>We go to the <i>SuperSaver</i> cinema ($1.75) every 2 months or so, to see films about 3-6 months after their main release.  However, we spent $7 each at the regular cinema when the 20th anniversary edition of <i>Star Wars</i> was released as I wasn't sure if it would make it to these downmarket places.  I wanted to see it again and I particularly wanted Lan to see it as she missed out the first time.</p>
   <p>A sure sign that we are becoming acclimatized to America is that we have acquired a taste for country music.  (That&rsquo;s &quot;country <i>and</i> western&quot; music if you saw <i>The Blues Brothers</i>.)  This started by accident when we hired a comedy video but received a dramatized biography of Patsy Cline.  I had never heard of her before but she was a big star in the late 50s/early 60s.  We rushed out and bought a "greatest hits" CD and it has brought a lot of enjoyment.  More recently, Lan saw 20 seconds of LeAnne Rimmes on TV and I heard 20 seconds on the radio and we were impressed.  We were interested to hear that the single Blue was actually written for Patsy Cline but she died in a plane crash before recording it.  When LeAnne won a Grammy for the best new talent, I decided to buy her CD for Lan&rsquo;s birthday. Lan said she had a shiver down her spine after just 10 seconds of <i>Blue</i> which is the first song on the CD.  LeAnne is just 14 (!) though you would never guess by listening to her.  She is now so popular that she has probably already earned more than I will in my whole life. </p>
   <p>Someone I worked with once said, <i>"You know, Australians are the only people in the world who speak without an accent"</i>.  He was right, or at least he was for me at that time; only Australian spoke normally.  To my horror, I now find that Australians do have an accent.  I don't think my speech has changed appreciably, though I will be interested to hear your view when I get a chance to speak to you.</p>
   <p>Unless you live in America, you were probably wondering about the cute little fellow on the outside of the envelope.  He (it?) is the <a href="../imageMgt/index.php?fuseAction=showPhotoAndCaption&photoName=Doughboy2.jpg">Pillsbury Doughboy</a> and appears in TV commercials to advertise the company&rsquo;s baking mix products like chocolate chip cookies.  He is so cute that we both stop everything when he comes on and at the end of every ad., a he gets tickled in the stomach and he lets out a "hoo hoo" laugh.  You can also find him at www.pillsbury.com although the laugh is not as good.</p>
   <p>Although he won the election, there seems to be no end of scandals surrounding the Clinton administration.  Until now, no single scandal has been really damaging, though in total they look bad.  What could be dangerous is allegations of the Chinese government funneling money into the re-election campaign and having a spy near the very top of the government.  A Mr. Huang was given top level security clearance months before he started a government job and held it over a year after he left.  He attended many top secret briefings about policy toward China but he was seen going to the Chinese embassy.  Suspicious to say the least though it has died out of the media recently.  There is probably some truth that the media is biased in favour of the President as I heard somewhere that in the 1992 election, 90% of Washington journalists voted Democrat.</p>
   <p>A few months after losing the Presidential election, Bob Dole was awarded a Congressional Medal of Honor which was presented by Bill Clinton.  After accepting the medal he rose to the podium and said slowly, "I, Robert J. Dole, do solemnly swear ...... Oh, sorry, wrong speech" as if he were being inaugurated as President!</p>
   <p>The right to "free speech" is written into the constitution and many outrageous things are defended in the name of free speech including the right to publish a book which I think was called How to murder someone and get away with it giving helpful tips on the weapons to use and how to avoid leaving evidence.  The City of Denver tried to stop the Denver Post being sold at busy intersections as it was causing traffic congestion but the Post successfully claimed in court that a ban would be a violation of free speech-despite the fact that the newspaper is available at every supermarket and petrol station.  There are apparently 7 exceptions which include shouting "fire" in a crowded theater and saying that you are going to kill the President.</p>
   <p>There was a depressing story on 60 Minutes about a Mexican gang in southern California which is so feared by rival gangs that they pay "taxes" for the right to sell drugs etc. in their own neighborhood.  They reason that all gang members are likely to go to jail one day and since the jails are controlled by the Mexican gang, it is best not to do anything which might offend them or you might get hurt.</p>
   <p>Driver education in Colorado is similar to Australia&rsquo;s in that there is no real system-you get your learner&rsquo;s permit and then you can pay for lessons, or get your friends/family to teach you.  However, I've been told that in most states, students are taught to drive as part of their school education which ensures (a) everyone gets some good training & (b) everyone learns the same things.</p>
   <p>A recent article in USA & World Today argued that highly paid black athletes are providing inappropriate role models for African-American boys.  Unfortunately, black men generally appear in the media in sport (positively), or as criminals (negatively) but not much else and so black kids aspire to be professional sportsmen.  Although only 1 in 10ÿ000 high school athletes will go on to play professional sport, 66% of 13-18 black boys think they can make a living from it.  However, by focusing on sport, there is less enthusiasm for school work, so they are less likely to enter college and then the professional workforce where there are opportunities.</p>
   <p>The attractions of sport are obvious.  The average pay for the 361 players in the National Basketball Association league is $2 million & 80% are black.  Michael Jordon gets paid $12.6 million and received another $40 million in commercial sponsorships.  Sixty seven percent of pro footballers are black but interestingly, only 17% of baseball players.  Professional golf is virtually all-white which is partly because less-affluent minorities can't afford the equipment and course fees.  Tiger Woods sensational entry has brought enormous publicity and brought young black people out to watch.  Although he looks black, he is part CAucasion, part BLack, part american INdian and part ASIAN and I heard he has coined the term CaBlInAsian to describe himself.  His multi-ethnic background reflects the changes in American society generally.</p>
   <p>Interesting things:</p>
   <ul>
   	<li>In a study of people who suffered fractured thigh bones, Americans are 5 times more likely to complain of pain than Vietnamese, despite being given 20 times more pain-killers (adjusted for body weight) - <i>Newsweek</i>
   	<li>It takes 600 gallons (2270 litres) to make the 1/4 pound of beef in a hamburger (mainly to irrigate the crops for grain-fed cows) - <i>Newsweek</i>
   	<li>The world&rsquo;s waters are polluted annually with 540 million gallons of oil i.e. the equivalent of 50 <i>Exxon Valdez</i> accidents every year - <i>National Academy of Sciences</i>
   	<li>The average new house in America is now twice as big as one built in 1950 and yet fewer people will live in it - <i>Denver Post</i>
   	<li>Two-thirds of US cash (dollar bills) is held outside America - <i>PBS</i> (America&rsquo;s public TV network)
   	<li>In 1970, 46% of households were families with children and at least one parent, now it is 25% - can't remember
   	<li>In Denver last year, a totally white dalmatian was spotted - Steve at my office.
   </ul>
   <p>This issue&rsquo;s bumper stickers:</p>
   <ul class="endText">
   	<li><span class="sticker">Wooden shoe rather be Dutch?</span>
   	<li><span class="sticker">Hire a teenager while they still know everything</span>
   	<li><span class="sticker">Lost your cat?  Look under my tires.</span>
   	<li><span class="sticker">A world of wanted children would make a world of difference.</span>
   	<li><span class="sticker">If you want peace, work for justice.</span>
   </ul>
</div>

<h2>...and finally</h2>
<div class="story">
	<p class="endText">We look forward to seeing you at Christmas.  By then we will have been away for 2 years, 9 months i.e. a long time.  There will be a lot of catching up to do and Lan is particularly looking
</div>

<div class="story">
   <p>Previous: <a class="previousPage" href="index.php?fuseAction=letter8b">Trip to southwest corner</a></p>
</div>
