<? //dsp_letter11.php ?>

<div class="story followOn">
	<p>8 November 1998</p>
	<p>Dear everyone,</p>
</div>
<div>
	<div class="story">
	<p>As some of you are aware, there has been a complete change of plans since the beginning of this year.  I am in Sydney but Lan is in Denver and I am leaving next Sunday, November 15 to join her.  In fact I should have gone two weeks ago but I had to delay my departure to get everything done.  I am excited about going back to see Lan (obviously) and our friends there and the city.  Denver (like Sydney) is a great place.</p>
		<p>Lan&rsquo;s company offered to sponsor her through the "green card" process to give her permanent resident status, so we decided she should stay until that went through.  We had started doing the same thing through my employer but that was terminated when I left to come home.  Approval should come by 3rd quarter 1999 and after that we will probably move to England for a few years.  I have a British passport so we wont have the hassle with visas.  Moving there will allow us to be tourists but with new scenery and the job prospects for computer professionals are very good.</p>
		<p>With me here and her there, it has not been an ideal way to run a marriage but daily e-mails and weekly phone calls made it manageable.  Lan came out for 2 weeks in July/August but as Sydney residents know, we had the second wettest winter on record and it rained almost continuously while she was here.  She frequently cried out <i>"miserable weather!"</i> but that didn't make it go away.  We spent a lot of time with her family as she has a brother and sister here, plus there was a sister visiting from the US.  We also slipped in a 2&frac12; day visit to Adelaide to see her family there and that was lots of fun.  We had not seen the children for 7 years so it was great to make friends with them.  I had not been there before and was amazed to discover that Adelaide real estate costs only half that in Sydney.   It is a lovely city and I'm tempted to move there one day.</p>
		<p>I spent the last 7 months fixing up our house so we can rent it out again.  We have a <a href="<?= $rootRelativeUrl ?>wherewelive/kitchen">new kitchen</a> but someone else installed the cabinets and bench tops.  I look back and wonder where all the time (and money) has gone but I know I almost never stopped working.  I had paid work for 6 months with TNA, a company that makes packaging machinery* but I've been working on the house full time for the last 2 months.  Much of the house is repainted, the bathroom has had a facelift and the garden is now almost under control.   Partly because Lan was not here, I spent much more time than expected choosing kitchen appliances and floor tiles.  Actually doing the work was easier without Lan here as much of it was done late at nightthough never past 3.30 am.</p>
		<p>I expected to spend perhaps 3 months renovating and the rest of my time seeing people and having fun.  Sadly, that didn't happen.  I generally accepted invitations but with two exceptions, didn't invite anyone over here thinking I should get the work done first and then I could relax.  Those two occasions coincided with the number of times I cooked a proper dinner!  By this I mean cooking a meat dish and some vegetables and providing (buying) something for dessert.   The rest of the time I managed quite happily on take-aways, frozen pizzas and lasagne, dinner with my mother about once a week and the Ryde TAFE where they teach student chefs how to cook.  At the TAFE you can get meat (choice of four) and vegetables for $4 (US$2.50).  Bargain! There were also a few occasions when someone came over but we went out to eat.</p>
		<p>Thank you to all of you who had me over to your place; I am sorry I was unable to reciprocate.  I thought by now it would have been possible but I was wrong.  My slow progress has been depressing and my self-confidence at being a handyman has suffered.</p>
		<p>I've been reflecting on my wasted youth and my career progress, or lack thereof.  I say my youth was wasted as I spent too much time studying and trying to be grown up when I should have been out having fun and chasing girls, had I had the self-confidence.  I've concluded that there are very few really interesting engineering jobs like designing wind turbines or hybrid cars and I am not suitably experienced for them anyway.  I was pretty disgusted by/jealous of the son of my neighbour who dropped out of an Arts degree to work for Optus in Customer Service answering the phone but he moved in the company after 6 months to a position building internet sites and paying $40,000.  I had to do a 4 year degree then work 8 years to get that much so it seems my study was a poor return on the effort invested.  If most jobs are made interesting only by the people you work with, school careers advisers might be better just directing people to where the money is.  I've also been wondering why we wasted time at school learning calculus and Shakespeare, but I digress ...</p>
		<p>I had a laser eye operation that was supposed to improve the vision in the eye which had a cornea transplant 5 years ago.  It is a little better at distance but worse at reading distance and I had several days where I could hardly see at all.  It may still improve over the next few months.  The other eye is near-useless without a contact lens but that hurts after a few hours.</p>
		<p>I surprised myself by becoming engrossed by the <i>World Cup</i>, spending an hour a day watching the highlights.  I was depressed when England lost to Argentina in the penalty shoot-out; I was impressed by Chilevert, the goal keeper and captain for Paraguay.  Before the match with France, he was asked about the pressure he felt.  He replied: any pressure on him was nothing compared with the pressure faced by the people of his country, who often didn't know where the next meal was coming from.  It puts in perspective.  In the end Nike (Brazil) lost to Adidas (France), so that was good.</p>
		<p>My mother is coming over to visit us at Christmas for two weeks and we'll do a bit of touring.  My sister Lucinda will be going to Britain in January to join her husband who is setting up his company in Europe.  He&rsquo;s doing very well..</p>
		<p>I have commented before on how many good bumper stickers there are in America.  The flip side of this is that there are very few in Australia.  All I can include in this issue are:</p>
		<ul>
		<li>McDonalds' logo with the words: <span class="sticker">Would you like lies with that?</span> Obviously they don't like the company but it would be nice to know which aspect.
		<li>Not a bumper sticker but it should be: <span class="sticker">My goal is to live forever.  So far I'm on schedule.</span>
		</ul>
		<p>I can add a worrying story though:  I met someone who had visited America and they gave an Australian calendar as a gift.  The lady receiving it said "This calendar won't work here".  She knew that Australia is a day ahead (for the purpose of calling someone) but had not realised that (for instance) Christmas falls on December 25 no matter where you are!</p>
		<p>That&rsquo;s all for now.  I'm sorry I didn't get to see more of you while I was in Sydney (and that there are no photos in this issue).  Please keep in touch.</p>
		<p class="endText">Peter V</p>
	</div>
	<div class="photo-gallery">
		<?
		setThumbnail("FriendsAtTNA1.jpg");
		setThumbnail("ChilavertInAction1.jpg");
		setThumbnail("ChilavertUpClose1.jpg");
		?>
	</div>
</div>

<div class="story">
	<p class="endText">* My friend Ken at TNA taught me a wonderful workplace saying: <i>"It&rsquo;s a good thing they pay usI wouldn't come otherwise"</i>(!).  Not completely true as there was a bit of fun and interest too.</p>
</div>