<? //dsp_letter12a.php ?>

<div class="story">
   <p>12 January 1999
   <p>Dear everyone,
   <p class="endText">A great deal has happened in the last year and I apologise that I ran out of time before I came back to America so that my last letter (8 Nov 98) was sent to only a few of you.  I've included it for those of you who missed out the first time.
</div>

<h3>News</h3>
<div class="story">
   <p>Lan is still working at US West Dex, the division of the local phone company that produces the phone directories, both in paper and on the net.  Her application for a "green card" or permanent resident status is progressing through the system slowly.  Labor certification, which demonstrates that there is no one in the US willing and able to do her job, has been successfully completed and the whole thing should be over by about September this year.  This will allow both of us to work for just about anyone without needing a new visa and we can come and go from the US more or less as we please, so long as she comes back to the US once a year.</p>
   <p>My current visa does not allow me to work, so there were three possibilities: (a) try and find an employer who is willing to apply for a working visa on my behalf, (b) go to the UK and find a job but fly to Denver for a week every 3 months to visit Lan, or (c) study.  Lan wants to work in the UK after her green card is approved, so option (b) seemed the most likely, especially as British Airways now fly direct.  However, having been separated by the Pacific Ocean for most of 1998, neither of us thought being on opposite sides of the Atlantic for most of 1999 would be such a great idea.  I don't want to go to job interviews in Denver knowing I will probably be here less than a year so that ruled out option (a).  That left option (c).</p>
   <p>I've adopted the saying "if you can't beat them, join them" - I'm moving into the computer industry.  I've been disappointed that my engineering career has not progressed as I expected, though in retrospect, it was my fault for not making better choices over the years; my résumé is long but it is unfocused and doesn't add up to much.  I'm taking a computer course heavy on internet development and I hope to finish by the end of August.  It seems that even with minimum training, there are endless, well-paid job opportunities, and unlike Lan, I am interested in computers - I can happily spend/waste almost every evening poking around on the internet or doing something on the computer.  It amazes me how much the computer world has changed since I studied engineering; in my final year at university (1985) there was only one person in our class of 35 who had a computer and of course, the internet did not exist for public use.</p>
   <p>Lan and I enjoyed reading Bill Bryson&rsquo;s <i>The Lost Continent; Travels through small town America</i>.  Bill takes a long trip around the US mainly avoiding the big cities and he writes of his experiences.  I laughed out loud often.  What makes it particularly interesting is that he spent 10 years in England before taking the trip and so he writes almost from the perspective of a foreigner.  I've been told it is sort of like my letters, only longer and more interesting.  Incidentally, this is the first book I have read cover-to-cover in almost 4 years and that alone makes it worth mentioning.</p>
   <p>Our American readers will be familiar with the TV commercial featuring country music star Alan Jackson singing <i>"If I had money, I tell you what I'd do, I'd go downtown and buy a Ford truck or two..."</i>.  It&rsquo;s really very catchy and it&rsquo;s hard not to find yourself singing it yourself from time to time.  Without realizing it, Lan changed the words in a way that reflects her personality: <i>"If I had money, I tell you what to do ..."</i>.  Note that she is now issuing commands instead of describing her actions!</p>
   <p>I've commented in previous letters on how Americans have mangled my name, especially when I give it over the phone.  I had a new variation recently: Pager.  Very amusing.  Ha, ha.</p>
   <p>We have had a very mild winter which has been a relief to me since I'm having my third winter in a row.  There was one really cold tch but I was out of town for most of it.  There hasn't been much snow this season and the ski resorts haven't done so well.</p>
   <p>I'm still recovering from the frustration of the nine months I spent in Sydney attempting to fix our house and resurrect the garden.   It seemed the task kept on expanding, yet there were endless delays and battles with tradesmen to do as they promised.  I never did get to see many of you who I would have enjoyed seeing.  Sorry.  I did listen to the radio a lot while I was working and there was a song called <i>Flagpole Sitta</i> which seemed to express my anger and sense of defeat I felt at the time, even though I heard the guy who wrote it say it was mainly nonsense.  It&rsquo;s best played LOUD.</p>
   <p class="endText">Our e-mail address through Juno.com is free and doesn't require an internet connection, just a computer and a modem.  There is now something similar in Australia through Telstra called Easymail.  You only pay the cost of a local call so now you have no excuse not to write to us!  You can see www.easymail.telstra.com or call 1800 429 4444 for information and they'll send you the software.</p>
</div>
  
<div class="story">
   <p>Continue to <a href="index.php?fuseAction=letter12b">Adventure to California</a> (page 2) <a href="index.php?fuseAction=letter12b"><img src="<?= $continueIconSrc ?>" height="13" border="0" style="vertical-align:bottom"></a></p>
   <p class="endText">Jump to <a href="index.php?fuseAction=letter12c">Life in America</a> (page 3)</p>
</div>
