<? //dsp_letter14b.php ?>

<h2>Out and about</h2>
<div class="story">
	<p>We only did two short trips together last year though both were fascinating.</p>

	<p>THE WINDY CITY*</p>
	<p>The first was to Chicago in early May.  Lan has a cousin living there who she had not seen since 1968 so they had quite a bit of catching up to do.  Xuan puts people to sleep at the hospital and wakes them up later.  She is forced to work odd hours since patients fail to set appointments before contracting diseases, getting into car crashes, falling down stairs and so on.  Very inconsiderate.  She did however have time to take us to the Botanical Gardens and even as a non-garden person, I have to say it was most impressive.</p>
	<p>We also did a walking tour of modern skyscrapers (we were too late for the early skyscraper tour which probably would have been even more interesting), and then went up the top of the <a href="http://www.sears-tower.com/" target="_blank">Sears Tower</a>  which was the world&rsquo;s tallest building for over 20 years.   My favorite building though was the <a href="http://www.galinsky.com/buildings/inlandsteel/index.htm" target="_blank">Inland Steel Building</a>.  The external metalwork is stainless steel that looks like it was installed yesterday but it actually dates from 1958.</p>
	<p>On our last day in the city, we visited an atom-smashing center (the <a href="http://www.fnal.gov/" target="_blank">Fermi National Accelerator Laboratory</a>) and <a href="http://architecture.about.com/arts/" target="_blank">Robie House</a> designed by Frank Lloyd-Wright.  The last was disappointing because the guide was a motor-mouth and wasted so much time outside, that at the time the tour was supposed to finish, the group had just entered the house but we had to leave to catch the plane home.</p>

	<p>DINASOUR NATIONAL MONUMENT</p>
	<p>Memorial Day is the equivalent of Australia&rsquo;s Anzac Day commemorating the sacrifices of servicemen and women.  Taking advantage of the long weekend, we decided to visit some friends in Grand Junction, a town on the western edge of Colorado and used that as a staging point to see Dinosaur National Monument. National Monuments are effectively National Parks but not quite so famous.  Actually, it is two parks in one.  Some of the best and biggest dinosaur skeletons anywhere have been dug up in the section of the park that is over the state border in Utah.  Since we had limited time and most of the dinosaurs are now in places like Pittsburgh, we visited the magnificent gorges carved by the Green and Yampa rivers.</p>
	<p>Amazingly, a group of Spaniards came through here in 1776 from Santa Fe, New Mexico, hoping to find a way through to California.  A long walk.</p>
	<p>Incidentally, it seems non-American exploration is quite under-appreciated.  I think every American can proudly tell you of</p>
	<p><a href="http://www.pbs.org/lewisandclark/" target="_blank">Lewis and Clark&rsquo;s expedition</a> across America reaching the Pacific in 1805.  It truly was a remarkable achievement but they were <i>not</i> the first.  <a href="http://www.nlc-bnc.ca/2/24/h24-1630-e.html" target="_blank">Alexander Mackenzie</a> and a group of Canadians beat them by 12 years, arriving a little way north of what is now Vancouver (see <a href="http://www.johnamatt.com/amrmap.htm" target="_blank">map</a>) in 1793 but they have been largely forgotten.</p>

	<p>OUR NEXT TRIP ... HOME!</p>
	<p>We have booked a trip to Sydney and Adelaide.  I'll be in Australia April 15 to 29th but since Lan hasn't had time to accumulate much holiday time (and American&rsquo;s get only 2 weeks each year), she won't arrive until April 21st.  We intend to see as many people as possible during that time, especially the few hundred that make up Lan&rsquo;s immediate family.</p>

	<p>IN MEMORY</p>
	<p class="endText">In our letter last year, I commented on the wonderful time we had with Lan&rsquo;s <a href="http://users.kua.net/~jmiller/" target="_blank">aunt Tuyet</a> in Orlando, Florida.  We suffered a great loss this year when she died unexpectedly of luekemia.  She went to the doctor thinking she had the flu and died a few weeks later.  She was only 47.</p>
</div>
<div class="photo-gallery">
	<?
	setThumbnail(["LanAndXuan1.jpg", "SearsTower1.jpg", "Dino_NM_Us1.jpg", "Dino_NM1.jpg"]);
	?>
</div>

<div class="story">
	<p class="endText">*<i>Contrary to popular belief, the name comes not from the weather but from the amount of "hot air" generated by early Chicago politicians claiming their city to be better than New York.</i></p>
</div>

<div class="story">
	<p>Next: <a class="next" href="<?= $rootRelativeUrl ?>letters/letter14c">Bumper stickers</a><br>
	Previous: <a class="previousPage" href="<?= $rootRelativeUrl ?>letters/letter14a">2&frac12; years for this!?</a></p>
</div>

