<? //dsp_letter10a.php ?>

<div class="story">
   <p>19 March 1998*</p>
   <p class="endText">Dear ...............,</p>
</div>

<h3>Home again</h3>
<div class="story">
   <p>I'm back!  Yes, it is true that in the last letter I said we just bought a unit and that I expected we would get permanent resident status before we come home, hopefully by the end of this year.</p>
   <p>Unfortunately, everything has changed.  As many of you know, my father had been very sick with cancer in his oesophagus for which he had an operation last year but then it spread to his stomach.  He had chemotherapy on the day before Christmas but the cancer failed to respond and he finally died at home yesterday, 18th March.  Although this news may come as a shock to you, it is something of a relief for us as have expected it for a long time.  My mother and my sister Lucinda were with him when he died and I was on my way home from work.  From Christmas until about 10 days ago (Sunday the 8th), he spent almost all day in bed with perhaps 2 or 3 waking hours which was down to 1 hour towards the end but he was still able to talk and eat in very small quantities.  Occasionally he would come out and watch TV or just look at the view. After that his conditioned worsened and he was unable to talk or swallow and so he was on much greater drug doses to sedate him and kill the pain.  The palliative-care doctor (and us) thought he would die last Friday (the 13th) when he would stop breathing for 30 seconds at a time and his extremities went cold but by Sunday, his breathing improved and he warmed up.  From then until Monday night of this week, one of us was at his bedside 24 hours a day but we became exhausted and we had to arrange for a nurse to stay the night so we could sleep.  The doctor and all the nurses were really wonderful in trying to make dad as comfortable as possible.  Lucinda and her husband Michael moved in 8 days before he died and Michael even stayed at home Wed-Fri last week which was an enormous help to mum and Lucinda (I started a new job that Monday about which I'll add more later).  It will probably be over by the time you read this but the funeral will be held 1.30pm Mon 23rd March at St. Giles Greenwich and dad&rsquo;s body will be cremated.  Being ever-practical, he asked that if anyone was thinking of sending flowers, he would rather the money be donated to the Salvation Army.</p>
   <p>I've always believed in doctor-assisted suicide but having seen dad die over a period of 21/2 months, my views are now unshakeable.  Dad was ready to go long before he actually did and it was sad to see him suffer so much.  Lucinda pointed out that you would not be allowed to prolong the life of a horse or dog in the same condition and someone at work went further and said that you would be obligated to put the animal out its misery but our laws treat humans quite differently.</p>
   <p>I resigned from my job in Denver and I came home on 5th Feb.  I've been staying at my parents' house temporarily partly because we still have tenants in our house but also to help look after dad.  I'll be back at Turramurra from April 1 or soon after.  The phone number here in Greenwich is ###-####.</p>
   <p>I also came home for a week by myself on a surprise visit over New Year when it became clear that something was wrong.  Just a few people knew I was coming, <i>not</i> including my parents, so my mother was amazed when I appeared at the door! </p>
   <p>Lan came to Sydney for a two week visit which included a week in Adelaide to see her family.  She flew back to Denver on March 4th.  We had thought of having a picnic so she could see everyone but she just ran out of time.  Our apologies to the vast majority of you that Lan didn't get to see.  The plan at the moment is that Lan will come back in June which allows her to stay in her new job a bit longer and allows me to move back into our house and rebuild the kitchen.  She is learning new, marketable skills at work and so is reluctant to leave after so little time there.  E-mail is a wonderful thing as we can be contact daily and phone calls are now relatively cheap2 so we'll speak weekly.  Still, it&rsquo;s not the same as being there.  We think we will sell the unit we just bought in Denver.  I will probably go over for a week in June or July to sign all the paperwork and help pack/sell everything we have.</p>
   <p>I bought a used car (a 1984 <a href="../imageMgt/index.php?fuseAction=showPhotoAndCaption&photoName=NissanPulsar2.jpg">Nissan Pulsar</a>) but I made the great mistake of going to view the car at night.  After 3 weeks of looking, I was getting desperate and this one was almost perfect inside, had no rust, blew no smoke in the exhaust and came with 51 weeks of registration.  Unfortunately, I didn't spot the poor-quality smash repairs to the rear of the car which are obvious in daylight, so I paid far too much for it.  It has other problems too which I think (hope) are fixable but I have not had time to look.  Apart from that, I really like the car-really.</p>
   <p>I started working two weeks ago at TNA Australia.  They make the machines that package foods like potato chips, nuts and confectionery at rates up to 125 bags per minute or more than 2 per second.  The owner of the business holds a world-wide patent on his technology and the company has doubled sales in both the last 2 years and exports 95% of what it sells.  The office and prototype assembly area is in Chester Hill, just a few kilometers from where we used to live in Auburn but the main factory is in Melbourne.</p>
   <p class="endText">I'm not sure how long we will stay in Australia but it probably be less than 3 years.  Lan was disappointed by what she saw in Tuesday&rsquo;s Australian which carries most of the computer jobs.  It seems there are many, many more opportunities for her sort of skills in either the US or the UK.  The UK may be more practical as I have a British passport as well as Australian, so we wont have the hassle with visas we had in the US and therefore have to work at salaries below market rates.  It could be our next adventure.</p>
</div>
<div class="photo-gallery">
	<?
	setThumbnail(["Dad1.jpg", "FriendsAtIsoTech1.jpg"]);
	?>
</div>

<div class="story">
	<p class="endText">*<i>I had hoped to get this out a month ago but the lack of a printer, Lan&rsquo;s visit and rapidly changing events slowed things down.</i></p>
</div>

<div class="story">
   <p>Continue to <a href="index.php?fuseAction=letter10b">Australia</a> (page 2) <a href="index.php?fuseAction=letter10b"><img src="<?= $continueIconSrc ?>" height="13" border="0" style="vertical-align:bottom"></a></p>
   <p class="endText">Jump to <a href="index.php?fuseAction=letter10c">America</a> (page 3)</p>
</div>
