<? //dsp_letter5d.php ?>

<h3>Life in America as we see it</h3>
<div class="story">
   <p>Christmas is taken seriously by many home-owners and businesses in Denver.  Lots of houses have lights all over them, plastic snowmen on the lawns and Santa with reindeer on the roof.  In some streets there seems to be a competition for the most decorated house.  Tacky perhaps but quite pretty when it is done well.  It would not work in Australia since our Christmas is in the summer and it gets dark too late.</p>
   <p>I used to think that Valentine&rsquo;s Day was just for lovers to express their affection for each other.  Apparently I was wrong.  You can get Valentine&rsquo;s Day cards for children, grandparents, nieces ... you name it and there is a card for them.</p>
   <p>American supermarkets are virtually self-contained shopping centres.  Our Safeway is about 3 or 4 times the size of the Franklins near us at Turramurra and it has everything.  There are no butcher or green grocer shops because they are in the supermarket.  As is the fish shop.  The in-store bakery makes great French loaves and baguettes.  There is also an in-store pharmacy which has meant that the drug stores have had to diversify to stay in business so that they look a lot like supermarkets.  Adjacent to the pharmacy is do-it-yourself blood pressure measuring equipment.  You can hire videos ($1 for most) although the selection is limited so there are still separate video stores. (The one near us is expensive at $3 but I don't know if this is normal.)   Some supermarkets even have a conplete bank inside them and it is a good place to have an ATM as there are always people around making it very safe).  If you have young kids , perhaps the biggest attraction is the horse/aeroplane/car rides which rock back and forth for just 1¢!  Given the affluence of this area, we have been surprised by how often we see people taking items from the shelves and consuming them while in the supermarket.</p>
   <p>One of the few things our supermarket does not sell is guns and ammo.  That&rsquo;s OK as there is a gun shop in the same building.  Killing animals for fun (also known as "hunting") appears to be a really big sport in Colorado though it seems to me that it would be more sporting if the animals could shoot at the hunters.  Someone at work had a magazine on their desk called <i>Hunting Dog</i> (shoot something and then have the dog get it) and there have been TV ads for gun shows (<i>"Hey sportsmen ..."</i>).  I've read that 95% of hunters are men.</p>
   <p>This reminds me that I've heard that men <i>hunt</i> while women <i>shop</i>.  It&rsquo;s true in our family.  If I need something, I go out and don't look at anything else until the desired item has been obtained.  If I'm looking for jeans, I don't want to get distracted by bedding, or shoes, or wrapping paper, no matter how cheap they are.  On the other hand, Lan wouldn't need to go looking for jeans because she probably bought some the day she went shopping for kitchenware.</p>
   <p>Americans take lots of pills.  Before I came to America, I didn't even know what "heartburn" was.  It may just be the demographics of the audience but in each half-hour news broadcast I would expect to see 2 or 3 ads for heartburn/acid indigestion pills plus ads for a plethora of nutrient supplements (e.g. <i>"Sustacal - it may not add years to your life but it might just add life to your years"</i>), at least one for headache tablets and possibly one for anti-diarrhoea tablets and/or laxatives.  There was a 60 Minutes report that there are 2 million children on a drug called Ritalin which is supposed to help hyperactive kids but one person on the show thought that 5 or perhaps 10% of those actually needed it.  The others just needed parents who disciplined them and provided good role models.</p>
   <p>I don't normally even look at the sports section in Sunday&rsquo;s newspaper but one thing did catch my eye which gave an insight into the American media.  I saw the word "Australian" in a headline about the Australian Open Tennis Championship.  A young Greek- Australian with a name like Philipopolopolis had surprised veryone by beating Peter Sampras who I think is American and No 1 or 2 in the world.  Incredibly, the photo was not of unknown Aussie who won but the well-known American who lost!</p>
   <p class="endText">I've been impressed by school buses (apparently called <i>cheese buses</i> by the kids because of their color) and that when they stop to pick up children, cars on both sides of the road must stop.  Pedestrian crossings near a school normally have a person with a stop/go sign and yellow lights flash to warn drivers that the speed limit is reduced to 20 mph (32 km/h).  I think school buses were introduced across America (in the 1960s?) to transport children to schools outside their area so that schools would became racially integrated.  However, since schools are run by local government and "busing" is within the county, white folks moved out of areas where there was a large black population.  Partly as a result, many inner cities across America are largely black and the schools are too.</p>
</div>
<?
setThumbnail("ChristmasLights1.jpg");
?>

<div class="story">
   <p>Go back to:</p>
   <ul>
   	<li><a href="index.php?fuseAction=letter5a">News</a> (page 1)</li>
   	<li><a href="index.php?fuseAction=letter5b">More news</a> (page 2)</li>
   	<li><a href="index.php?fuseAction=letter5c">Trip to California</a> (page 3)</li>
   </ul>
   <p class="endText">Continue to <a href="index.php?fuseAction=letter5e">Interesting things</a> (page 5) <a href="index.php?fuseAction=letter5e"><img src="<?= $continueIconSrc ?>" height="13" border="0" style="vertical-align:bottom"></a></p>
</div>
