<? //dsp_letter5b.php ?>

<h2>More news</h2>
<div class="story">
   <p>I'm still having difficulty making myself understood.  I introduced myself to someone at work a few weeks ago and they thought my name was <i>Pleaser</i>!  How could they hear an <b>L</b> and mistake my <b>T</b> for an <b>S</b>?  It is beyond me.  Someone at the supermarket asked me where in England I came from.  When I said Australia, he commented that Australian and English accents were very similar.  I pretended to be amused.  My office is becoming a Shrine to Australia.  I have a big map of Australia on the wall, pictures of the Opera House, a koala and Sydney Harbour, a postcard of a kangaroo riding a surfboard (I do!) and another postcard which has the outline of Australia overlaid on a map of America (they are about the same size which comes as a surprise to most Americans).</p>
   <p>I get paid weekly by check which is a real nuisance.  You may remember when ATMs were introduced in Australia, the Commonwealth Bank forced customers to write their account number and the amounts on deposit envelopes.  It didn't last long because so many people complained and the other banks' machines printed it for you.  Not so our bank and I assume the other banks too.  To make a deposit I have to bring the account number and a pen with me and give them my address and phone numbers, the check numbers and amounts.</p>
   <p>I'm also angry with our bank because they would not give us a Visa debit card (one where charges come directly from your account and you are severely penalised if you spend more than your savings).  They agreed that we had a healthy income and plenty of money in our accounts but we had no credit file and that was the end of it.  American babies must be born complete with credit files otherwise they could never get a credit card when they become adults.  I intend to close our accounts.</p>
   <p>Incidentally, the standard work day for office workers is 8am to 5pm with an hour for lunch (40hrs).  I get 8 public holidays each year but Lan&rsquo;s company is generous as it grants Columbus Day, or on alternate years, Martin Luther King Day and Presidents' Day.</p>
   <p>On President&rsquo;s Day, Lan dropped me at work and I caught the bus home.  Unfortunately, it is a half-hour walk for me to get to the bus stop when I can drive all the way home in 15-20 minutes.  The bus was great as it was clean and modern with a clear spot for wheelchair users though I'm not sure how they could get on.  The bus even had seatbelts which seemed rather pointless as buses are bigger than just about everything else on the road and no-one was wearing them.  In peak hours, fares for all routes are just $1 and off-peak fares are 50&#162;. For senior citizens, the ride only 15&#162;.  At that rate, why not make it free?</p>
   <p>Denver has strange weather.  I had expected it to be really cold all winter but there have been times when it has been really warm and even some cold days come with strong sunshine that makes them quite bearable.  We had three weeks during February when the daily maximum temperatures was 15&deg; to 20&deg;C.  This was compensation for days at the other extreme:  on Feb 2, the maximum temperature was 0&deg;F (-18&deg;C) and the overnight low was -16&deg;F (-26&deg;C).  It was worse further north and east and at least I had the luxury of driving to work and living in heated buildings.  Still, it made me wonder how the native Americans and early settlers survived.  The gold miners must have had a hard winter as the easy gold was in the icy mountains streams.  It is beyond my imagination how miserable it must have been for the German army in WW2 and Napoleon&rsquo;s army before them when they were caught unprepared in a Russian winter.  I was also reminded of <i>Ivan Denisivich</i>, a book I had to read at school about a prisoner in one of the Soviet gulags.</p>
   <p>Over the last few months we have had about a dozen people from Lan&rsquo;s office over to dinner, or been out with them.  The only social thing that we've done with anyone connected with my work has been to have dinner with the lady at the employment agent who originally hired me. lly then, we are still friendless.  I have received a few items of junk mail offering to help me make new friends and long-term relationships but on their reply cards, there has been no box to tick if you are already married.  What a shame.</p>
   <p>We have seen about 6 movies since November after we discovered that there are two cinemas that show films after they have been withdrawn from the main cinemas but before they come out on video.  Tickets are just $1.50!  My favourite was <i>It takes two</i>.  Did you see it?  It was cute.  We saw <i>Babe</i> which apparently is Australian.  While on the subject of Australian movies, we hired <i>Priscilla! Queen of the desert</i>.  We both found it highly amusing but also thought-provoking and even sad.  An American movie show on TV mentioned it and told everyone to get it on video as they felt it was brilliant.  I don't think it was much of a hit in the US outside the gay community.</p>
   <p class="endText">While at Lan&rsquo;s aunt&rsquo;s house, we watched <i>Soul Man</i> which I saw years ago with St Giles Fellowship and I wanted Lan to see.  A young white man makes himself eligible for a college scholarship by making himself a Negro.  It is also full of laughs (does anyone remember the basketball scene?) but it probes the deeper issue of race and gives a small insight into how white stereotypes affect the world that black people live in.</p>
</div>

<div class="story">
   <p>Next: <a class="next" href="<?= $rootRelativeUrl ?>letters/letter5c">Trip to California</a><br>
Previous: <a class="previousPage" href="<?= $rootRelativeUrl ?>letters/letter5a">News</a></p>
</div>
