<? //dsp_letter16b.php ?>

<h2>I love New York</h2>
<div class="clearfix">
	<div class="story followOn">
		<p>Lan tuned into a fund-raising auction for one of our local public TV stations and picked up a 3-night/4-day package to go to New York, a place we have wanted to visit for a long time and particularly since the terror attacks.</p>
		<p>Real estate prices and by extension, hotel prices, are unbelievable!  The business-class hotel that came with the package would have cost US$269 per night if we were to pay for it ourselves. Fortunately we didn't and the flights were not fixed so we were able to extend it to a week by arranging our own hotel for 3 nights. We booked a "budget" hotel for "just" $129 per night but Lan thought it too smelly and I found it too noisy so we stayed the last two nights in a hotel that was $139 per night but with various taxes it came to $158 per night! Quite surprising really as New York real estate used to be a bargain-in 1625, the Dutch bought the whole Manhattan Island from the local native Americans for goods worth 60 guilders, or roughly $24! The new town was called New Amsterdam.</p>
		<p>In 1664, English warships sailed into the harbor and Peter Stuyvesant, the Dutch governor, surrendered the settlement without a fight.  The Dutch regained the colony a few years later but then gave it to England under the terms of a peace treaty, swapping it for spice-growing islands in what is now Indonesia.  The English renamed the colony New York. In January 1785, shortly after America gained its independence, New York City became the temporary capital and George Washington was inaugurated there as the nation&rsquo;s first President in April 1789.</p>
		<p>Aside from hotel prices, New York was fabulous. We didn't plan what wanted to see and we didn't need to.  There is so much to do and everything is so close. The best value in town is the weekly "Metro" card that allows you to hop on an off the excellent subway and bus system as often as you wish.</p>
	</div>
</div>

<div class="clearfix">
	<div class="story followOn">
		<p>It was essential to see the <i>Statue of Liberty</i> but security precautions got in the way.  Before boarding the ferry, we had to go through metal detectors and bag searches similar to those at the airport. The ferry took us to the island where the statue stands but you can no longer go inside the statue or the museum at its base. I thought it was a bit rude that they didn't make this clear before we bought our tickets. I also thought it senseless since we had already been searched and if I wanted to blow up the statue, I'd come along at 2am in my own boat rather than take the public ferry.  We walked around it twice in the late-October cold and headed back to the wharf for the warmth of the next ferry.</p>
		<p>The disappointment at the statue was made up by the visit to the former immigration processing facility at nearby <i>Ellis Island</i>.  Between 1892 and 1954, 12 million people, mainly from Europe, began their new lives in America right here. For those fleeing oppressive governments, it must have been a tremendous thrill to see the Statue of Liberty as a reminder of their new freedom. New immigrants were interviewed to verify their identity and checked for various diseases.  Entry was not automatic.  Today you must get a visa before leaving your destination and the airlines won't allow you to board the plane if you do not have the necessary paperwork.  It seems in those days, a family might arrive from some poverty-stricken area in Europe, only to have grandfather sent back home because he failed the health test.  The shipping companies did some preliminary checking at the port in Europe but in an era before passports and visas they could only reject the most obvious.</p>
		<p>Not surprisingly, new immigrants tended to settle in areas of New York where there were already established communities from their home countries.  The pattern tended to be that the most recent and poorest arrivals would go to lower (south) Manhattan and then move further uptown and into the wider city as they became more established and integrated. In most cases, the community eventually became so dispersed as to be unrecognizable.  There is no longer a German area of Manhattan and Little Italy is now just a few streets catering to tourists.  On the other hand, Chinatown is enormous and growing.  While some probably feel threatened that the Chinese are consuming adjacent neighborhoods, I saw it more as an inability to integrate and therefore indication of failure. </p>
		<p>We did a walking tour run by the <i>Tenement Museum</i> on the "Lower East Side".  Tenements were buildings of cheap rental accommodation for new migrants.  Large extended families crammed into one or two rooms, often with no natural light. To improve conditions, an 1867 law stipulated that a toilet must be provided for every 20 people.  As you can imagine, it was almost impossible to stay clean and disease was common.</p>
		<p>The <i>Guggenheim Museum</i>, designed by Frank Lloyd Wright, is world-famous for its <a href="http://www.guggenheim.com/the_building.html" target="_blank">unusual building</a> with a cork-screw interior. However, the art in the museum was modern and with one exception, to my eyes, completely worthless. That exception was a huge white piece with a single black line running across the middle of it. At first it appeared to be abstract art but on closer inspection it was a photograph taken near to the ground of a snow-covered beach in Iceland, a narrow strip of dark ocean then overcast sky above. Brilliant. </p>
	</div>
	<div class="photo-gallery">
		<?
		setThumbnail("StatueOfLiberty1.jpg");
		?>
	</div>
</div>

<div class="story">
	<p>We did an excellent boat trip around the island (it is much longer than I imagined) and then looked over the aircraft carrier <i>Intrepid</i> which is docked as a permanent museum.  Various aircraft are arranged on the flight deck and the hanger below is crammed with naval history.</p>
	<p>Lan had trouble with one of her knees and by the time we got to the <i>Whitney Museum</i> she could hardly walk so we borrowed one of the museums wheelchairs. It is amazing how people get out of your way when you are in a wheelchair!  By the time we left she was feeling a lot better and I had to tell her to limp on her way out so it looked like she needed it.  The Whitney was full of interesting pictures, made so much more enjoyable by the (free) electronic guide. It looks like a telephone handset and selected pictures are numbered so you punch in the number and hear the story.  Unlike a guided tour, you can always see what it is you are hearing about and best of all, if you speak Japanese or German or whatever, the staff just punch a few buttons to reprogram it for your language. A similar system was used at the <i>Museum Of Modern Art</i> where there was some quite interesting material.</p>
	<p>No discussion of New York is complete without references to tall buildings. The guidebook mentioned that there would be a long wait if tried to get up the <i>Empire State Building</i> during the day so we went there at night for an excellent panorama of city lights. There are historical photos of the building at the observation level including one of a horse peeking out of the elevator! </p>
	<p>At that time it was just over a year since the <i>World Trade Center</i> towers had been brought down and remarkably, the cleanup was complete. We wanted to see the hole at "Ground Zero" but found that construction work was underway to build a walkway along the edge so it was fenced off and we couldn't see in. We were disappointed not to be able to get closer but as we left, we found an unexpected memorial to all those that lost their lives that fateful day.  A huge tree had shielded nearby St. Paul&rsquo;s church from the flying debris as the towers collapsed so it was virtually undamaged.  A fence with vertical iron bars surrounds the block and every available space was covered with a homemade memorial or "Missing" poster.  It was very moving because it was created spontaneously by those closest to the missing rather than manufactured by a committee.  The church housed an exhibition as it had been a base for those responding to the emergency and then those picking through the rubble.  The photo that sticks in my mind was a pair of civilian shoes on top of two of the iron bars of the fence-the owner was one of the rescuers that had raced to the scene and changed into work gear but then never returned. Very sad.</p>
	<p>I intended to visit both the Police and Fire Department museums since they both suffered so terribly that day but I left it until our last day only to find they are closed on Mondays. There was a caretaker at the Police Museum and we chatted briefly to him about his experiences.</p>
	<p>We went looking for the spot where John Lennon was killed but couldn't find it.  I knew that the Dakota Building was on 72nd Street but incorrectly believed it was on the eastern side of <i>Central Park</i>.</p>
	<p><i>Grand Central Station</i> has been extensively renovated so we went to look at the building but were surprised and delighted to see a stirring exhibition of photographs called <a href="http://www.ditlafrica.com" target="_blank">A day in the life of Africa</a> in of its side rooms.</p>
	<p class="endText">We wandered around low-rise <i>Greenwich Village</i> and took a short cable car ride to Roosevelt Island. One night we saw a Broadway show, <i>Thoroughly Modern Millie</i>, which was fun but expensive. We got our tickets at half price from the booth in Times Square but at US$48 each, I wonder who pays full price.</p>
</div>
<div class="photo-gallery">
	<?
	setThumbnail(["Intrepid1.jpg", "Turtle1.jpg", "FlatironBuilding1.jpg", "CentralPark1.jpg"]);
	?>
</div>


<div class="story">
	<p>Next: <a class="next" href=""></a><br>
	Previous: <a class="previousPage" href="<?= $rootRelativeUrl ?>letters/letter16c">The Netherlands</a></p>
</div>

