<? //dsp_letter12b.php ?>

<h2>Adventure to California</h2>
<div class="story">
	<p>My mother came and visited us for Christmas which was good as it was our first Christmas without dad and it gave us the excuse we needed to go on an expedition.  Actually, the expedition was in two parts as I met mum in San Francisco and we travelled around there for a week before flying to Denver then all three of us drove to Los Angeles and stopped at various places along the way.  I didn't see much point in spending much time in Denver as mum has already been here and being mid-winter, it was likely to be cold.  Indeed it was -6&deg;F/-21&deg;C by the time we got mum back home but I'm jumping ahead.</p>
	<p>We were lucky with the weather in SF as it was unusually clear and for the first two days it was quite warm.  We walked around the waterfront and saw sea lions unaware they were in a major city and unconcerned about all the people looking at them.  We looked at the outside of beautiful Victorian houses, rode on the cable car, visited Chinatown and saw the fort built to protect the bay against invading ships (never used).  We saw an awful lot of homeless people too.  I've commented before there are far more homeless people visible in Denver than there are in Sydney but it seemed there are many more in SF than Denver.</p>
	<p>Unlike Sydney, San Francisco does not extend north across the bridge because the land on the other side is the Golden Gate National Recreation Area.  I find the thought of Sydney stopping at the Harbour Bridge quite odd.  Close by is the town of Sausalito which struck me as being like Avoca, only much more upmarket and on the bay instead of the ocean.  Most interestingly, there are hundreds of house boats, which are obviously permanent in that they are on barges instead of shaped boats.  Some of them were almost as big and attractive as land-based houses.  Quite charming with the added benefit in the San Francisco area that they will ride out earthquakes well.</p>
	<p>We saw the coastal redwoods and the pyramidal Bank of America building, one of the most distictive skyscrapers anywhere.</p>
	<p>Just 150 km up the coast from SF is Fort Ross which was the most southerly outpost of the Russian empire and represented their claim on the California coast.  I had no idea they had come so far south.  Territory to the south was held by the Spanish who had established missions up the coast from Mexico.  However, when they had trapped all the sea otter and couldn't make a profit on agriculture, the Russian lost interest and in the 1830s sold to a Mr Sutter who had extensive land holdings in the state.  (They held onto Alaska until 1867 when it was sold to the US.)</p>
	<p>Sacramento is the state capital but it was too cold to walk around the old town district.  Mr Sutter had a "fort" here which acted as a welcome center for settlers coming to the area and he operated various businesses.  In 1848, just two years after the Mexican-American war passed California to the US, gold was discovered during construction of a sawmill on Sutter&rsquo;s land.  The secret soon slipped out and the California gold rush was on.  Sadly, prospectors and swindlers overran his property, stole his livestock, ripped up his fences for timber and Mr Sutter was left with almost nothing.</p>
	<p>We drove on to Yosemite National Park which we were pleased to visit in the winter.  The park is beautiful with a bit of snow  on the ground and ice in the river but it gets 4 million visitors per year and apparently, most come in July and August so it must be chaotic.</p>
	<p>We had three days in Denver which included Christmas and we had some of our friends come over.  There was also a lot of shopping done, mainly clothes for baby Eleanor and we had to send mum home with an extra box to carry all the stuff she bought which wouldn't fit in her suitcase.</p>
	<p>We hired a car for the second leg of our journey since we needed something with enough room for three people with luggage, had 4 doors, which was quiet and new enough to expect it not to break down in mid-winter miles from anywhere.Our car doesn't fit any of these criteria.  As a bonus, the Camry-sized Dodge Status could sit happily on 75mph (120km/h) and it had cruise control which allowed Lan to keep to the speed limit.  It looks good too.  I liked it - really liked it.</p>
	<p>I intended to stop at Bryce Canyon and Zion National Parks but mum wasn't feeling well so on the second day we went straight to Las Vegas.  Since the hotels are subsidized by gambling, the rooms are not too expensive as fancy hotels go and Lan contributed by losing a total of 40&#162; in a slot machine.  The Luxor is an amazing building in the shape of a hollow pyramid and follows an Egyption theme.  It cost US$700 million to build and is the second largest hotel in the world with over 4000 rooms and 4000 staff.  The pyramid is 196m square at the base and 107m (36 stories) tall and it is claimed 9 jumbo jets could fit inside the atrium.  One thing I found interesting was the elevators which are actually inclinators as they rise at 39&deg;.  They start and stop very gently since they move sideways as well as up and down and sudden movements would make guests fall over.  Like many things in America, the sphinx outside is arguably better than the original as it is bigger, newer and Napoleon&rsquo;s troops didn't shoot its nose off.</p>
	<p>The room was quite plain though and it occurred to me that they don't want the room to be too nice as you should be downstairs gambling.  We wandered around seeing the sites and it was interesting to see so much investment in wealth transfer instead of wealth creation.  As an architect&rsquo;s concept, I was also impressed with <i>New York, New York</i>.  Unlike most monster hotels which look like ... well, hotels, NY, NY is one building designed to look like several including the Chrysler and Empire State buildings.</p>
	<p>Hoover Dam is near Los Vegas so we visited it on the way out.  It is most impressive, and contrary to rumors, there are no bodies buried in the concrete wall - 96 lost their lives during construction but all the bodies were recovered except one that washed downstream.</p>
	<p>On to San Diego where we saw the Cabrillo National Monument which commemorates the Spanish explorer who sailed into the bay in 1542, just 50 years after Columbus "discovered" America.  (The records aren't clear but it appears that officials from the Immigration and Naturalization Service caught Cabrillo attempting to enter the US illegally and sent him back to Mexico.)   After that we saw the old town center which had been threatened with demolotion in the 60s but has been over-commercialized in order to save it that its character has essentially been destroyed anyway.  We also saw a Spanish mission, the first in California.</p>
	<p>The highlight of the city was Sea World.  Though outrageously expensive at US$38 for adults (we had a $5 discount coupon which helped), it was a lot of fun.  We particularly enjoyed the show put on by the killer whales, even though I'm aware that some people consider shows like this to be abuse of the animals.  You can see more at <a href="http://www.shamu.com" target="_blank">www.shamu.com</a>.  Lan commented that children in middle-class America are very lucky as they expect to go to attractions like this and Disneyland which are only dreams for kids elsewhere in the world.</p>
	<p>Our first day in Los Angeles was a bit disappointing.  Since LA never really gets cold, I thought the gardens would be worth looking at.  We went to the Descano Gardens which have 4,000 roses and 100,000 camellias but almost nothing was flowering.  I did learn a few interesting things:  The Roman Emporer Nero (68-54 BC) liked to have rose petals scattered on the path over which he was about to walk and to shower banquets with them.  In his usual manner of doing things to excess, he had such great quantities dumped on his dinner guests that a few of them suffocated!  On the theme of "better late than never", Thomas Hammer wrote <i>The Garden Book</i> in 1659 describing 21 varieties of rose but it wasn't published until 1933.  Modern roses are the result of breeding Europn roses with Oriental varieties which were brought to the west starting in 1789.  Josephine, empress of France by virtue of being married to Napoleon Bonaparte, had a garden in the early 1800s which contained all 250 varieties of rose known at that time.</p>
	<p>The next day we visited the <a href="www.getty.edu/center/center.htm" target="_blank">Getty Center</a> which is an art museum in spectacular new building in the hills above Santa Monica.  However we spent most of the day getting there and back. There is extremely limited parking (reserved 3&frac12; weeks in advance the day we went), which is unusual for America and amazing for Los Angeles which is so car dependent.  We took a local bus from Santa Monica but if it hadn't been Sunday, we would not have been able to park in the street.  I suspect this was done to limit the crowds and there is mention in the brochure that there may be long lines and it may not be possible to enter at all if capacity has been reached.  Getting in is bizarre as you have to take a train ride up the hill from the car park where the bus drops you off and then it seems you are going in the back door as the passage way is dark and so narrow that you have to walk single file if there are people coming in the opposite direction.  The train is slow and has only two carriages so they were running buses as well which seemed to defeat the purpose.  Anyway, it was worth the effort when we got to the top.  Amongst other things, there was an exhibition of 500 year old Flemish "illuminated manuscripts".  These books are exquisitely illustrated, often with gold leaf highlights but the tradition died out in the late 1500s, presumably because the printing press made reproduction so much cheaper.  Very interesting.</p>
</div>
<div class="photo-gallery">
	<?
	setThumbnail(["SeaLions1.jpg", "PeterGoldenGate1.jpg", "TransAmerica1.jpg", "Houseboats1.jpg", "YosemiteFalls1.jpg", "Stratus1.jpg", "LuxorOutside1.jpg", "LuxorInside1.jpg", "HooverDam1.jpg", "SeaWorld1.jpg", "Illuminate1.jpg"]);
	?>
</div>

<div>
	<div class="story followOn">
		<a name="grandcanyon"></a>
		<p>Mum flew back home and we spent an extra day or so in LA with Lan&rsquo;s relatives which was fun, especially getting to know 8 year old Patricia.  Then began the long drive home.  Three years ago we came home along the obvious route which is to approach Denver from the west along I-70 which takes you through the mountains and over two 11,000 ft/3350 m passes.  It snowed for most of the last 250 miles and was a generally awful drive.  Hoping to avoid snow and to see the Grand Canyon, we took a longer but more southerly route along I-40 to Albuquerque, New Mexico and then north up I-25.  We left LA later than we should have done and we made it to the Grand Canyon just as the sun was setting.  We looked at three more lookouts in increasing darkness which was disappointing but we did see enough.  It stuck me as being a combination of the Black Canyon of the Gunnison in Colorado (deep) and Canyonlands National Park in Utah (wide).</p>
		<p>That night we found a motel in Flagstaff but were unaware until too late that there was a railway line very close by and freight trains ran though the night.  Lan hardly slept and I woke up early.  Unable to get back to sleep we decided we may as well be in the car heading home so we were on the road at 5.25am.  Just as well as we had 750 miles/1250 km to cover and it meant that were home in the late afternoon instead of the evening which was good.  All in all, a great trip.</p>
	</div>
</div>
<div class="photo-gallery">
	<?
	setThumbnail(["GrandCanyon1.jpg", "I40NewMexico1.jpg"]);
	?>
</div>

<div class="story">
    <p>Next: <a class="next" href="<?= $rootRelativeUrl ?>letters/letter12c">Life in America</a><br>
	Previous: <a class="previousPage" href="<?= $rootRelativeUrl ?>letters/letter12a">News</a></p>
</div>
