<? //dsp_letter9a.php ?>

<div class="story">
   <p>23 November 1997</p>
   <p>Dear ................,</p>
   <p class="endText">A quick black & white letter this time since I want to make sure we get them all out by Christmas.  I've been disorganised this year as you may have noticed this is only our second letter for 1997&mdash;I managed three last year and four the year we left Australia.  It has been something of a difficult year for us and we weren't really motivated to write while we didn't have much happy news.</p>
</div>

<h2>News</h2>
<div class="story">
   <p>We did finally buy the unit we were renting but there were some severe bumps along he way.  If the original schedule had been kept we would have bought it 25th June.  However, about a month before that, the landlady called us and said that her husband had been very sick and would be coming back to Denver to stay with his daughter.  She therefore wanted to come back to Denver too and needed somewhere to stay and so the easiest thing for her was to have us move out!</p>
   <p>Fortunately, we found somewhere to live where we took over someone else&rsquo;s lease and we were committed for just 3&frac12; months.  Almost everyone wants a 12 month lease and short term rentals are normally expensive as they are aimed at executives.  This worked out well as the owners still wanted to sell once they found a new place to live without stairs and so we became owners on 24 Sept.  The whole thing was a bit stressful though and it cost us more rent.  Additionally, we were hurt by the change in exchange rates as it worked out to be better/easier to bring money over from Australia rather than borrow it here.  When we decided to buy, the exchange rate was A$1 = US79.5c; if we had bought in late June as expected, the rate was 76.5&#162; and when the time came to transfer money, it was down to 72&#162; so we needed more $A than we expected for the same amount of US$.</p>
   <p>Lan was out of work for six months too which was depressing.  Her previous job looked promising at first but it turned out to be a place where people shouted at each other in meetings and managers were incompetent and/or corrupt.  After a few months of this abuse, we decided enough was enough and the money didn't make up for the pain, so she quit.  The task of getting another job took much longer than expected and getting the paperwork sorted out with the Immigration & Naturalization Service involved a lawyer who made a complete mess of the application, thus delaying the time when Lan could start by over 5 weeks.  For some of that time she was technically here illegally and we were slightly concerned we would be deported.  Lan did finally start on 1st October and is already a star [she told me herself, so it must be true!].  She is working for the section of the local telephone company which produces the directories, both in paper and on the net [at http:///www.uswestdex.com] and it is good work since it is using up-to-date technology.  Most of the very few companies hiring foreigners try to put those workers in dead-end jobs at salaries way below market rates.  Lan had some insulting offers from some companies.</p>
   <p>There is nothing really exciting to report about my job except the usual complaints about incompetent management.  We have nearly completed a some equipment which I designed and we may yet get them done on schedule by the end of the year.  It is all very "common sense" engineering with no need to make difficult calculations as would be needed if you were designing an aeroplane or a dam-I've heard it called design on the "TLAR". principle which is an acronym for "that looks about right"!.</p>
   <p class="endText">One problem we have is the separation between the factory and us in the engineering office which complicates communication, makes it impossible for us to see problems first hand etc.  The real fix is put the engineers where the factory is but none of us want to move, the company politics wont allow it and they have little hope of hiring any because they are in the middle of nowhere and Minnesota&rsquo;s unemployment rate is about 3% so engineers can get jobs in the city.</p>
</div>

<div class="story">
   <p>Next: <a class="next" href="index.php\?fuseAction=letter9b">Travels and adventures</a></p>
 </div>
