<? //dsp_blizzard97.php ?>

<div class="story">
	<p class="endText">This is a report on the considerable adventure I had getting home from Denver Intenational Airport as the city was being shut down by the snow storm of October 24, 1997. I wrote this to email to everyone at work the following Monday to save retelling the story to everyone individually.</p>
</div>

<h3>You'll remember that it was snowing on Friday night ....</h3>
<div class="story">
   <p>I feel the need to tell a story: My plane from Minneapolis-St Paul was due in at 9.25 pm and I think we were just a few minutes late. The lady I sat next to on the flight had hoped her daughter was going to pick her up but she called and found out that she would have to take a shuttle bus. Since she hadn't done that before, she was a little apprehensive but as I had and we were going in the same direction, I suggested she take the same bus as me. Both of us had luggage to collect (parts for Alza in my case) and she decided she would go to the shuttle company desks to find out what the situation. She went to the shuttle bus counter and came back saying we could expect at least a 3 hour wait before one was available. I began to get worried that I would be home late so I called Lan to let her know.</p>
   <p>I know that there are more companies that come to the DIA than have desks inside so I went outside to see if we could get on one telling her I'd be back in a few minutes to report. The snow was blowing but I was hot from being fully rugged up while still inside the terminal. Most people waiting for transportation were just inside the doors ready to run out when something came. When I came in I couldn't find her so I wasted a bit of time searching. I gave up and decided the best solution was to take the regular RTD airport bus service to Stapleton figuring I'd get there at about 11.15 pm and then take the 105 which runs close to my house. I was confident that the 105 would run until about midnight and indeed the last ride of the evening leaves at 12.23 am.</p>
   <p>It was by now 10.45 pm and the RTD buses were being mobbed so I was pleased to be standing outside when my bus rolled in. As it turned out, not many people wanted to go to Stapleton but it was the beginning of the Bus Ride Through Hell.</p>
   <p>Once we pulled away from the kerb, it soon became clear that Peña Blvd was barely moving. We spent much of the time stationary and when we moved it was normally walking speed with great excitement being getting to jogging speed. This would have been bearable were it not for 4 teenage girls who had finished their shift at McDonalds and were catching the bus home. It seemed they laughed, shouted, screamed and clapped all the way home and ignored requests from me and others to be quiet. They were having a great time but no-one else was. Sadly, the girls were black and so no doubt, some people&rsquo;s predjudices were reinforced. There was a black man on the bus who was quiet but he&rsquo;s not the one we'll remember.</p>
   <p>After the girls got on, a group of Hispanic passengers boarded and I found their reaction interesting. Instead of ignoring them like the rest of us, they started talking even louder saying things like, "I'll have a burrito with no jalapenas" and "have you noticed that there are no Mexicans in our Spanish books". It seemed that they viewed themselves as downtrodden and hoped to elevate their status by pushing another group down.</p>
   <p>We spent perhaps 1½ hours on Peña Blvd until we got to our exit for a Park & Ride and then we continued on minor roads. It seemed I-70 had been shut down as there were no cars on it when we crossed over. Off the main road, cars were stuck in the snow and often abandoned and the bus had to drive around them. About 2 hours after we left, we arrived at another Park & Ride where the 4 girls got off and the remaining passengers burst into applause!</p>
   <p>Another hour got us to Stapleton but it was by now 1.45 am, and the last bus had left long ago. There is an enclosed bus shelter at Stapleton but I knew it is not heated and so I decided to get to one of the Stapleton-area hotels where I could be warm and call for a cab or perhaps catch a shuttle bus after it had dropped of some passengers. The snow was perhaps 12" deep by now, so calling Lan to collect me was out of the question as she would have got stuck somewhere. When we arrived at Stapleton though, visibility was so bad that I couldn't see the nearest hotel. I was not even sure which direction to go so I asked the bus driver who kindly allowed me to stay on the bus out of Stapleton and he dropped me in front of the DoubleTree hotel.</p>
   <p>Just walking 200 yards to the hotel was an effort with my small case and a box with no handle and my vision was being obscured by snow on my glasses. I walked past about 5 men trying to free one of the hotel&rsquo;s own shuttles which had become stuck in the driveway and was blocking someone trying to get out. I made it inside and took of my jacket, gloves and skarf so I could look business-like. I went to the reservations counter and asked if I could call a cab but she said they were no longer running but she would try for me. Indeed, we had seen two stranded taxis from the bus. She called but the lines were busy. I said, "Oh well, I'll just have to hang out in the lobby till morning then" but the bitch said, "I'm sorry, I can't allow you to do that". Trying to remain calm and co-operative, I asked if there was a 24 hour supermarket or some place open nearby I could go and she said no. She did suggest a Denny&rsquo;s but it was a mile and half away on the other side of I-70. I told her that it was hardly practical to walk there. I asked if there were any rooms available but there weren't and then I realized I only had $30 with me anyway and I would need triple that. This conversation was all while she was on hold waiting for the taxi company to answer so I said, "well if you can give me the number for the taxi company, I'll keep trying to stop holding you up". She gave me two numbers and directed me to the pay-phones past the elevators around the corner.</p>
   <p>Here I was safe as she couldn't see me and there was a shoe shine stand with 2 normal chairs. I couldn't go to sleep or look untidy lest Security ask why I was there so I had to look awake and busy or at least that I was waiting for someone or something. Fortunately, not sleeping doesn't bother me to much. From about 2 am to 4 am I wrote down everything that had happened during the night just to keep my brain active and I tried calling every 15 minutes or so. At 3 am I did get through but I was told there would be a 3 or 4 hour wait so I decided to forget the taxi (they're rear-wheel drive and probably not good on snow) and take the first 105 bus in the morning.</p>
   <p>About 4 am flight crews came downstairs expecting to go out on early morning flights. I heard that one of the hotel&rsquo;s shuttles just back had taken 3 hours in each direction and so they decided to stop service for hotel guests as they were concerned about being stranded. At about 4.30 am they decided to send one shuttle out just for the 20 flight crew but it was gone about 10 minutes (and probably 1/4 mile) before it got stuck. Another bus was sent out to collect the flight crew and then we heard that Peña Blvd and other routes to the airport were all closed or impassable.</p>
   <p>At 5 am I tried to call RTD to see if people were at the phones to find out when the first 105 left Stapleton but on Saturday, they don't start until 8 am. I decided it was too risky to walk the 1/2 mile to the RTD station as I wasn't confident there would be a bus till 6 am. By now the hotel was really coming back to life so about 5.30 am I had a cup of tea and a danish which made me feel better. At 6 am I called Lan but was surprised to only get the answering machine. I found out later that instead of assuming I could look after myself, Lan stayed up most of the night worrying and called the police and had me paged twice at DIA. The police told her that I was probably in a vehicle stuck on Peña Blvd.</p>
   <p>After calling Lan, I put on my jacket, scarf and gloves and headed out the door. Anyone who saw me probably wondered where I was going. It was cold and windy but walking through the snow was good exercise so just my ears and feet were cold. When I got to the bus shelter, I was amazed to see there were about 6 people there already who had just come in on other buses. The buses were running. At about 6.30 am, the 105 came and we were on our way.</p>
   <p>Short of being on a snow plough, a bus is probably the best way to get around on the road. On Colfax, there was an abandoned car roughly every 100 yards but we just cruised on through. Everyone on the bus was smiling, pleased to be out of the cold and on their way with some confidence that they would arrive. Many were on their way to work including a man from U-Haul who commented what a dreadful day it was for moving! He was expecting a busy day too as it was the last Saturday of the month. The man sitting opposite with me was going to work but he didn't have a key and was relying on someone else to make it there to let him in.</p>
   <p class="endText">Once off the bus, I only had a short distance to walk up Poplar St through 20" of snow which seemed to be less than other parts of town had. I made it home at 7.30am, just 10 hours after my plane arrived at DIA and 26 hours after I left home the previous morning. If I didn't get out on the RTD bus, I probably would have been one of those trapped in DIA for two nights. If only we got paid hourly ...</p>
</div>
<?
setThumbnail("PeterBlizzard1.jpg");
setThumbnail("SnowAngel1.jpg");
setThumbnail("BackSteps1.jpg");
?>
