<? //dsp_letter6b.php ?>

<h2>Trip to South Dakota</h2>
<div class="story">
   <p>July the 4th is Independence Day and it fell on Thursday, so most people took a 4-day weekend.   We had thought about going to see the Grand Canyon but since it is summer, we decided to go north to see the Black Hills of South Dakota in the hope it would be cooler.  We had a wonderful time although Thursday and Friday were both uncomfortably hot as it was 35&deg;C and our car has only "260" air conditioning (two windows, 60 miles/hour).</p>
   <p>We started our trip with an excavation site of mammoths before spending the evening at Mt Rushmore.  Since it was Independence Day, there was a special program of which the highlight was a man who was able to quote the <i>Declaration of Independence</i> from memory, explain what each section meant and comment on its historical significance.  I was not aware that the Revolutionary War (for independence from England) had already been underway for more than a year when the <i>Declaration</i> was written.</p>
   <p>You may have heard one of the opening sentences which says, <i>"We hold these truths to be self-evident, that all men are created equal..."</i> as it was quoted by Martin Luther King in his famous 1963 <i>"I have a dream"</i> speech.  It continues, <i>"that they are endowed by their Creator with certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness"</i>. Although it was not mentioned, I have heard that Jefferson, who wrote theDeclaration, was a slave owner!  Nevertheless, the <i>Declaration</i> of 1776 is a central document in American history and its ideas have been used in other revolutionary struggles.  The Declaration stated why the 13 colonies wanted to rid themselves of English rule and by publishing it, the Americans hoped to gain foreign assistance and that the 13 colonies would stay united.  Ironically, the old French regime sent money and military supplies to the revolutionaries and later declared war on the English changing the balance of the war but the success of the Americans helped inspire revolution back in France.</p>
   <p>The Declaration lists a number of grievances against the king but most fall under the general heading of English rule being undemocratic.  Our commentator noted that the Jefferson and the other men who signed it were commiting treason against the English and would have been tortured and killed if the rebellion had been put down and they were captured.  As Benjamin Franklin put it, <i>"We must all hang together, or assuredly, we shall all hang separately"</i>!</p>
   <p>Unfortunately, when presidents' heads were carved from the mountain, there was little recognition that the area is sacred to local indian tribes.  The tribes took the government to court over a broken treaty signed with "Red Cloud" who I mentioned in an earlier letter.  The tribes were offered $100 million but they refused saying they wanted the land back.</p>
   <p>In recognition that native-Americans have heroes too, another mountain nearby is being carved depicting "Crazy Horse" riding into battle (below, model in foreground and the mountain behind).  In 1876, Crazy Horse led the indians against the US Army and won, killing General Custer and all his men.  The final sculpture will be HUGE.  The head is as tall as a nine-storey building. One man (of Polish descent, not indian) was invited to do something and he started in 1947.  He worked alone most of the time until his death in 1982 and his family has since taken over. The face is virtually finished and I think that as it progresses, there will be more and more paying visitors so work should speed up.  They have turned down government money.</p>
   <p>We visited Jewell Cave which is now the 4th longest in the world with 170 km of known passages but still being explored.  It is a "breathing cave" meaning that when the atmospheric pressure changes outside, there is a noticable wind at the entrance as air is sucked out, or pushed into, the cave.  At this cave, "breathing" creates a powerful blast of wind. Lan invented the word <i>broccolized</i> to describe some of the fomations in the cave. Jenolan Caves in NSW are not so big but have a much greater concentration of features.</p>
   <p>On the way to the "Badlands", we stopped to visit the drug store (pharmacy) at Wall, South Dakota.  On the roads around Wall, there are an incredible number of billboards promoting the store, perhaps one every kilometer and more as you get closer.  They have messages like <i>Free coffee and donut for Vietnam veterans</i> (we weren't sure if Lan qualified) and <i>Kids love Wall Drug</i>. Some of the signs are in odd places such as in the middle of a lake and it became a game to spot the next sign. We saw signs as much as 200 miles from the store and we are told there is one in Amsterdam.  To my surprise, they do still sell drugs but the business is mainly an icecream palour, restaraunt and souveneir shop with historical photos, models and amusements.</p>
   <p>At the Petrified Forest (where petrified means that it has been turned to stone), the tree stump I am leaning against (right) looks 20 years old.  Actually, it is 120 million years old!</p>
   <p>I was impressed by Devil's Tower which Lan visited last year with her family.  On the day we visited there were 10 people at various points up the vertical face of the tower and there are about 1000 succesful ascents each year.  It is 260 m from the base to the top but the last 80 or so are not vertical.</p>
   <p class="endText">Those of you who have been on a "beach mission" with me will be surprised to know that we camped in a tent while we were away.  You would think I would have learned how horrible it can be.  We borrowed a tent and survived a thunderstorm that made the tent flap around so much that I worried about having to return the tent in several pieces.  Tent design has improved enormously since the crude things that we used on scout camps.  Just having a sewn-floor makes a huge difference as you can crawl inside and be in a clean environment.  It was very small though with just enought room for our inflatable matress.</p>
</div>
<div class="photo-gallery"></div>
	<?
	setThumbnail(["LanMtRushmore1.jpg", "CrazyHorse1.jpg", "MenAtWork1.jpg", "BadlandsSDakota1.jpg", "PetrifiedLog1.jpg", "DevilsTower1.jpg", "Camping1.jpg"]);
	?>
</div>

<div class="story">
   <p>Next: <a class="next" href="index.php?fuseAction=letter6c">Life in America</a><br>
	Previous: <a class="previousPage" href="index.php?fuseAction=letter6a">Our news</a></p>
</div>
