<? //dsp_letter15c.php ?>

<h2>September 11 and all that</h2>
<div class="story">
	<p>The day of the attacks started normally enough. I dropped Lan off at her office, turned on the radio and then drove on to my office a few miles away. It was only half an hour after the first plane hit the World Trade Center and the normal program had been interrupted but it was clear that nobody had a clue what had happened. At work a little while later, someone told me that a plane had crashed into the WTC and I asked if it was foggy in New York. It wasn't. You may be aware that a bomber got lost in heavy fog in 1945 and flew into the Empire State Building.</p>
	<p>Obviously, it soon became clear that the crashes were not accidents. It was a horrific event and it is beyond imagination what it must have been like for those trapped on the upper floors to feel the building give way beneath them. Still, it is amazing that the carnage was not worse. The last official toll I saw was 2830 killed, a very small fraction of the buildings' full occupancy. It is a great credit to the architects that both buildings withstood the initial impact and stayed up for two hours allowing most to escape.</p>
	<p>While is debatable whether the attacks could have been prevented, it was disappointing to hear the head of the National Security Council say at a press conference months later, <i>"I don't think anybody could have predicted that these people &ndash; would try to use an airplane as a missile."</i> Given that Japanese kamikazes had pioneered the technique, I thought it would be especially appropriate to fly a plane into a Japanese whaling ship as a protest but I hadn't thought of hijacking an airliner to do it. Other people have though and it has actually been attempted <i>twice</i> before, both in 1994. One was an Air France jet bound for Paris, hijacked before it left the ground in Algeria. The plan was to fly into the Eiffel Tower but the plane landed in Marseilles to take on extra fuel allowing French commandos to storm the plane. <a class="external" href="http://en.wikipedia.org/wiki/Air_France_Flight_8969" target="_blank">Flight 8969.</a> The other was in America. Read the amazing but largely unknown story of <a class="external" href="http://www.suite101.com/article.cfm/history_of_flight/79391" target="_blank">FedEx flight 705</a>.</p>
	<p>The attacks brought out both the best and worst of America. The out-pouring of generosity after the attacks was unbelievable both in cash donations and offers of all help imaginable. I thought of donating blood but when I called, there was a recorded message saying that the earliest the center could see me was over a month away. Sadly, little blood was needed, as few were injured&mdash;people either got away physically unhurt or they were killed.</p>
	<p>There were attacks against Muslims but as others sought understanding, conversions to Islam quadrupled! I was pleased that the President made a special point of saying that the vast majority of American Muslims were worthy citizens and deserved our support and not hatred. The country was covered in American flags and a many cars sport stickers proclaiming "United we stand". There were rallies and speeches. However, there is a fine line between patriotism and nationalism and I read an article expressing a minority opinion that the display of national pride reminded the author of the Nazi Nuremberg rallies.</p>
	<p>If you must be killed, it is certainly better to do it as part of a large group&mdash;US$1.4 billion was raised to help the families of victims and others adversely affected such as those who lost their jobs. As bad as it was, fewer people were killed on 11th September than an average month on America&rsquo;s roads. Get killed by a drunk driver and there are no telethons, no memorial funds, no interest. Sadly, some of the money raised has been at the expense of other worthwhile causes. One large concert to raise money for AIDS in Africa was converted at the last minute to a concert to aid victims of the attacks.</p>
	<p>At the risk of being controversial, I want to say that I believe the &quot;war on terrorism&quot; is a sham. Its fundamental problem is that it is fighting the <i>symptoms</i> and not the <i>disease</i>.</p>
	<p>It seems to me that there are two ways to deal with hatred directed against the United States. One way is to make the country a harder target to hit by improving intelligence, tightening airport security, increasing defense spending and so on. The other is to look inward ask why some people hate America so much that they are willing to kill themselves to harm us and then see if we can modify our behavior to be less offensive.</p>
	<p>There has been effectively zero effort by political figures to answer the question posed by the second option. The symptom is terrorism but the disease is an arrogant and inconsistent foreign policy. Soon after the attacks, an Arab sheik gave $10 million to New York to help the victims but made some comments that perhaps some aspects of American foreign policy were fueling the rage that led to the attacks. His money was returned. There will be no discussion of policy. Indeed, statements such as <i>&quot;they hate our freedom&quot;</i> by the President only serve to obscure the real issues as it suggests that those who hate America are irrational and want to take away our fundamental rights.</p>
	<p><a name="Note1Ref"></a><b>Most Americans are kind, decent people</b> and would be horrified to know that much of what is done by America outside the country takes away the freedom of other peoples. If only the media reported it<sup><a href="#Note1">Note 1</a></sup>. America&rsquo;s policies in the Middle East appear to be based on two principles: ensuring the continuing flow of cheap oil and unquestioning support for Israel.</p>
	<p><a name="Note2Ref"></a>The former ensures that brutal and corrupt regimes are supported throughout much of the Arab world. Although the human rights situation in Saudi Arabia is almost as bleak as Afghanistan under the Taliban, there is no criticism. Saddam Hussein was America&rsquo;s friend in the region before the Gulf War<sup><a href="#Note2">Note 2</a></sup> because he fought against the Iranians who, in a popular revolution, had humiliated America by sweeping aside the hated Shah and took embassy staff hostage for over a year.</p>
	<p>The latter means that Palestinian rights are ignored and that American-made weapons are used to attack them. I think few Americans know that three Palestinians have been killed for every Israeli but Israel presents itself as the victim. A forgotten footnote to the Gulf War was that Saddam Hussein offered to withdraw his forces from Kuwait if Israel would withdraw from the areas they took by force in the 1967 Six Day War. The offer was ignored, so while Iraqi occupation of Kuwait was unacceptable and would be repelled by force, Israeli occupation of the &quot;Occupied Territories&quot; continues to this day. American politicians say they support Israel because it shares our democratic values which is true to an extent, though you can make a case that the population movements that accompanied Israeli&rsquo;s founding in 1948 would today be called &quot;ethnic cleansing&quot;, so many potential voters are excluded. What they don't mention is political contributions: check for yourself on the web site of <a class="external" href=" http://www.opensecrets.org" target="_blank">Center for Responsive Politics</a>. Pro-Israel groups gave more in the 2000 election cycle than the pro-gun lobby, though less than the tobacco industry.</p>
	<p>Just in case you were worried about me, I'd like to say that I'm against all oppression, no matter who is doing the oppressing: it was wrong for Nazis to kill Jews but it is also wrong for Israelis to kill Palestinians and take their land.</p>
	<p>Hardening America against attack, while failing to address the root causes of terrorism, appears doomed to failure. The Vice President is right when he said it is only a matter of <i>when</i> and not <i>if</i>. It is not possible to protect everything all the time. Given the demonstrated effectiveness of flying a large plane into a tall building but the new difficulties of hijacking a plane, I predict that next time, the terrorists will just <i>buy their own plane</i>. You read it here first. I did some poking around the Internet and it appears you can buy a very used 707 or even a 747 for US$1 to $2 million. It only has to make a few flights. I couldn't find any prices but I suspect old Soviet airliners are almost being given away.</p>
	<p><a name="Note3Ref"></a>Since September 11, America has given its enemies even more reasons to hate it. It appears that American bombs have killed more Afghan civilians than Americans were killed in the terror attacks<sup><a href="#Note3">Note&nbsp;3</a></sup>, the President has told the Palestinians to elect someone else as their leader while describing Ariel Sharon as a &quot;man of peace&quot;<sup><a href="#Note4">Note 4</a></sup>. Americans would rightly be outraged if, for example, the Chinese told Americans that they refuse to deal with Mr. Bush until they elect someone else. Prisoners taken in the &quot;war against terrorism&quot; are not accorded &quot;prisoner of war&quot; status. We will probably never know what really happened but it appears that the US gave at least a wink and a nod to the military coup that overthrew the democratically elected government of Hugo Chavez in Venezuela.</p>
	<p>Perhaps more worrying because it has received so little attention, are actions in the ex-Soviet republics of central Asia, some of which surround the Caspian oil fields. To its credit, America had been trying to promote democracy and an open society but that has ended. Given the new willingness of the US to fight Islamic fundamentalism, some dictators in these countries have allowed, even invited, America to establish military bases on their soil for the &quot;war against terrorism&quot;. However, Islamic groups are often the only credible opposition and America has looked the other way while press freedoms have been curtailed, leaders have been arrested and much of the oil wealth has gone in the pockets of a tiny elite. Now that they are there, the bases may now be more important to protect the rapidly growing interests of US oil companies.</p>
	<p class="endText">If you missed it, I urge you read a refreshing alternative view on America in <i>Beyond Good and Evil</i>, an essay that appeared in the <i>Sydney Morning Herald</i>. (No longer on the <a class="external" href="http://www.richardneville.com" target="_blank">author&rsquo;s web site.)</a></p>
</div>
<div class="photo-gallery">
	<? setThumbnail("FakePhoto1.jpg"); ?>
</div>

<div class="story">
	<p>Next: <a class="next" href="index.php?fuseAction=letter15d">And in other news</a><br>
	Previous: <a class="previousPage" href="index.php?fuseAction=letter15b">New Orleans</a></p>
</div>

<div class="story footnotes">
	<p>Notes:</p>
	<ol>
		<li><a name="Note1"></a>ABC&rsquo;s <i>Nightline</i> program is a notable exception. On the general topic of bias in US media, read this fascinating comparison of coverage after both the Soviets and the US shot down civilian airliners: <a class="external" href="http://www.fair.org/extra/best-of-extra/kal007-iranair655.html" target="_blank">KAL 007 and Iran Air 655: Comparing the Coverage</a> <br><a href="#Note1Ref" class="noteGoBack">Go back</a></li>
		<li><a name="Note2"></a>See details of Saddam Hussein, America&rsquo;s friend in <a class="external" href="http://www.zmag.org/zmag/articles/ShalomIranIraq.html" target="_blank">The US and the Iran-Iraq War</a> <br><a href="#Note2Ref" class="noteGoBack">Go back</a></li>
		<li><a name="Note3"></a>See report by Marc Herold of the Uni. of New Hampshire <a class="external" href="http://pubpages.unh.edu/~mwherold/AfghanDailyCount.xls" target="_blank">Daily Casualty Count</a> <br><a href="#Note3Ref" class="noteGoBack">Go back</a></li>
		<li><a name="Note4"></a>Yassir Arafat may well be "compromised by terror" but so is Ariel Sharon, though I would argue, only more so. His own government found him &quot;indirectly responsible&quot; for massacres in Lebanese refugee camps in 1982 that killed at least a thousand Palestinians. Documents leaked since the inquiry indicate more direct control. The Israeli attack on Lebanon left around 20,000 dead. See a summary of his work <a class="external" href="http://www.danpal.dk/vidensbase/baggrund/bg-033.htm" target="_blank">gaining land at the expense of peace</a>. <br><a href="#Note3Ref" class="noteGoBack">Go back</a></li>
	</ol>
</div>
