<? //dsp_letter9b.php ?>

<h2>Travels and adventures</h2>
<div class="story">
   <p>My company is based in Minnesota and I've had to make a few trips up there.  While Lan was unemployed, I arranged to be in the factory Mon-Wed but Lan and I flew up early Saturday so we could be tourists over the weekend.  We spent a day looking around the "twin cities" of Minneapolis & St Paul which were originally separate, but like Sydney and Parramatta, have grown and filled the space in between.   We started with the impressive State Capitol building and a gothic-style cathedral.</p>
   <p>The 3750 km Mississippi River runs through the twin cities and even though it is only about 20% of the way to the ocean, it is already 300 m wide at Minneapolis.  [Of course on its way to the Gulf of Mexico it gets very big.  Annual discharge is 600 km&sup3; of water, 0.3km&sup3; of silt.]  Over the past century, the construction of dams, locks and the dredging of channels has allowed progressively larger vessels to travel on the river and it is now possible for barges 2.7 m deep to travel all the way from the Gulf of Mexico to Minneapolis.  We watched boats being raised and lowered 15m as they moved through the locks which bypass the St. Anthony falls..</p>
   <p>Most interesting of all was the <i>Museum of Questionable Medical Devices</i> which had all manner of machines and treatments that were supposed to cure various conditions.  There was a box with a light bulb inside which you were supposed to stare at.  By changing the combination of coloured filters in the two eye pieces, it was claimed that most illnesses could be treated.  Devices like this were harmless to the extent they didn't inflict injury although they may have made some think they did not need to seek conventional medical treatment.  Others, used electric shocks, radiation or chemicals like mercury and definitely did more harm than good.  It is not surprising that these devices flourished last century when conventional medicine could do little but I was amazed that many of the exhibits were modern with one claiming to cure AIDS.  It made clear the need for government regulation of drugs & medical products as there are many greedy people willing to take the money of people desperate to find cures for their ailments. The science behind modern medicine is now so complicated that it is way beyond the ability of average citizen to make rational choices without an independent authority screening out treatments with no scientific basis or testing.</p>
   <p>The next day we drove north to Duluth on the shore of Lake Superior which is so big it appears to be an ocean.  We visited two light houses, saw and old steam locomotive and huge piers for loading iron ore into ships.  Lake Superior freezes over in the winter and storms in the autumn make these waters some of the most treacherous in the world.  You may remember a 1970s song about <i>The Wreck of the Edmund Fitzgerald</i>.  I had thought it was long ago on the ocean but it was 1975 on Lake Superior when an iron ore ship was broken up in a severe storm.</p>
   <p>After work on Tuesday, we went to the <i>Mall of America</i>, a huge shopping center with an indoor amusement park.  The winter in Minnesota is so cold for so long that most rational people don't go outside, so it sort of makes sense to combine department stores with roller coasters.  The Mall now attracts 42 million visitors a year (!) making it the biggest tourist attraction in the US, beating out more likely contenders like the Disneyland..</p>
   <p>My last trip home from the factory provided some entertainment as it coincided with a <a href="index.php?fuseAction=blizzard97">blizzard</a> shutting down the city!  I got back to Denver airport about 9.30pm on a Friday night and should have got home by 10.30pm.  However, heavy snow meant shuttles buses were running very slowly and I heard there was at least a 3 hour delay.  I decided to take the regular airport bus and change to a local bus.  Unfortunately, what should have been a 40 minute trip took 3 hours because of all the stranded cars blocking the roads and it was made worse by 4 girls who yelled, laughed, clapped and sang most of the way.  We arrived at the bus terminal at 2am, the end of the route and an hour and a half too late for the last local bus.  I got to one of the nearby hotels and asked to call a taxi but the desk clerk told me the taxis were not running but she would try anyway.  She couldn't get through.  The hotel was full and in any case, I didn't have enough money to stay.  I said I'd have to wait out the night in the lobby so I could catch the bus in the morning but she said <i>"I'm sorry, I can't allow you to do that"</i>!  I was stunned.  I asked if there was anywhere close I could go to get out of the storm.  She suggested a 24-hour restaurant but it was 2.5 km away.  I asked for the number of the taxi company and said I would try and get through so she directed me to the pay-phones around the corner where I was safe.</p>
   <p>From about 2 am to 4 am I wrote down everything that had happened during the night just to keep my brain active and I tried calling every 15 minutes or so.  At 3 am I did get through but there would be no taxis for 3 or 4 hours by which time the buses would be running.  At about 4 am flight crews came downstairs expecting to go out on early morning flights.  I heard that one of the hotel&rsquo;s shuttles to the airport had taken 3 hours in each direction and so for safety, they decided to stop service for hotel guests.  At about 4.30 am they decided to send out one shuttle just for the 20 flight crew but it was gone 10 minutes (and probably 1/2km) before it got stuck.  Then we heard that all roads to the airport were closed or impassable.</p>
   <p>At 6 am I walked perhaps 1km to the (enclosed) bus stop and was amazed to see 6 people already there.  At about 6.30 am, we were on our way and short of being on a snow plough, a bus is probably the best way to get around as it was able to get through where 4WDs were stuck.  Everyone on the bus was smiling & chatting, pleased to be out of the cold and on their way with some confidence that they would arrive.  Once off the bus, I only had a short distance to walk up Poplar St through 0.5m of snow which was less than other parts of town but 3-4 times as much as we has seen in Denver.</p>
   <p class="endText">I made it home at 7.30am, 10 hours after my plane arrived and 26 hours after I left home the previous morning.  If I didn't get out on the bus, I probably would have been one of those trapped in the airport for two nights.  I found out later that it was -25&deg;F/-31&deg;C with wind chill (the effective temperature when the wind is taken into account) so being outside was life-threatening.  Indeed, 6 people (and 30,000 cattle!) died in Colorado.  My boss called the hotel and complained and we got a free dinner at the restaurant so all is forgiven.</p>
</div>
<div class="photo-gallery">
	<?
	setThumbnail(["MNStateCapitol1.jpg", "Cathedral1.jpg", "TwoHarbors1.jpg", "SplitRockLight1.jpg", "MallOfAmerica1.jpg", "InsideMall1.jpg"]);
	?>
</div>

<div class="story">
   <p>Next: <a class="next" href="index.php\?fuseAction=letter9c">Interesting things</a><br>
	Previous: <a class="previousPage" href="index.php?fuseAction=letter9a">News</a></p>
</div>
