<div class="story">
	<p>{Originally sent as an email on 27<sup>th</sup> December 2020.]</p>
	<p>I did not intend this to be a Christmas/New Year letter as I wanted to send it in late October on the anniversary of our arrival in Portugal but we were busy then and writing captions for photos took longer than it should so here we are. It is now ten months since my last general update and I have another set of photos so you can see what we&apos;ve seen:</p>
	<p><strong>Portugal: Feb - Nov 2020</strong></p>
	<ul>
		<li>the <a href="https://photos.app.goo.gl/TMiUrwnyUabJcFe28" class="external" target="_blank">full set</a> with 205 photos</li>
		<li>a <a href="https://photos.app.goo.gl/i6dZwLdAJJdkT3B29" class="external" target="_blank">summary version</a> with just 25 photos</li>
	</ul>
	<p>As before, <strong>almost every photo has a caption</strong> (except for close-up photos of tiles), so make sure that you turn the captions on. I don&apos;t expect you or anyone else (well, maybe 2) will review all of them; there will be no quiz.</p>

	<p>As a bonus (or punishment?), there is another set and summary set for our two trips to the Azores.</p>
	<p><strong>Azores: Mar &amp; Sep 2020</strong></p>
	<ul>
		<li>the <a href="https://photos.app.goo.gl/y7A7ikdH9zn3qDeT9" class="external" target="_blank">full set</a> with 216 photos</li>
		<li>a <a href="https://photos.app.goo.gl/Kr3RNgd7E62JtjzH7" class="external" target="_blank">summary version</a> with just 25 photos</li>
	</ul>

	<p>As with you and everyone else, COVID-19 upended our plans for 2020 and so we are not having the retirement that we intended.</p>
	<p>Portugal was doing quite well in the pandemic until September when the number of new cases started rising gently and then in October they rose sharply as you can see on the &ldquo;Evolution of new cases&rdquo; chart on the <a href="https://covid19.min-saude.pt/ponto-de-situacao-atual-em-portugal/" class="external" target="_blank">government&apos;s data page</a> on the topic. Overall, the rate is a little over half of the average for the whole of America, or about the same as DC and VA. There was a complete shutdown from mid-March for two months but now, while there are some restrictions on movement, most business and tourist attractions are open with reduced numbers of people inside. There was no panic buying here so we never faced the shortages that you may have experienced.</p>
	<p>I enjoy listening to podcasts while getting dressed, mopping floors and washing up after dinner. If you have time for one more podcast, I highly recommend <strong><em>Cautionary Tales</em></strong> with Tim Hartford who has done several podcasts for the BBC such as <em>50 things that made the modern economy</em> which you might have heard. In each episode he looks at a disaster and sees what we can learn from it and you might start with <a href="https://timharford.com/2020/06/cautionary-tales-ep-9-fire-at-the-beverly-hills-supper-club/" class="external" target="_blank"><em>Fire at the Beverly Hills Supper Club</em></a> since that is surprisingly relevant to how we responded to COVID-19.</p>
	<p>We spend most of our time at home when we thought we would be out and about. We both do an hour or so per day studying Portuguese, Lan has enjoyed numerous Korean dramas (she recommends <em>Reply 1988</em> which was recommended to me by our teams intern last year and <em>Crash Landing On You</em>) and I&apos;m on the computer doing one thing or another. I&apos;d like to say that I had read several books and learned some new programming skills but that has not happened. Given that we are not working and don&apos;t have children, it is hard to account for where the time goes but it is rare for me not to have something that needs researching (how to file a Portuguese tax return is going to be a challenge shortly!) and we do spend more time than before reading the news - there has been rather a lot of it in the US over the past several months and it didn&apos;t slow down after the election.</p>
	<p>In October we moved to a new apartment (<a href="https://what3words.com/laptops.strike.using" class="external" target="_blank">here</a>) on the 24th floor of one of Lisbon&apos;s taller buildings. The old apartment had a fabulous view and was very close to a railway station but it had a dreadful kitchen, more space than we needed and was very cold last winter because all the window and doors leaked cold air. We are now in a much smaller apartment but it is more modern and has a far better kitchen though the refrigerator is about half the size of the one we had in DC and smaller than the one in the other apartment.</p>
	<p>This apartment also has a great view though it is very different: we can see the water but there are few boats and no ships this far up the river where it is <a href="http://fishing-app.gpsnauticalcharts.com/i-boating-fishing-web-app/fishing-marine-charts-navigation.html?title=Lisboa+Alcantara+to+Canal+do+Montijo+boating+app#11/38.7683/-9.0981" class="external" target="_blank">wide but shallow</a>, so the more interesting thing to see is the other buildings in the area, many of which were built for <a href="https://en.wikipedia.org/wiki/Expo_%2798" class="external" target="_blank">Ëxpo &apos;98</a>. We can now also watch the free-to-air TV channels too which will be useful when my Portuguese gets to the point where I can follow along; the rooftop antenna was removed from the old building some years ago. We had to buy some furniture though there was a dining table, four chairs and some storage cabinets left behind by a previous tenant so that was helpful.</p>
	<p>We are still within walking distance of a Metro station and Lisbon has an excellent bus network so we have had no need to own a car while we have been here. When it is safe to travel again, will get a small car since many tourist attractions are essentially inaccessible by public transport. The news about vaccines is very encouraging but since Portugal is a second-tier country and I am not in a high-risk group, I am not expecting to get it until the middle of next year.</p>
	<p>I registered for the Lisbon marathon this year but like all similar events around the world, it was cancelled and I&apos;ll be participating next year instead. I am too lazy to exercise if I don&apos;t have a specific objective so I&apos;ve not had any real exercise since June - unless you count walking up 24 flights of stairs to get warm which I&apos;ve done 3 times so far (on separate days, not all at once).</p>
	<p>The national government runs language classes for new immigrants and when we registered at the end of January, we were told they would start "in a few weeks". Then the pandemic came so that was delayed until September. They are three evenings per week and initially they were in a school but the rise of infection rates forced classes to go online. Lan and I were already diligent learning with phone apps (though they are for Brazilian Portuguese) which is good since the class is moving very fast! I know I have learned a lot but it is discouraging that it is still not enough to be useful. Learning a language is hard but Portuguese is relatively simple compared with most others since it uses the Latin alphabet, is largely phonetic once you understand the variations from English in how letters are pronounced and so many words have an obvious English equivalent, also derived from Latin &ndash; today&apos;s favorite is comfortable/confortável.</p>
	<p>Lan is doing much better than me and is able to have simple conversations with random strangers though this is her 4th language, one of which is French, so she knows how to learn and also understands English grammar far better than I do - it was a revelation to me a few days ago that in English, we use "I" for the subject of a sentence and "me" for the object. Similarly with "he/she" and "him/her". I had no idea! Our big problem is that we don&apos;t have anyone to speak to regularly. We say hello at the supermarket checkout and that&apos;s about it. Whether we decide to stay here forever depends in part on whether we can learn the language.</p>
	<p>Since we aren&apos;t working and not in full-time study, I was expecting to have to make an effort to make new friends but the pandemic has closed off opportunities for clubs and various meet-ups we might have become involved in. We have just two Portuguese friends: one ran the Airbnb where we stayed for three weeks when we arrived and the other was working in a palace gift shop the day we visited three days after it reopened in May and there was almost no one else around. Both women are married (the husband of the first speaks good English too) and have a young child. I also met a very interesting American man while waiting to register at the local health center and we&apos;ve seen him a few times.</p>
	<p>Lan cooked a full Thanksgiving dinner and that was an adventure. You can&apos;t just walk into a supermarket and buy a turkey (though you can buy an <a href="https://photos.app.goo.gl/KGNUki2XDAU5jkkp9" class="external" target="_blank">octopus</a>!) but Lan was confident enough of her Portuguese to enter a butcher&apos;s shop and order one. She asked for a smaller one and we were supposed to collect it the day before Thanksgiving. Unfortunately, he didn&apos;t get one saying he had a big one we could buy. So we went to a different butcher who said she could get it overnight. It was ready at 8am and Lan spent a second day in the kitchen. The result was great, of course and it was shared with the two Portuguese women to take home to their families.</p>
	<p>To keep my Green Card alive without too much arguing, I should be back in the US by the end of January but I have to weigh the risk of losing the Green Card against the risk of getting very sick, so I&apos;ve not made a decision yet but I am leaning toward waiting until I get vaccinated, probably mid-2021.</p>
	<p>I&apos;d love to hear your news to so please write when you can.</p>
	<p>Peter</p>
</div>
<?php
setThumbnail(["photoName"=>"photoSetPortugal3.jpg", "overrideURL"=>"https://photos.app.goo.gl/TMiUrwnyUabJcFe28"]);
setThumbnail(["photoName"=>"lighthouseAzores.jpg", "overrideURL"=>"https://photos.app.goo.gl/y7A7ikdH9zn3qDeT9"]);
?>



