<? //dsp_letter4c.php ?>

<h2>Strange and curious things</h2>
<div class="story">
   <p>Denver recently hosted the 46th <i>Annual Convention of the Christian Booksellers Association</i> which covered an area of 6 football fields. Apparently, with the exception of furniture and major appliances, it is possible to outfit an entire house in "Christian" products - bird feeders to body lotions, luggage to lamps.   My personal favourite is a car sun visor that says <i>Jesus is Lord</i> on one side and <i>Need help! Please call Police</i> when you turn it over!  You also have to question the motives of some of the promoters though.  Consider for example, the mission statement of religious publishing conglomerate Thomas Nelson Inc: "to  produce and market products that honor God and serve humanity, and to enhance shareholder value"!</p>
   <p>A lot of shops have big signs outside proclaiming <i>Now Hiring</i>.  Lan wonders if they will pull them down in the next recession and replace them with banners saying <i>Now Firing</i>.</p>
   <p>There are many words that can be used to describe Colorado drivers but patient and courteous are not among them. Almost every intersection with a traffic light has a left turn lane and a left turn arrow at the beginning of the cycle.  Despite this, normally one or two but sometimes 4 or 5 cars will try and sneak through on the orange/red.  On my way to work, I have to make a left turn where there is normally a queue of cars and I get through on the second cycle.  On most days, some jerk (a different one each day) decides he (it&rsquo;s normally a man) doesn't need to wait like everyone else so he drives to the front and forces his way in.  The prize for arrogance though has to go the driver who overtook cars doing 90-100 km/h by passing in the breakdown lane!  Nationwide. about 500 Americans are killed each year when their car is flattened by a train at a level crossing.  In about half these cases, there have been boom gates to block traffic entering the crossing but the driver has driven to the other side of the road so he (again, I'm sure most would be men) can drive around the boom gate.  What a time saver!</p>
   <p>Interesting little-known fact: just 40% of women&rsquo;s swimsuits bought in America actually get wet.</p>
   <p>K-Mart has rifles and ammo on sale for Christmas.</p>
   <p>Somewhere in America (I missed where) the locals have come up with a spectacular way to get rid of the pumpkins left over after Halloween. The men used to have an anvil throwing competition but one of them said that they are getting older now and it was taking them several days to recover.  As an alternative, someone came up with the idea of a pumpkin throwing competition but with machines to do the throwing. The only rules are that the pumpkin must weigh between 8 and 10 lbs (3.6 - 4.4 kg), no explosives are allowed and the pumpkin must leave the device intact.  The rest is up to your imagination.  Apparently it is bad form to admit that you spent substantial effort or money on your machine.  A few years ago, the favoured design was to hold the pumpkin in "bucket" on the end of a spinning arm and the bucket would open to allow the pumpkin to fly out.  Last year a canon powered by compressed air won by a large margin.  This year, an improved air canon won with a distance of 2655ft (810m)!  The reporter said that the pumpkin left the barrel so quickly that it could not be seen but way off in the distance there was a black dot arcing through the sky.  Some years ago a church about half a mile away put a big target on its roof as a joke but it is now coming in to range!  A crowd of 20 000 came to watch.</p>
   <p>It seems that every American has seen <i>Crocodile Dundee</i> so Paul Hogan is now advertising the Subaru (Japanese) Outback. Paul and friend are being chased by someone in a Chevrolet (Americans don't need to know that "Chevys" are not sold in Australia).  You can guess who wins.  There have also some amusing billboard ads for Fosters beer.  In my favourite one, the left half shows a battered old Land Rover with the caption <i>"Australian for limo"</i>. The right half of the poster shows a close-up of the Fosters beer can with the words <i>"Australian for beer"</i>.  Incidentally, I've seen an ad for a CD-ROM called "The Beer Hunter".</p>
   <p>One thing I really like here is that there are very few dogs.  It hit me when I heard a dog barking late at night a few weeks ago, that it was the first time I had heard a barking dog since leaving Australia.  Barking dogs were a nuisance at Turramurra and at times unbearable in Auburn.  Also, you never see dogs running around loose to harass passers by (or foul the footpaths).  This may be because of the disease rabies - dogs without owners are presumed to be a public health problem and perhaps the dog catchers take them away. I have seen a few dogs (on a leash) taking their owners for a walk but only a few.</p>
   <p>Anyway, have a great Christmas and New Year.</p>
   <p class="endText">- Peter</p>
</div>

<div class="story">
   <p><span class="next">Next: <a href="<?= $rootRelativeUrl ?>letters/letter4d">Lan&rsquo;s letter</a> (page 4) <span><br>
	Previous: <a class="previousPage" href="<?= $rootRelativeUrl ?>letters/letter4b">News in America</a></p>
</div>
