<? //dsp_letter13a.php ?>

<div class="story">
   <p>Dear everyone,</p>
   <p>It is now a full year since our last letter and so we have a lot to tell you but most of our news is only a month or two old.</p>
   <p class="endText">This letter is our first intended for online delivery.  It is quicker and cheaper for us, it will get to you sooner than one in the mail, plus you get hyperlinks and more photos, in color, than I can provide in the printed version.</p>
</div>

<h2>Activity report</h2>
<div class="story">
   <p>The US Immigration Service has effectively determined what we haveand have notdone this year.  Since Lan is still waiting to get a "green card" (permanent resident status) through her employer, she is committed to stay there until everything is finalized.  We thought it would be over by now but it seems we must wait until the end of 2000.  She works for US WEST Dex, a section of the local phone company and while there has not been much news there, she has recently transferred to a different group and moved to a cubicle 2 rows away from the old one.  More importantly, she is now a DBA (database administrator) instead of just a database designer.</p>
   <p>As I indicated last year, the Immigration Service would not let me work during 1999, so I decided to study computers instead.  By taking a heavy course load and getting a few credits for my engineering degree, I very nearly finished a 2-year course on Internet development in 1 year.  I am annoyed that my engineering career never went very far and I feel a bit of a loser having to take an entry-level job at 35 but the industry is booming and the prospects for rapid advancement are good.</p>
   <p>Best of all, I already have a job!  One of the guys from my previous job here in Denver helped me get an interview for what I believe was an unadvertised position and my boss offered me the job on the spot!  I am very lucky.  It is a "dream job" since I'll be working with Visual C++, Java and Cold Fusion.  Someone like me without a full degree might expect to get stuck in a big company doing tedious maintenance work but this is a small company, so I'll get to do a bit of everything. Premier Data Systems does mapping software for oil and gas companies and the government. My second week was demoralizing as I battled with my first real task but I found out that my boss expected me to struggle.  Amazingly, when the currencies are converted, my entry-level job here pays the about same as my last engineering job in Australia, to which I brought a decade of experience.</p>
   <p>Those of you who have read our earlier letters will know I've often been misunderstood when giving my name.  Somehow, <i>Peter</i> becomes <i>Pleaser</i>, <i>Plato</i>, <i>Pleter</i> and so on.  I was thinking that if I started a new job with people I didn't know, I would save myself the trouble and be Andrew instead but since I know Steve from my previous job, I've stuck with being me.</p>
   <p>Most American 17-year-olds have a better car than ours but our little <a href="<?=$rootRelativeUrl ?>imagemgt/index.php?fuseAction=showPhotoAndCaption&photoName=Hyundai2.jpg">Hyundai</a> has served us well, recently passing 100,000 miles (160,000 km).  Right now though it has a rough idle and taking it to the dealer only made it worse.  We expected that we would need to buy a second car so I could get to work and to provide more room and comfort (i.e. air conditioner) for travel, particularly when we have visitors.  However, I can catch the bus to my new job, so we can put off that decision a little longer.</p>
   <p>While I was looking for <i>Visual C++ for Dummies</i> on the library shelf, I stumbled across a fascinating book that I'm working my way through now.  It is actually a book about other books.  It&rsquo;s <a href="<?=$rootRelativeUrl ?>artsandculture/index.php?fuseAction=readingPlan">The New Lifetime Reading Plan</a> and it gives the authors' opinions of all the books we should read some time in our life, not necessarily for pleasure but to be a fuller human being.  I've read a few of them but that was because I was forced to at school.  I'll probably never read most of the rest but it great to know a little about each and why they are considered important.  There are even a few that I'm inspired to attempt.</p>
   <p>I was disappointed that we didn't elect to toss out the Queen in time for Australia&rsquo;s Centenary.  It seems absurd to me that our head of government is unelected, is not a citizen and doesn't even live in the country.  Having seen the circus that accompanies American Presidential elections, I favored the proposed model of a President chosen by a 2/3 majority of Parliament.  However, I can also understand people&rsquo;s reluctance to accept it.  I'm sure we will get to vote again within a few years.</p>
   <p>Our neighbors across the corridor gave us a wonderful and unexpected Christmas present&mdash;they moved out!  Without going into details, they made life very tense and we considered moving. Lan looked at perhaps 20 houses but I wanted to postpone buying until after I got a job so we could choose a convenient area.  Now that issue has gone, we just need to worry about the building falling apart.</p>
   <p class="endText">We ended the year with a big splash.  Putting aside any Y2K concerns, we saw Neil Diamond at a New Year&rsquo;s Eve concert.  I have never seen anyone so famous, the nearest being Midnight Oil at the Horden Pavilion, so it was quite an experience!  Unfortunately, it was held in a sports arena rather than a concert hallthe basketball and ice hockey players were gone but the lousy acoustics remained.  There was absolutely no stereo effect, so it was like listening to the TV turned up loud.</p>
</div>
<?
setThumbnail("AcrobatIcon_Ltr13.gif", $rootRelativeUrl . "letters/files/Letter13.pdf");
?>

<div class="story">
   <p>Next: <a class="next" href="index.php?fuseAction=letter13b">Travels, part 1</a></p>
 </div>
