<?php //dsp_letter5c.php ?>

<h2>Election and American politics</h2>
<div class="clearfix">
	<div class="story followOn">
		<p>Although not able to vote, I&apos;ve never been as emotionally involved in an election as I was for last year&apos;s US election. Same for Lan. Along with almost half of America, it seemed utterly obvious that the President was incompetent and his Administration wrong on almost every issue. However, the other half of America held the opposite view just as passionately. </p>
		<p><a name="Note2Ref"></a>While I believe it is <i>probably</i> true that Mr. Bush got more votes where it counted <sup><a href="#Note2">Note&nbsp;2</a></sup>, I am still angry at some of the tactics employed, or attempted, by the Republicans. A few are worth mentioning here:</p>
		<ul>
			<li><a name="Note3Ref"></a>During the lead up to war and then during the election campaign, the President and other members of the Administration constantly used &quot;Iraq&quot; and &quot;terrorist attacks&quot; in the same sentence and spoke of Iraq as part of the &quot;war on terror&quot;. Without ever actually saying it, they created an impression that Iraq was directly involved in the attacks on New York and Washington. In 2003, nearly 70% believed it <sup><a href="#Note3">Note&nbsp;3</a></sup>. As we know and as the President has admitted, there was no such link.</li>
			<li><i>The Plain Dealer</i>, a newspaper in Cleveland, a city that is heavily Democratic, printed voter registration forms in the paper as a service to its readers. However, Ken Blackwell, the Ohio Secretary of State and a Republican rejected the many thousands that arrived because the paper was &quot;too thin&quot;! This was later overturned but it is likely that some applicants didn&apos;t hear about the reversal and didn&apos;t vote.</li>
			<li>Two weeks before the election, Republicans attempted to have 63 polling stations in Philadelphia moved in an apparent attempt to confuse voters. 53 were in areas with largely African-American or Hispanic (Spanish-speaking) populations that traditionally vote Democrat. The city rejected the application.</li>
			<li>In Nevada, the civic-sounding but Republican-funded <i>Voters Outreach of America</i> discarded the voter registration forms of those indicating that they wanted to be noted as Democrats (allowing them to vote in the pre-election elections that select the candidates). They got away with it.</li>
			<li>In Florida, where the President&apos;s brother just happens to be Governor, the state sent a list of 47,000 felons to the counties to ensure that they were removed from voter rolls. However, as an investigation by the <i>Miami Herald</i> soon discovered, 2100 of those had won back their right to vote. Remember that the 2000 election was decided by just 537 Florida votes. Even worse, the <i>Sarasota Herald Tribune</i> reported that there were just 61 Hispanic names on the list in a state where 17% identify themselves this way. (Florida Hispanics are largely Cuban and vote Republican overwhelmingly.) The state&apos;s defense of the list became untenable and they eventually relented allowing the counties to make their own judgements.</li>
			<li><a name="Note4Ref"></a><i>&quot;Those who vote decide nothing; those who COUNT the votes decide everything.&quot;</i> Although attributed to Stalin, there is scant evidence that he actually said it but it sounds plausible. Anyway, the CEO of Diebold, a large maker of electronic voting machines, wrote that his company was <i>&quot;helping Ohio deliver its electoral votes to the President&quot;</i>.  Some 40 million voters used electronic voting machines in this election and only a minority of machines left a physical paper trail available for independent audit. Was their fraud? We don&apos;t know and we can&apos;t know. However, even assuming Diebold was completely honest, it has been demonstrated that the tabulators can be hacked to change the &quot;results&quot; <sup><a href="#Note4">Note&nbsp;4</a></sup>.</li>
		</ul>
		<p>I must also report that there were irregularities on the Democrat side. Probably the most famous was someone being paid in illegal drugs to get Democrats to register. However, from what I&apos;ve read, these problems are utterly insignificant compared with actions by the other side.</p>
	</div>
</div>

<div class="clearfix">
	<div class="story">
		<p>Having said all this, what really gave Mr. Bush the edge was his political advisor Karl Rove. His strategy was not to united by winning over undecided voters in the middle but to &quot;energize the base&quot; and it is widely believed, to use third parties to ruthlessly smear the opponent.</p>
		<p>Dealing with the second one first, in this last election, I&apos;m referring to the so-called <i>Swift Boat Veterans for Truth</i> that ran TV ads casting doubt on John Kerry&apos;s record in Vietnam. Although some of the claims were contradicted by what they themselves had written at the time and John&quot;s crew mates who saw what happened stood by him, some of the mud stuck. I find it incredible a large segment of the American public was so willing to believe this and yet be completely unconcerned that Mr. Bush avoided going to Vietnam because his father used his influence to secure a position in the Texas Air National Guard. Even then, he failed to show up for duty for several months.</p>
		<p>Similar tactics were used against John McCain in the Republican primaries in 2000. As you probably know, John was a prisoner of war in Vietnam for 5&frac12; years. The communists offered to release him when they discovered that his father was an Admiral but he refused unless all the POWs were released. That&apos;s character.</p>
		<p>Unlike Australia where voter turnout is near universal because it is required by law, in America, not only do you have to convince voters that your positions are right but you have to convince them <i>enough</i> to get them to vote. Karl Rove reckoned that 4 million &quot;evangelical Christians&quot; didn&apos;t vote in 2000 so he aimed to engage them with &quot;Christian values&quot;&mdash;and change the subject from Iraq, loss of jobs, exploding government deficits and so on. I thought what they were promoting was a perversion of Christian values, or at least a self-serving subset.</p>
		<p>I heard an interesting analysis that argued that in the last generation or so, Christian values have been turned from <i>external</i> issues (fighting against poverty, racism, violence against women, environmental degradation, torture and war combined with fighting for peace, jobs, access to healthcare, education) to <i>internal</i> issues focused particularly on abortion and same-sex marriage.</p>
		<p><a name="Note5Ref"></a>I&apos;m uneasy about abortion but see the real solution is preventing unwanted pregnancies. The &quot;pro-lifers&quot; would do well to ask why the US has such high rates of teen pregnancies&mdash;more than double that of Canada for instance and 16 times higher than Japan <sup><a href="#Note5">Note&nbsp;5</a></sup>. Their opposition to sex education and contraception might be part of the problem rather than part of the solution.</p>
		<p>The hypocrisy on the same-sex marriage issue is jarring. The President has given his support to a Constitutional amendment that would define marriage in terms of one man and one woman and 38 states have passed &quot;defense of marriage acts&quot; that define it this way. The Republicans talk about marriage and family as being the foundation of society and say that same-sex marriage is a threat. Somehow divorce is never mentioned even though 40-50% of US marriages now end that way. While condemning homosexuals, the President was strangely silent when Britney Spears was married and then divorced 55 hours later. If lack of children is the problem, it is odd that Republicans don&apos;t criticize couples like Lan and I.</p>
		<p><a name="Note6Ref"></a>I am forced to conclude that these issues are merely politics; a way to get popularly elected while doing what they really want &ndash; massive tax cuts and rollback of regulations for their wealthy donors. I urge you to read this article <sup><a href="#Note6">Note&nbsp;6</a></sup> about the growing wealth inequality: <i>&quot;... between 1973 and 2000 the average real income of the bottom 90 percent of American taxpayers actually fell by 7 percent. Meanwhile, the income of the top 1 percent rose by 148 percent, the income of the top 0.1 percent rose by 343 percent and the income of the top 0.01 percent rose 599 percent.&quot;</i> It gets worse after that.</p>
		<p>To my mind, a government that truly reflected Christian values would look like a combination of <a class="external" href="http://www.greenpeace.org" target="_blank">GreenPeace</a>, <a class="external" href="http://www.amnesty.org/" target="_blank">Amnesty International</a>, <a class="external" href="http://www.care.org/" target="_blank">CARE</a> and <a class="external" href="http://www.doctorswithoutborders.org/" target="_blank">Doctors without Borders</a>.</p>
		<p><a name="Note7Ref"></a>Although there were some cheap shots at the President, the film <i>Fahrenheit 9/11</i> moved me when looking at who makes the decisions about the war and who fights it. Only a few members of Congress have close relatives serving in the military <sup><a href="#Note7">Note&nbsp;7</a></sup>. The film followed a pair of Marine recruiters who focused on the poorest neighborhoods knowing that the residents there had few other opportunities for education and employment. </p>
		<p><i>&quot;We don&apos;t do body counts&quot;</i>&mdash;General Tommy Franks. The Administration does not discuss the human cost of the war for the Iraqi population. Strange given that the President considers the sanctity of life so important that he flew back from Texas to sign legislation at 1AM to save the &quot;life&quot; of Terri Schiavo who, as you probably know, had been severely brain-damaged for 15 years. Since there were no WMD or links to <i>al Qaeda</i>, the overthrow of a dictator allowing &quot;freedom&quot; and &quot;democracy&quot; is about all they have left to justify the war but that would sound hollow if the death toll was widely appreciated. Sadly, there are no plans to overthrow other brutal dictators such as Robert Mugabe but then Zimbabwe has no oil.</p>
		<p class="endText"><a name="Note8Ref"></a>For the record, as of today, there are at least 17,316 reported civilian casualties <sup><a href="#Note8">Note&nbsp;8</a></sup>&mdash;more than five times the number killed on 11th September 2001. A report in <i>The Lancet</i> <sup><a href="#Note9">Note&nbsp;9</a></sup> estimated the toll to be 98,000 within a wide range. It included Iraqi army personnel (mainly unwilling conscripts) killed during the invasion as well as civilians and extrapolated from samples.</p>
	</div>
	<div class="photo-gallery">
		<?php
		setThumbnail(["debateBulge1.jpg", "electionMap1.jpg"]);
		?>
	</div>
</div>

<div class="story">
   <p>Next: <a class="next" href="<?= $rootRelativeUrl ?>letters/letter17d">Miscellaneous</a><br>
   Previous: <a class="previousPage" href="<?= $rootRelativeUrl ?>letters/letter17b">Washington D.C.</a></p>
</div>

<div class="story footnotes">
   <p>Notes:</p>
   <ol class="endText" start="2">
		<li><a name="Note2"></a>There was a significant discrepancy between exit polls that had Kerry win by 3% rather than the actual results which had Bush up by 2.5%. The group that conducted the polls, Edison Media Research and Mitofsky International, theorize that more Democrats were willing to talk to their data collectors as they left the polls, though they admit that the difference between observed and recorded results is unprecedented: <a class="external" href="http://exit-poll.net/election-night/EvaluationJan192005.pdf" target="_blank">Evaluation of Edison/Mitofsky Election System 2004</a>. However, a group of academics reviewing the same data believes that the statistical chance of this happening is no better than 1 in 240 and concluding &quot;<i>No matter how one calculates
it, the discrepancy cannot be attributed to chance</i>.&quot;  <a class="external" href="http://uscountvotes.org/ucvAnalysis/US/Exit_Polls_2004_Edison-Mitofsky.pdf" target="_blank">Analysis of the 2004 Presidential Election
Exit Poll Discrepancies</a>. <br><a href="#Note2Ref" class="noteGoBack">Go back</a></li>
		<li><a name="Note3"></a>From The Washington Post, <a class="external" href="http://www.washingtonpost.com/ac2/wp-dyn?pagename=article&amp;contentId=A32862-2003Sep5" target="_blank">Hussein Link to 9/11 Lingers in Many Minds</a>. <br><a href="#Note3Ref" class="noteGoBack">Go back</a></li>
   	<li><a name="Note4"></a>See <a class="external" href="http://www.blackboxvoting.org/" target="_blank">Black Box Voting</a>. Also, Diebold is not the only company making voting machines with ties to the Republican party as <a class="external" href="http://www.motherjones.com/commentary/columns/2004/03/03_200.html" target="_blank">Mother Jones</a> explains. <br><a href="#Note4Ref" class="noteGoBack">Go back</a></li>
     	<li><a name="Note5"></a>From the Population Resource Center, <a class="external" href="http://www.prcdc.org/summaries/teenpreg/teenpreg.html" target="_blank">Adolescent Pregnancy and Childbearing in the U.S.</a> <br><a href="#Note5Ref" class="noteGoBack">Go back</a></li>
	   <li><a name="Note6"></a>From ZMag quoting Business Week, <a class="external" href="http://www.zmag.org/content/showarticle.cfm?SectionID=10&amp;ItemID=4728" target="_blank">The Death of Horatio Alger</a>. (Horatio Alger, to quote <a class="external" href="www.wikipedia.org" target="_blank">Wikipedia</a>, was an author who <i>&quot;wrote over 130 dime novels, describing how down-and-out boys were able to achieve the American dream of wealth and success through hard work, courage, determination, and concern for others&quot;</i>.) <br><a href="#Note6Ref" class="noteGoBack">Go back</a></li>
		<li><a name="Note7"></a>From Footnote Fahrenheit, <a class="external" href="http://www.newsaic.com/f911chap7-8.html" target="_blank">Members of Congress with children in Iraq</a>. <br><a href="#Note7Ref" class="noteGoBack">Go back</a></li>
		<li><a name="Note8"></a>From <a class="external" href="http://www.iraqbodycount.net/" target="_blank">IraqBodyCount.net</a>. <br><a href="#Note8Ref" class="noteGoBack">Go back</a></li>
		<li><a name="Note9"></a>To save you creating an account with The Lancet:, <a href="files/LancetIraqReport.pdf" target="_blank">Mortality before and after the 2003 invasion of Iraq: cluster sample survey</a> (PDF, 262 kb). <br><a href="#Note9Ref" class="noteGoBack">Go back</a></li>
	</ol>
</div>
