<? //dsp_letter7b.php ?>

<h3>Alaska holiday</h3>

<div class="story">
   <p>We took a holiday for the first two weeks of September starting in Seattle, flying to Anchorage Alaska, joining a ship to come south to Vancouver and then spending a few days there.</p>
   <p>Seattle reminded us both of Sydney and Lan liked it so much that she wanted to move there!  It is a city on the water and it has history and older buildings which suburban Denver mainly lacks.  The climate in the &quot;Pacific northwest&quot; is mild and wet and we were surprised to find gardens in full bloom in autumn.  You may be aware that Seattle has a reputation for rain and we saw a T-shirt that supposedly advertised the <i>Seattle Rain Festival:  January 1 &ndash; December 31</i>!</p>
   <p>Perhaps the highlight of the Seattle area was the Boeing factory where 747s, 767s and the new 777s are built.  When I see 747s at the airport, I am always impressed at how enormous they are.  When many of them are inside a building at various stages of construction, they don't look so big any more.  I think my brain had trouble comprehending just how huge the building is and mentally scaled down the aeroplanes accordingly.</p>
   <p>We had less than two days in Alaska itself and it was unseasonably warm and clear.  We drove north from Anchorage to see Mt. McKinley which at 20,320 ft or 6193 m is the tallest mountain in north America and almost 3 times as tall as Kosciusko (and 40% taller than Colorado&rsquo;s highest).  It was big &amp; white.</p>
   <p>Salmon populate the coast from Alaska at least as far south as Seattle.  These remarkable fish hatch in the rivers, float out to sea and swim around for 5 years before returning to the same river where they came from.  Their body changes shape and colour and then they battle against the current and leaping rapids to get to the same spot they hatched.  After spawning, the fish swim gently over the spot where the eggs are laid until they die.  There are several species and they come ashore at different times.  We were there after one species had spawned so we missed the battle upstream.  At one town we visited on the ship where there were so many it seemed you could walk across on their backs!</p>
   <p>The cruise was the main reason we went &ndash; the scenery was great, we ate too much good food and the ship&rsquo;s crew were very friendly.  The only disappointment was the other passengers who were almost all a lot older than us.  There is nothing wrong with older folks but 1600 of them and a very few under 50 made us feel a bit lost.  To make matters worse, we had fixed seating arrangements at dinner and we were assigned to a table of just 4 with a grandmother and her mother!  The only young people we spoke to were crew members.  I approached one couple and said how nice it was to see another couple under 50 years old and found that they were two off-duty photographers.  One was English and one from New Zealand and we spoke to them several more times during the cruise.</p>
   <p>Back to the scenery, Alaska has lots of glaciers and many of them come all the way down to the sea.  I thought that glaciers were relics from the last ice age.  This is true of some but most exist as a result of the huge snowfalls that fell at the top of the mountain and then fail to melt during the short summer.  As snow accumulates over the years, the layers at the bottom get compressed and the air is squeezed out to form ice.  The ice will flow like a huge slow river if has somewhere to go.  I recall that one of the glaciers we saw was moving downhill at about 2 meters per day and melting at just a little more, so the front of the glacier retreated a meter or so each year.  Apparently this is normal-most glaciers around the world are retreating and the retreat is accelerating with global warming but a few glaciers are advancing where local weather conditions have produced more snow to overcome the additional melting.  A few centimeters per day does not sound much but over decades, the retreat adds up.  One of the bays we sailed into was completely filled with ice when explorers first came past 200 years ago.</p>
   <p>Ships arriving nearly simultaneously in Seattle and San Franscisco, each with 2 tonnes of gold, caused a sensation and triggered a stampede of people into Alaska and Canada&rsquo;s Yukon Territory in 1898.  Most entered through Skagway (where we stopped) and climbed over Whitehouse Pass, or at nearby Dyea to Chilkoot Pass shown here during winter. Following a near-famine the previous winter, the Royal Canadian Mounted Police required that every miner bring a full year of provisions which meant about 40 trips over the pass.  Once all their gear was checked, they and their companions spent the winter building a boat to get across a lake and then down hundreds of km of often treacherous river.  The Canadian police check each boat to ensure it was safe.  The day the ice broke in March of 1898, 6000 boats set sail.  The gold fields were so far north that the ground is frozen so miners digging pits or shafts had to light fires to melt the dirt before it could be scooped out.  The Canadian police earned enormous respect from the miners for keeping law and order.  Dawson City was the center of the gold rush and during the boom there was no murder or significant gold theft.  Skagway and Dyea on the American side were run by con-men.</p>
   <p>We did see some humpback whales and I found it reassuring that these magnificent animals have made something of a comeback since being nearly exterminated earlier this century.  Humpbacks are big at up to 20 m and 60 tonnes but nowhere near as the blue whale which can be 50 m long and 200 tonnes.  The blue whales apparently congregate off California each year so maybe we will see them one day.</p>
   <p>The ship&rsquo;s <i>Cruise Director</i> is in charge of passenger entertainment and the man on our cruise (Peter) had an outstanding sense of humour and an ability to make us feel excited.  He probably tells the same jokes on every cruise but they sound as though they are new.</p>
   <p>For example, commenting how some people were staying all day in the best seats in the viewing areas, he said, <i>&quot;I overheard two ladies talking today and one said, &rsquo;I have been sitting in this chair so long that my bottom has gone to sleep&rsquo; and the other said, &rsquo;Yes I know &ndash; I heard it snoring&rsquo;&quot;</i>!  Bearing in mind that September is autumn and you need a coat and preferably gloves to go outside, he said, <i>"The captain told me the weather forecast for tomorrow and you won't believe it . It&rsquo;s going to be 85&deg; (Fahrenheit, about 33&deg;C): 40 in the morning and 45 in the afternoon!"</i></p>
   <p>There was also a 45 minute video on the internal TV channel explaining procedures to disembark.  Although the subject is inherently boring, after the first 2 minutes you wanted to watch it.  When explaining to Americans (who made up most of the passengers) how the Canadian customs work with Green and Red gates (like Australia), he said with a completely straight face <i>&quot;if you have nothing to declare, go to the green side;  if you've bought too much Scotch, or are carrying weapons, explosives or narcotics, you will have to go to the Red gate and declare it.&quot;</i></p>
   <p class="endText">When we arrived in Vancouver, we picked up a rental car and headed for Victoria which has a reputation for being more English than England.  We didn't see any cricket matches but we did see some fine buildings and some gardens that impressed even me.  When we made it back to Vancouver, Lan changed her mind on wanting to move to Seattle as she thinks Vancouver is better still.  It has a huge Chinatown.  Many Hong Kong Chinese have arrived in the city over the last decade because of the uncertainty over the Chinese handover next year.</p>
</div>
<?
setThumbnail("SpaceNeedle1.jpg");
setThumbnail("Cabbages1.jpg");
setThumbnail("RegalPrincess1.jpg");
setThumbnail("UnEnteringShip1.jpg");
setThumbnail("UsAtDinner1.jpg");
setThumbnail("LanGlacier1.jpg");
setThumbnail("PeterGlacier1.jpg");
setThumbnail("ChilkootPass1.jpg");
setThumbnail("SnowTrain1.jpg");
setThumbnail("VictoriaBC1.jpg");
setThumbnail("ButchardGardens1.jpg");
setThumbnail("LanAtBGardens1.jpg");
setThumbnail("TotemPole1.jpg");
setThumbnail("SuspensionBridge1.jpg");
?>

<div class="story">
   <p>Go back to <a href="index.php?fuseAction=letter7a">News</a> (page 1)</p>
   <p class="endText">Continue to <a href="index.php?fuseAction=letter7c">Life in America</a> (page 3) <a href="index.php?fuseAction=letter7c"><img src="<?= $continueIconSrc ?>" height="13" border="0" style="vertical-align:bottom"></a></p>
</div>
