<? //dsp_letter4b.php ?>

<h2>News in America (or the lack of it)</h2>
<div class="story">
   <p>As you can imagine, there was a lot about OJ Simpson in the media. In Newsweek after the verdict was given, there was a quote from the producer of one of the TV talk shows: <i>&quot;If we had God booked and OJ was available, we'd move God&quot;</i>.  It has surprised me and apparently most white Americans how the black and white communities saw the trial so differently.  I heard something on the radio that one third of young black men are in prison, on parole or on good behaviour bonds.</p>
   <p>TV has taken a turn for the worse. First, the <i>Cosby Show</i> ended then <i>The John Laraquette Show</i> (is this on in Australia?) moved to a channel that we can't get and now the Public Broadcasting Service has dropped the English ITN news.</p>
   <p>Although PBS has let us down with the news, they still show some excellent documentaries. We saw one on President Franklin Roosevelt (FDR) which highlighted how he coped with polio which prevented him from walking.  At the time, very few Americans knew of his disability.  Also, there was a program about Bob Hope who, as you probably know, entertained American troops during WWII and the wars in Korea and Vietnam.  In a full hour of laughs, the one that has stayed in my mind is <i>&quot;we have to let the Nazis know that Crimea doesn&rsquo;t pay&quot;</i>.</p>
   <p>PBS is hopelessly underfunded by the standards of the rest of the developed world. PBS TV gets just 15% of its funding from the government and National Public Radio gets just 12%.  The rest is made up with sponsorship by businesses (their name gets mentioned; there are no ads) and subscriptions by listeners.  PBS TV gets just 80&cent;/year/American compared with 8&cent;/day/Australian that I recall the ABC gets. It should be a national embarrassment but some Republicans are trying to take away even that. PBS can be off-air for days at a time if they have equipment failure. Full marks though for battling on. There are 2 channels so I'm surprised they don&rsquo;t have just one given the limited resources.</p>
   <p>The French testing of nuclear weapons is a non-issue over here. I suspect most Americans are vague on where France is, much less where Muraroa Atoll is.  As far as I&rsquo;m aware, the commercial media has not even mentioned it.  It was a significant issue in the English news.  There was even a segment about a car trying to drive into the French embassy in Canberra with a stuffed kangaroo and a mock nuclear bomb on top.</p>
   <p>Politics is very interesting here though I&rsquo;m struggling to understand how government is supposed to work.  I'm not the only one.  A recent survey found that 49% think country is controlled by lobbyists, 25% by Congress and a mere 6% by the President!  Actually, for 6 days, the government didn't work at all.  The President and Congress couldn't agree on a temporary budget and the Federal government ran out of money. Hundreds of thousands of &quot;non-essential&quot; staff were sent home, offices were closed and government contracts were suspended. The situation appeared to be similar to when Mr Whitlam&rsquo;s government was brought down after Mr Fraser &quot;blocked supply&quot; so the government had no money to operate. Everyone here seemed to just accept the shutdown and made arrangements to work around it. A temporary measure has now been agreed to but the real fight over the budget is still ahead. Unlike Australia, where the government &quot;hands down&quot; the budget (Independent Green senators notwithstanding), it appears that the American way is that Congress and the Senate have to agree on a budget, then President has to sign it to make it law. If they have different agendas, paralysis can occur. The Republicans now control the Congress and Senate and have promised to balance the budget, have passed sweeping cuts in welfare and health programs (and even agricultural subsidies which is of interest to Australian farmers) and there is a large tax cut. So far it is all political theatre; Democrat Bill Clinton has said he will veto it.</p>
   <p>Sadly, voting is not compulsory here so politicianpitch their message more and more at actual voters, not the general population of potential voters.  Thus Medicare, the health program for the elderly has been trimmed much less than welfare and Medicaid, the health program for the poor.  As one congressman explained political reality, <i>&quot;Old folds vote, kids don&rsquo;t&quot;</i>.</p>
   <p>General Colin Powell decided not to run for President in next year&rsquo;s election which is a pity as I think he would have brought the Republicans back to the mainstream.  There are now about 10 Republicans hoping to challenge Mr Clinton in the election which is still a year away and none are very inspiring and some are frightening.  Abortion is a hot and divisive issue and every potential office-holder for a higher government position has to state if they are &quot;pro-choice&quot; or &quot;pro-life&quot;. All the Republicans are &quot;pro-life&quot; with some taking the extreme position of wanting to outlaw it even in cases of rape and incest. Such is the power of the &quot;religious right&quot;.</p>
   <p>As you are probably aware, most Americans regard Abraham Lincoln (1861-65) as one of their great presidents.  It is a surprise then to find that there is some evidence that he was gay.  The evidence for his predecessor, James Buchanan is even stronger.</p>
   <p>New York has started to fight crime with "broken window theory" and the results have been very encouraging.  The analogy is that if a house has a single broken window that is not fixed, the other windows will soon be broken too and very soon, the whole house will be dilapidated.  There seems to be a link between petty crime (like people jumping over the railway ticket barriers and graffiti) and more serious crimes like murder and armed assault. Murders in the Big Apple have fallen by 32% in the last year (as I recall).</p>
   <p class="endText">The more I know about the American health care system, the more I realise how good Medicare is, despite its faults.  An American&rsquo;s health insurance is normally provided by his or her employer (which is obviously a problem if you are unemployed).  To cut costs many employers are moving their staff into health management organisations (HMOs) which run their own hospitals and you have to see their doctors.  However, they may also achieve economies by denying care. Women who have a baby without apparent complications can now stay in the hospital for only 24 hours at the insurance company&rsquo;s expense. In response to public outrage, a few states have now passed laws that say the HMO must pay for 48. With some HMOs, the doctor is given a set amount each month for each patient in their care but that amount has to include things like the cost of tests that the doctor prescribes. Order too many tests and the doctor loses. Similarly, if a doctor refers the patient to a specialist, the expenses billed to the HMO are counted against the doctor and their contract may not be renewed. Also, the contract between the doctor and the HMO may prohibit the doctor saying anything negative about the HMO to either a patient or a government authority. I'm surprised it is legal.</p>
</div>

<div class="story">
    <p>Next: <a class="next" href="index.php\?fuseAction=letter4c">Strange and curious things</a><br>
	Previous: <a class="previousPage" href="index.php?fuseAction=letter4a">Our news</a></p>
</div>
