<? //dsp_letter1.php ?>

<div class="story followOn">
   <p>20th March 1995</p>
   <p>Dear .......................................... ,</p>
</div>
<div><!-- Keep images from floating above this 'story'. -->
   <div class="story">
      <p>Sorry to have to send you a standard letter.  We want to say so much to so many people it is impractical to do otherwise.  Anyway, let me bring you up to date with what has happened since we left Australia and some impressions on our new home.</p>
      <p>We are still in Detroit, Michigan, the home of the American car industry.  Lan&rsquo;s new employer (CBSI) has its headquarters in suburb that is the very rough equivalent of say Pennant Hills.  Their office block is a long way from the centre of town and is on a major road.  Detroit doesn't appear to have regional commercial centres like Parramatta or Chatswood.  We are camped in a motel nearby.  I thought that we were headed for a project in Cedar Rapids in Iowa and then it was to be Columbus, Ohio.  That is no longer true, if it ever was.  CBSI is less organised than we had expected and we are now not sure where or when we are going.  The current guess is Washington D.C. (where Bill lives) in about a week.  Denver, Colorado was also being talked about but who knows.  Both cities get overall high marks in the <i>Places Rated</i> book I read.  Lan is spending her days at work on a temporary assignment &ndash; from what I understand, it is the start of a telephone billing system. Her shoulder is OK but only OK.  I have been spending most of my time in the adjacent library, where they have a few computers so that I can write this letter.</p>
      <p>Before I left, I may have given some people the impression that I don't like America.  That&rsquo;s not true.  There is much to admire in America - it&rsquo;s just Americans I don&rsquo;t like.  Indeed, I was disgusted by what happened over the weekend.  The hotel was temporary home to about 30 white, middle-class families who came for a sports competition.  Friday night was mildly unpleasant but on Saturday, they went wild.  Kids were running up and down the corridors, yelling and screaming while their parents sat around and ignored them.  I rang the front desk at 11 pm to complain but it seemed to make no difference.  I&rsquo;m not sure if the were unwilling or unable to calm them down.  I managed to get to sleep but woke again at 1.45 am with some kid down the hall shouting &quot;yee-hoo&quot; every 20 seconds or so (mixed in with loud conversation and laughter).  Then at 1.50, it suddenly went quiet.  I don't know why.  I was appalled that they all had their parents there but the parents seemed to abdicate responsibility.  One good thing here is that streets are well sign-posted and business and houses have visible street numbers.</p>
      <p>I now understand better why Americans are generally LARGE.  For breakfast, the hotel serves juice, tea/coffee, donuts and sweet muffins. No bread, no fruit, no cereal.  I guess that&rsquo;s what customers like. Since the hotel room has no cooking facilities &ndash; we can&quot;t even boil water &ndash; we have had to manage with take-away (&quot;to go&quot; is the expression here) and restaurant food.  Most of it seems to be loaded with salt, sugar or fat (or all three).  We went to an Indian restaurant for 3 meals in two days when we discovered it.  We went again 2 days later and we'll go back tonight.  We had a revolting "meal" at the Tokyo Steakhouse and later noticed in the yellow pages that it had the cheek to describe itself as "one of the most beautiful restaurants in the world" (!).  Yuk!</p>
      <p>Lan has been trying to buy some nice clothes for work but with no success.  The Petite sections in stores carry sizes up to 12.  There is very little less than size 8 but Lan has found even size 2 is too big.</p>
      <p>No letter would be complete without a comment on the weather.  We have been very lucky.  There was a blizzard two weeks before we arrived but they had a lot of rain after that so nearly all of it melted.  In the week after we arrived, temperatures were around 22&deg;C which was about 20&deg;C higher than normal.  The last few days have been cooler at about 10&deg;C.  Since the winters are so cold, salt is spread on the roads which results in very rusted cars.  I've seen lots of 5-10 year old cars that would be unregisterable in NSW.  I'm not sure what all the salt does to the environment but I imagine it isn't good for it.</p>
      <p>On our first weekend we drove about 30 miles down Twelve Mile Road (an east-west road named for its distance north of the city) to see Lake St Clair.  The lake is not one of the &quot;great lakes&quot; but it is still too big to see the other side.  The surface freezes over in the winter and we saw perhaps 200 people on the ice fishing through holes.  On the way home we had great dinner at the Old Country Buffet (not Bob&rsquo;s Country Bunker).  Of perhaps 250 diners, there were about 10 whites, the rest were black.  Conversely, at church the next day, there were no blacks at all.  It seems that racial integration has been very poor.  On Saturday we visited Windor, Canada which is just over the river, like Albury-Wadonga.  One way, we drove through whole suburbs without seeing any white people at all.  I don't think we have anything in Australia to compare with the inner city decay we see here.  Windsor has a small Vietnamese community so we had a lunch we liked.  We went on to Amerstburg nearby which is of historic significance from the time when the British and Americans were fighting over where the US-Canadian border was (there was a war in 1812-1814).  The British co-operated extensively with the local indians, for a time to their mutual advantage.  The indians were trying to protect their lands from the Americans but they ended up losing it anyway.  It was interesting to hear that, since communication was so slow in those days, there was a big battle in New Orleans (on the Gulf of Mexico) one month after the war had ended. No-one knew.</p>
      <p>We had to open a bank account for Lan to be paid.  However, American banking is covered by state laws and banks can&rsquo;t operate freely outside their home state.  There are no national banks with branches everywhere.  As a result, when we move we'll have to open another account with another bank.  Apparently, this is a great improvement on what it used to be.  Banks were not allowed to operate more than 25 miles from base!  We have been given a plastic card for use with ATM machines.  We can only withdraw $60 a day.  If we are good, they will review that after 3 months and decide if we can take out $100 from our own account.</p>
      <p>There are 36 TV channels at the hotel.  Just 2 are worth watching - the &quot;Discovery Channel&quot; which runs documentaries and the &quot;College Cable Channel&quot; which runs educational programs.  I have yet to find any news program that acknowledges that important things happen outside the US, even some that don't involve Americans.  The only two off-shore stories I can recall were one about Al Gore and what he did for Bosnia and the other about US servicemen returning to Iowa Jima.  I saw the Iowa Jima story on 3 channels.  All said that about 6,000 Americans died but only one mentioned that the Japanese lost 21,000.  Last night we saw 3 programs about Australia on the Discovery channel - <i>Lizards of Oz</i>, <i>Wombats</i> and <i>The Big Wet</i>.  There was a Qantas ad too.</p>
      <p>We have been amazed at the cost of calling from public phones.  Calls to Australia are US$10.95 for the first 3 minutes and a call to the next area code (like calling Gosford from Sydney) is 80 cents for the first minute.  At least the told us first so we could choose not to.  Calls from home appear to be cheap though - one phone company was advertising 10 cents per minute to anywhere in the US.  All the phones take coins only - there appears to be no equivalent of a Telecom card, so long distance calls require handfuls of coins.  I have read that there are credit card phones but I have yet to see one.  At those prices, I don't want one.  Back to the subject of advertising, even the church weekly bulletin carries ads for local businesses.</p>
      <p class="endText">That&rsquo;s about all for the moment.  When we have an address, I&rsquo;ll let you know.</p>
	</div>
	<div class="photo-gallery">
		<?
		setThumbnail(["GeneralMotors1.jpg", "FarmingtonHills1.jpg", "LakeStClair1.jpg", "IceFishing1.jpg"]);
		?>
	</div>
</div>