<? //dsp_letter8a.php ?>

<div class="story">
   <p>10 May, 1997</p>
   <p class="endText">Dear ........................,</p>
</div>

<h2>News about us</h2>
<div class="story">
   <p>Another 5 months has come and gone since we last wrote.  Thank you to everyone who sent us a letter or card at Christmas.  As some of you discovered, our ex-landlord wrote <i>"return to sender"</i> on those that slipped past the post office which would have redirected them.  Our landlord knew our address, or could have found it easily if he had lost it-he just isn't a nice person.</p>
   <p>Our big news is that we are probably going to buy the unit that we are currently renting.  We were looking anyway and then our landlord called and offered this place at a good price.  By selling direct, he can afford to be generous as the real estate agent&rsquo;s fee would be 6% of the sale price, or almost double what is charged in Australia.  This unit has the three most important attributes in real estate (<i>location</i>, <i>location</i> and also <i>location</i>) but like most places we have seen, construction quality is lousy.  Virtually everything here is built of wood which needs repainting every 5-10 years and most dwellings have asphalt shingle roofs which must be replaced every 15 years.  Ours has a flat roof which is tarred and it will need refinishing within the next year or so.</p>
   <p>Our decision to buy real estate is partly the result of our immigrant status.  We have decided to stay at least as long as it takes to get a green card  which is like gaining permanent resident status.  This will allow us to compete equally with Americans for jobs and so we can come back and quickly get re-established if we wish  As you know, we are only able to work here on "temporary" worker visas.  To change jobs, the new employer must submit another visa application and not surprisingly, most can't be bothered.  Those that can are usually those hoping to exploit us.  Lan, with almost 10 years programming experience was offered a job with pay that students fresh from college would reject.  However, the US government obviously expects green card holders to stay and they may revoke the green card if they believe we have no serious intention of living in the US.  Therefore, to retain credibility, we have been encouraged to maintain our drivers' licences, keep a bank account and have a rental property we can come back to.</p>
   <p>The <i>normal</i> processing time to get a green card is close to 2 years.  This involves an employer proving that there is no US citizen willing and able to do the job that the green card applicant has.  The company has to advertise the position extensively, and show that no suitable candidates applied.  Right now, this is can be done as the US economy is very strong with unemployment down to 4.9%-the lowest since 1973.  Colorado&rsquo;s unemployment rate is even lower at 3.8%.  (Quite a contrast with the European Union where the average unemployment there now stands at 11.5% although Britain&rsquo;s unemployment is just 6.2%.  Mind you, if you have few skills, the American economy leaves you behind.  A lot of the jobs are at "minimum wage" which I think is now $5.15 per hour but no health care is provided.  At the very bottom, I see homeless people perhaps twice a week, compared with hardly ever in Australia.)</p>
   <p>It appears though that my company can avoid this <i>labor certification</i> process by showing that keeping me here is in the national interest.  The words <i>health care</i> rate highly when applying and my job involves designing equipment for the pharmaceutical industry.  If I go, equipment will not be designed, drug companies will be unable to do their research, thousands of people will die etc.  I thought this was a bit far fetched but a trombone player was able to show that it was in the nation&rsquo;s cultural interest for him to stay.  The main hold up now is that I need to get at least 3, and preferably 5, letters from our customers saying what a great guy I am and that they need me to stay.  This is difficult as I have had direct contact with the customer on only 3 projects and that has been only for the last few months.  Unfortunately, one project was for a Canadian company so that doesn't help and the other 2 are different parts of the same company.  I'm expecting it will take 6 months to get my letters and then we have to wait out the processing period for another few months.</p>
   <p>Therefore, it seems that we will not be coming home to live for a some time.  However, we are planning a trip home at Christmas with 2 weeks in Sydney and another week in Adelaide where Lan has family.  While some of the time will be for "business", like sorting out what we have in storage, there will be time to see people and do things.  I'm expecting we will have a big picnic somewhere so we can see as many as possible.  Details will be in future letters.</p>
   <p>While I still think of Sydney as "home", I confess that I like not being totally "settled".  I don't want to live in Denver forever but I am getting interested in London for a while, particularly since the election.  At one time, it looked as though Lan might get a job in Malaysia and that could be interesting.  We'll see.  I'd like to live in the developing world sometime but I realise that I have no ability to learn another language.  The 2 years since we arrived have gone quickly; we did not expect to stay as long as we have so I won't even try to predict what will happen over the next few years.</p>
   <p>My job can be boring at times; I am not doing much real engineering as our equipment is very low-tech.  I do get paid though and that makes it worthwhile.  As I mentioned in the last letter, the company effectively went bankrupt at the end of last year and the assets were bought by a French group which has an American base in a country town, 60 miles from Minneapolis (north, central USA).  We now have just an office and all the production is done up there.  It is a shame not to be working with the men (& they were all men) who actually built the product.  They often knew much more than we did-and they were never afraid to tell us!  Rumor has it that the "Christian" man who owned the old company tried to sell equipment and get a deposit after he knew the company would be sold.  That way, he could keep the deposit money and not have to deliver anything.  Scum!  Cheat!  The company has been very political as my boss tried to defend his privileged position by taking credit for things he didn't do and assigning blame for anything wrong.  We had nothing documented before and now we have a paperwork overload.  However, the CEO of the new company has just moved him out of engineering management which was the real problem but he did it so graciously that I barely noticed.  A new engineering manager will be hired so things are looking up.</p>
   <p>Lan has not had much luck with her employment.  She had to leave her last job as the work environment was impossible with people swearing and shouting at each other.  Some very highly paid people were allowed to get away with total incompetence, while the few like Lan who did their job were expected to perform miracles.  Lan is now having a nice rest and sending off rsums.  She has been doing a C++ and a Java course two evenings a week at a "community college" which is like the TAFE in Sydney and having no job has allowed her to catch up on her homework.</p>
   <p class="endText">I think we mentioned in an earlier letter that we had come to know one of the checkout ladies at the supermarket and her husband.  Knowing that we had no family here, they kindly invited us over to have lunch with them on Christmas day and we ate far too much.  Various friends of theirs dropped in during the afternoon so it was a very pleasant day.</p>
</div>

<div class="story">
   <p>Continue to <a href="index.php?fuseAction=letter8b">Trip to southwest corner</a> (page 2) <a href="index.php?fuseAction=letter8b"><img src="<?= $continueIconSrc ?>" height="13" border="0" style="vertical-align:bottom"></a></p>
   <p class="endText">Jump to <a href="index.php?fuseAction=letter8c">Life in America</a> (page 3)</p>
</div>
