<? //dsp_letter13b.php ?>

<h2>Travels</h2>
<div class="story">
	<p>In May, we had the pleasure of a visit by two of my cousins, Neville & Diana and since Neville is a geologist, we did a quick geological tour of Colorado.  Perhaps the highlight was seeing some tree stumps!  These are no ordinary tree stumps though.  About 15 million years ago, a volcanic eruption showered 15m of ash on a forest of massive redwood trees.  The trees were killed but the bases of the trees were protected and eventually fossilized.  The intricate structure of the wood is clearly visible and though less spectacular (but of more interest to the scientists) thousands of insects were preserved in fine detail.</p>
	<p>Since we had time available and Frontier Airlines started flying to Orlando at discount prices, we decided to take a trip to Florida as soon as my exams were over until the end of the year.</p>
	<p>The first thing to know about Florida is that, among the Europeans, the Spanish got there first, claiming it in 1513.  Of course, Mr. Columbus arrived in the New World in 1492 and the Spanish quickly claimed most of Central and South America.</p>
	<p>Our first stop was St. Augustine, which the Spanish established in 1565, making it the oldest permanent settlement in the US.  I understand that school children were once taught that the first settlers were the Pilgrims who landed in what is now Plymouth, Massachusetts but this reflected the Anglo-Saxon view of history, as they didn't arrive until 1620, 55 years later.</p>
	<p>Treasure ships on the way to Spain sailed up the Florida coast in the Gulf Stream and so could be vulnerable to pirates operating from coastal bases.  It was therefore essential for the Spanish to retain control of Florida. French Protestants settled near present-day Jacksonville in 1564 but when they came south in 1565, the Spanish seized the opportunity, killing nearly all the attackers and then capturing their town.</p>
	<p>However, the British were a bigger threat.  After several British raids on St. Augustine, the Spanish built the massive <i>Castillo de San Marcos</i> using "coquina", the soft, local stone made of seashells.</p>
	<p>It is very impressive and we were lucky to see a demonstration of a cannon being fired, though in the interests of local boat owners, it was just gunpowder and no cannon ball.</p>
	<p>Some of you may be aware that I lived in Washington D.C. in 1969/70.  My parents brought me here on a trip and it made such an impression on me that I still remembered it 30 years later.</p>
	<p>The fort survived British sieges in 1702 and again in 1740 but when the British captured Havana in what is now Cuba, the Spanish gave up all of Florida in 1763 to get it back.  At that time, Florida was everything south of the Savannah River, which is now the border between Georgia and South Carolina.  However, since the Spanish supported the Americans in the struggle for independence from Britain, the Americans gave Florida to Spain in 1783 as a reward, only to buy it back again in 1821.</p>
	<p>We saw a few other things in the area including a lighthouse, the "oldest house in the oldest city" (which is newer than one in Santa Fe, New Mexico) and another smaller fort further south.</p>
	<p>We drove north to Charleston, famous for its magnificent houses though it is worth noting that the region&rsquo;s wealth was generated by slave labor on the plantations.  We went to see <i>Magnolia Plantation</i>, which once grew rice and I expected to see a huge house in the style of <i>Tara</i> in <i>Gone with the Wind</i>.  It wasn't there.  We were to learn that firstly, plantation owners built their main houses in the town to escape the malaria on the plantations and secondly, as with Tara, Union troops burnt nearly everything as they came through at the end of the Civil War.  The house we saw was built later but they did have an interesting "swamp garden".</p>
	<p>The houses in Charleston are outstanding though.  We did a walking tour of the old town and toured one house that George Washington briefly rented.</p>
	<p>We had a bizarre lunch at <i>Burger King</i> that day.  The local senior citizens use it as a their bingo hall!  Also notable was the bathroom door&mdash;when the door opens as someone enters, diners in the main room get an unobstructed view of the men&rsquo;s urinal!  It seems impossible that the architects drew it that way, that the building codes allowed it and that it was never fixed after construction.</p>
	<p>However, the most memorable meal of the trip was at the <i>Feng Lin Chinese Restaurant</i> that night.  I had beef with broccoli for just $3.50 but it was the girl behind the counter that was special.  A family business with mum and dad cooking but their 12-year-old daughter took the orders, presumably because she spoke the best English.  She and her younger sister had their homework on one of the tables and would go back to it when there were no customers.</p>
	<p class="endText">I intended visiting Fort Sumter at the mouth of Charleston Harbor where the first shots of the Civil War were fired.  However, I misunderstood the boat schedule and we couldn't get a ferry before we had to leave town to visit Lan&rsquo;s sister and her family in Charlotte, North Carolina.  We were there only from about 3pm one day until breakfast the next but it was well worth the trip to see them.</p>
</div>
<div class="photo-gallery">
	<?
	setThumbnail(["PetrifiedStump1.jpg", "FloridaRoute1.jpg", "CastilloDeSanMarcos1.jpg", "FortMatanzasUs1.jpg", "Lighthouse1.jpg", "LighthouseSteps1.jpg", "SpanishMoss1.jpg", "SwampGarden1.jpg"]);
	?>
</div>

<div class="story">
	<p>Go back to <a href="index.php?fuseAction=letter13a">Activities</a> (page 1)</p>
	<p>Continue to <a href="index.php?fuseAction=letter13c">Travels, part 2</a> (page 3) <a href="index.php?fuseAction=letter13c"><img src="<?= $continueIconSrc ?>" height="13" border="0" style="vertical-align:bottom"></a></p>
	<p>Jump to:</p>
	<ul class="endText">
		<li><a href="index.php?fuseAction=letter13d">Travels, part 3</a> (page 4)</li>
		<li><a href="index.php?fuseAction=letter13e">America</a> (page 5)</li>
	</ul>
</div>
