<div class="story">
	<p class="endText">I was laid off in 2003 and during the 7 months I was out of work, I started to
   read. As a child I was encouraged (actually <i>forced</i> is how I remember it) but I never learned
   to love it and I struggled with the books I had to read for school. From 1986 to 2003 I probably
   averaged only one book per year, by far the most notable being Paul Kennedy's
   <i><a href="http://en.wikipedia.org/wiki/The_Rise_and_Fall_of_the_Great_Powers">The Rise and Fall of
   the Great Powers</a>: Economic Change and Military Conflict 1500-2000</i>. Then and now, I much
   prefer non-fiction.</p>
</div>

<h3>2011 &ndash; 2014</h3>
<div class="story">
<ol>
	<li><em><a href="http://www.amazon.com/40-Chances-Finding-Hungry-World/dp/1451687869/" target="_blank" class="external">40 Chances: Finding Hope in a Hungry World</a></em> by Howard G Buffett. I once wanted to work in international development so it was distressing to read of the many, many failures that make up much of the book. Howard (son of Warren&mdash;yes, that Warren Buffet) is a farmer and is doing great work trying to improve crop yields for small farmers in the third world and achieving some good results but not without many setbacks. One incident worries me still: he is driving somewhere and comes across a fellow who wants a ride into town so he can purchase a tire repair kit so he can get going again. They ride into town, the man finds a store that can sell him the kit and then asks Howard to take him back to where his broken down vehicle is so he can get his wallet. Howard asked him why he didn't bring it but it seemed the man was unable to think that far ahead. Perhaps malnutritian as a child.</li>
	<li><em><a href="http://www.amazon.com/64-Tomato-Fortune-Endured-Existential/dp/1565125576/" target="_blank" class="external">The $64 Tomato: How One Man Nearly Lost His Sanity, Spent a Fortune, and Endured an Existential Crisis in the Quest for the Perfect Garden</a></em> by William Alexander. This was amusing because Lan likes growing things to eat but the book clearly demonstrates the cost to benefit ratio is highly unfavorable if saving money is the goal.</li>
	<li><em><a href="http://www.amazon.com/Three-Ways-Capsize-Boat-Optimist/dp/0307592375/" target="_blank" class="external">Three Ways to Capsize a Boat: An Optimist Afloat</a></em> by Chris Stewart. Chris somehow gets a job looking after an old yacht in Greece for a wealthy but remote owner despite having no sailing experience and somehow pulls it off though not without trouble. Having conquered that he gets a place on a boat doing a trans-Atlantic crossing from Norway to Newfoundland.</li>
	<li><em><a href="http://www.amazon.com/Atlantic-Battles-Discoveries-Titanic-Million/dp/0061702625/" target="_blank" class="external">Atlantic: Great Sea Battles, Heroic Discoveries, Titanic Storms, and a Vast Ocean of a Million Stories</a></em> by Simon Winchester</li>
	<li><em><a href="http://www.amazon.com/Where-Fate-Beckons-Jean-FranCois-University/dp/160223003X/" target="_blank" class="external">Where Fate Beckons: The Life of Jean-FranCois de la Perouse</a></em> by John Dunmore. This book took forever to get the voyage that made him famous ... and killed him. On a roundabout way to Australia, they surveyed the long, thin <a href="http://en.wikipedia.org/wiki/Sakhalin" class="external" target="_blank">Sakhalin</a> to Japan's north sailing through the Nevelskoy Strait to prove it was an island and continued to Russia's <a href="http://en.wikipedia.org/wiki/Kamchatka_Peninsula" class="external" target="_blank">Kamchatka Peninsula</a>. There they dropped off Barthélemy de Lesseps who made his way overland back to Paris. I was so amazed that I created a <a href="http://en.wikipedia.org/wiki/Barth%C3%A9lemy_de_Lesseps" class="external" target="_blank">Wikipedia article</a> about him which made it to the &quot;Did you know...&quot; section of their home page for featured new articles (for just six hours).</li>
	<li><em><a href="http://www.amazon.com/Gold-Rush-Forever-Changed-Australia/dp/1864711302/" target="_blank" class="external">The Gold Rush: The Fever That Forever Changed Australia</a></em> by David Hill</li>
	<li><em><a href="http://www.amazon.com/Chocolate-Wars-150-Year-Rivalry-Greatest/dp/1610390512/" target="_blank" class="external">Chocolate Wars: The 150-Year Rivalry Between the World's Greatest Chocolate Makers</a></em> by Deborah Cadbury</li>
	<li><em><a href="http://www.amazon.com/Long-Way-Bernard-Moitessier/dp/0924486848/" target="_blank" class="external">The Long Way</a></em> by Bernard Moitessier. If you only read one book about sailing, it should be this one.</li>
	<li><em><a href="http://blogs.abc.net.au/queensland/2013/06/willis-island-solitude-solecisms.html?site=brisbane&program=612_weekends_with_warren" target="_blank" class="external">Solitude & Solecisms</a></em> by Frank Exon. I should mention that the author is a distant relation of mine. His son Neville had the diary published with the illustrations and though I started reading out of a sense of duty, I continued because it was delightful. A tough life though, especially the battle with cockroaches.</li>
	<li><em><a href="http://www.amazon.com/Unlikely-Voyage-Jack-Crow-Odyssey/dp/1574091522/" target="_blank" class="external">The Unlikely Voyage of Jack De Crow: A Mirror Odyssey from North Wales to the Black Sea</a></em> by A. J. Mackinnon.</li>
	<li><em><a href="http://www.amazon.com/1788-Watkin-Tench/dp/1921520043/" target="_blank" class="external">1788</a></em> by Watkin Tench.</li>
	<li><em><a href="http://www.amazon.com/Girl-Interrupted-Susanna-Kaysen/dp/0679746048/" target="_blank" class="external">Girl, Interrupted</a></em> by Susanna Kaysen.</li>
	<li><em><a href="http://www.amazon.com/Water-Between-Journey-Sea/dp/0385498845/" target="_blank" class="external">The Water in Between: A Journey at Sea</a></em> by Kevin Patterson.</li>
	<li><em><a href="http://www.amazon.com/Man-Who-Cycled-World/dp/0307716651/" target="_blank" class="external">The Man Who Cycled the World</a></em> by Mark Beaumont.</li>
	<li><em><a href="http://www.amazon.com/Am-Nujood-Age-10-Divorced/dp/0307589676/" target="_blank" class="external">I Am Nujood, Age 10 and Divorced</a></em> by Nujood Ali.</li>
	<li><em><a href="http://www.amazon.com/Ice-Bird-Classic-Single-Handed-Antarctica/dp/1574091514/" target="_blank" class="external">Ice Bird</a></em> by David Lewis.</li>
	<li><em><a href="http://www.amazon.com/Spanish-Treasure-Fleets-Timothy-Walton/dp/1561642614/" target="_blank" class="external">The Spanish Treasure Fleets</a></em> by Timothy R Walton</li>
	<li>Also some book about an early Australian settler. Can't recall the details now.</li>
</ol>
<div>

<h3>2010</h3>
<div class="story">
	<ol>
		<li><i>Longitude: the true story of a lone genius who solved the greatest scientific problem of his time</i> by Dava Sobell. (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=0802713122" target="_blank" class="external">ISBN 0-8027-13122</a>. I read this book thinking it might explain why <a href="http://en.wikipedia.org/wiki/John_Harrison" target="_blank" class="external">John Harrison's</a> accurate chronometer to allow ships to find their position at sea was a large watch rather than a full size clock. His first three machines (commonly referred to as H1, H2 and H3) were large clocks but he had a watch made for him incorporating some of his ideas and was impressed how accurate it was. To my mind, bigger should be better since machining inaccuracies are less important the larger the equipment. Unfortunately, this is a book for the general reader and didn't dwell on specifics. In fact it is short book but still felt padded to fill a paperback sized book of just 184 pages.</li>
		<li><i>The Race: The first non-stop, round-the-world, no-holds-barred sailing competition</i> by Tim Zimmerman (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=0618117482" target="_blank" class="external">ISBN 0-618-11748-2</a>); I finished the ~300 pages in under a week, which for me is speed reading. The title is somewhat misleading because the <a href="http://en.wikipedia.org/wiki/Sunday_Times_Golden_Globe_Race" target="_blank" class="external">Golden Globe race</a> of 1969-70 fits the description (see <i>A Voyage for Madmen</i> below) but that was sailed by amateurs in cruising boats and the winner took 313 days to get back to England whereas by 2000 the racing was done by professionals at speeds up to 40 knots in catamarans over 100 ft/30m long and the race was won in 62 days (the record is currently just 48!). The introductory chapters on the history of ocean racing, particularly the 19th century clipper ships, were amazing too. Unfortunately the most innovative boat entered in the competion, <a href="http://www.petegoss.com/journey-to-date-team-philips.php" class="external" target="_blank"><i>Team Philips</i></a> didn't make it to the start line. The boat minimized the sail handling by using &ldquo;windsurfer sails&rdquo;, kept the crew safe in a central module and used &ldquo;wave-piercing&rdquo; hulls to cushion the ride and reduce the loads on the boat but there were faults in the structure and the boat broke up in the North Atlantic during trials.</li>
		<li><i>The Fourth Part of the World: The race to the ends of the earth and the epic story of the map that gave America its name</i> by Tony Lebster (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=9781416535317" target="_blank" class="external">ISBN 978-1-4165-3531-7</a>). I read a <a href="http://www.washingtonpost.com/wp-dyn/content/article/2009/10/30/AR2009103002866.html" target="_blank" class="external">review</a> of the book in the Washington Post and it looked interesting. It was! The author set out to write a book about the map but ended up writing about how the European conception of the world, so long crippled by misguided theological notions, was enlarged in the two or three centuries leading up to Columbus and Vespucci's voyages to the New World. I had heard of <a href="http://en.wikipedia.org/wiki/Ptolemy" target="_blank" class="external">Ptolemy</a> from ancient Greece but had no idea that he'd invented the system of lattitude/longitude and had attempted to draw a world map. Naturally it was extremely difficult to get relative positions of places since he was reduced to guessing based on descriptions of how many days an army had taken to march from city A to city B. Then his work was lost for over a thousand years. Most amazing for me were the journeys of two Christin monks, <a href="http://en.wikipedia.org/wiki/Giovanni_da_Pian_del_Carpine" target="_blank" class="external">John of Plano Carpini</a> and separately, <a href="http://en.wikipedia.org/wiki/William_of_Rubruck" target="_blank" class="external">William of Rubruck</a>, to what is now Mongolia in the mid-1200s, a generation or so before Marco Polo.</li>
		<li><i><a href="http://en.wikipedia.org/wiki/Blue_Highways" target="_blank" class="external">Blue Highways</a></i> by William Least Heat-Moon (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=0449211096" target="_blank" class="external">ISBN 0-449-21109-6</a>). I enjoyed <i>River Horse</i> (see below) so much, I decided to read the book that made him [somewhat] famous. After his marriage fails and he loses his job, he fits a bunk bed and minimal equipment in a standard van that might be used by a plumber and sets off around America. He visits small towns with names that appeal to him, strikes up conversations in bars and picks up hitch-hikers but most importantly, learns the history and character of the places he encounters. He said he never came across a hoodlum (I think that was the word he used) but he was taken for one several times. Wonderful stuff. Read it.</li>
		<!--li><i></i> by  (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=" target="_blank" class="external">ISBN </a>). </li>
		<li><i></i> by  (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=" target="_blank" class="external">ISBN </a>). </li-->
	</ol>
</div>

		
<h3>2009</h3>
<div class="story">
	<ol>
		<li><i>The God Machine: From Boomerangs to Black Hawks: The Story of the Helicopter</i> by James Chiles (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=9780553804478" target="_blank" class="external">ISBN 978-0553804478</a>). Lots of interesting details on the history of this ungainly piece of machinery though the last third of the book petered out into commercial aspects. One interesting anecdote concerned a young Lyndon Johnson using a helicopter to make far more campaign stops in spread-out Texas than was possible by road or even by plane when the time to get into town by car was included; he won the election.</li>
		<li><i>Cathedral, Forge and Waterwheel: Technology and Invention in the Middle Ages</i> by Frances and Joseph Gies, (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=9780060165901" target="_blank" class="external">ISBN 978-0060165901</a>). If you like history and you like technology, a book about the history of technology is a sure winner. It was slow to read as I had to take notes and read more on Wikipedia on particular topics. It turns out that the &ldquo;Dark Ages&rdquo; were not actually such a wasteland of development in Europe after all. Windmills and waterwheels came into common use and there were big advances in ship design and construction. Decimal numbers and double-entry bookkeeping were introduced. Even the humble stirrup, imported from China, was a game-changer (look carefully at the <a href="http://en.wikipedia.org/wiki/Bayeux_Tapestry" class="external" target="_blank">Bayeax Tapestry</a> and only one side has them). By the end of the Middle Ages (500-1500AD) printing was appearing and change accelerating.</li>
		<li><i>River Horse: The Logbook of a Boat Across America</i> by <a href="http://en.wikipedia.org/wiki/William_Least_Heat-Moon" target="_blank" class="external">William Least Heat-Moon</a> (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=ISBN 0395636264" target="_blank" class="external">ISBN ISBN 0-395-63626-4</a>). I picked up this book at the library only half-heartedly because it involved a power-boat, not a yacht but it was absolutely fascinating. He knows so much interesting history about the places he travels through and there are adventures along the way on a journey that nearly falls apart many times. Wonderful. My only complaint is that his vocabulary is so wide I often had to look words up; he mentions a &ldquo;pother&rdquo; of cormorants for instance. Next up, <i>Blue Highways</i>, the book that got him into the Best Seller lists which I started but had to return.</li>
		<li><i>Sea of Dangers: Captain Cook and His Rivals in the South Pacific</i> by Geoffrey Blainey</a> (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn9781566638258" target="_blank" class="external">ISBN 978-1566638258</a>). I'd been wanting to read something about Cook's remarkable voyage to Australia's east coast but this book also covers the simultaneous journey in the opposite direction by a French ship who were hoping to find a continent in the south Pacific inhabited by Jewish traders. Apparently that didn't seem so ridiculous at the time. Amazingly, Cook and de Surville passed each other in the night at the top of New Zealand, both assuming the nearest Europeans were thousands of kilometers away in Java or the Philippines.</li>
		<li><i>Australian squatters</i> by Hubert De Castella (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=9780522843330" target="_blank" class="external">ISBN 978-0522843330</a>). A first-hand account of life in Australia in the 1850s. Despite his high-status European origin, he seems very open-minded and in particular speaks well of the aborigines which was perhaps unusual at the time.</li>
		<li><i>500 days: Around the world in a 12 foot yacht</i> by Serge Testa (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=9780731648498" target="_blank" class="external">ISBN 978-0731648498</a>). Over 20 years later, Serge still holds the record for the circumnavigating in the smallest boat. I started the <a href="http://en.wikipedia.org/wiki/Serge_Testa" target="_blank" class="external">Wikipedia article</a> but need to fill in a lot more detail as he deserves more recognition. I'd like to do a similar voyage&mdash;only in a smaller boat.</li>
		<li><i>How the States Got Their Shapes</i> by Mark Stein  (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=978-0061431395" target="_blank" class="external">ISBN 978-0061431395</a>). Every state boundary captures a piece of history, whether it is:
			<ul>
				<li>national rivalries (the northern border of CA, NV and UT along 42&deg;N)</li>
				<li>interstate rivalries (CT claimed land all the way to the Pacific but NY, formerly New Holland, got in the way)</li>
				<li>inaccurate surveys (the south-western corner of VA is 5 miles too far north)</li>
				<li>budget contraints (lack of money for a proper survey of the rivers means that part of the border between SD and MN is a straight line)</li>
				<li>successful lobbying, or depending on your point of view, bribery (the top of ID is so narrow because a representative from MN went to Washington with $2000 in contributions to politicians)</li>
				<li>geographic realities (the triangular snip of the south-west corner of MA was given to NY because the only roads into Boston Corner were through CT and NY making MA law unenforceable, and perhaps most interestingly</li>
				<li> a deliberate attempt to make the western states the same size.</li>
			</ul>
		</li> 
		<li><i>Bligh and the Bounty; his narrative of the voyage to Otaheite with an account of the mutiny and of his boat journey to Timor</i> by <a href="http://en.wikipedia.org/wiki/William_Blighy" target="_blank" class="external">William Bligh</a>. It appears that the popular reputation of this incident forged by the <a href="http://en.wikipedia.org/wiki/Mutiny_on_the_Bounty_%281962_film%29" target="_blank" class="external">film</a> staring Marlon Brando is a gross distortion of Bligh's character. While this is his own account of what happened, he certainly comes across as a thoughtful, skillful and even kind commander and navigator.</li>
		<li><i>The essentials of living aboard a boat: the definitive guide for liveaboards</i> by Mark Nicholas  (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=9780939837663" target="_blank" class="external">ISBN 978-0939837663</a>). Since I don't want to get stuck in the US and I was getting scared at the amount of money that Lan was prepared to spend on a house, I seriously contemplated living on a boat instead, preferrably one that could be sailed back to Australia when we were ready. Unfortunately, further research, much of it from this book, showed it to be impractical. First, a good boat for living in makes a lousy boat for cruising and vice versa with something else I read suggesting if you want to do both you need two boats - probably a houseboat to live on which might even be unpowered and a sail boat to go anywhere.  The best sail boats for space are catamarans but if big enough to live on (~40ft/12m) they are too wide for a standard marina berth though they can fit on the end of the row if available. Second, although there are several marinas in Washington DC, there is only one where you can legally live aboard and there is a waiting list that is years long. Third, it became clear that Lan really wouldn't be happy in the very limited space aboard a boat. Still, it was nice to dream for a while and look at ads for boats&mdash;check out <a href="http://www.yachtcouncil.com" class="external" target="_blank">www.yachtcouncil.com</a>. </li>
		<li><i>Summits: Six Meetings That Shaped the Twentieth Century</i> by David Reynolds (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=9780465069040" target="_blank" class="external">ISBN 978-0465069040</a>). I confess I'm only halfway through this. The intial chapters on the Munich conferences and then Yalta were fascinating but I put the book down and didn't get back to it until 2010. The section on Gorbachev and Reagan was interesting partly because I'm old enough to vaguely remember it and partly because it largely reinforced my belief that the credit for ending the Cold War lies far more with the Russian President than the American.</li>
	</ol>
</div>

<h3>2008</h3>
<div class="story">
   <ol>
		<li><i>The Lighthouse Stevensons</i> by Bella Bathurst with the subtitle, &quot;The Extraordinary Story of the Building of the Scottish Lighthouses by the Ancestors of Robert Louis Stevenson&quot;. It would have been more extraordinary if the story was told in half as many words. Bits of it (the descriptions of lighthouse construction) were very interesting but were interspersed with long passages of drivel. My mother and sister both gave me interesting books for Christmas but I've got something else I want to tackle first.</li>
		<li><i>High Lattitudes</i> by Farley Mowat  (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=1586420615" target="_blank" class="external">ISBN 1-58642-061-5</a>). I didn't know it when I picked up the book at the library but it turns out that <a href="http://en.wikipedia.org/wiki/Farley_Mowat" target="_blank" class="external">Mowat</a> is one of Canada's most popular authors and has written extensively about the Arctic and its native peoples and wildlife. In this book, published in 2002, he recounts a journey he took in 1966 noting the generally detrimental impact of European encroachment and intriguingly, on what appears to be Viking settlements in Ungava Bay off Hudson Strait.</li>
		<li><i>The Wollemi Pine: The Incredible Discovery of a Living Fossil from the Age of the Dinosaurs</i> by James Woodford (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=1876485744" target="_blank" class="external">ISBN 1876485744</a>). The discovery of the <a href="http://en.wikipedia.org/wiki/Wollemia" target="_blank" class="external">Wollemi Pine</a>, tree thought long extinct, would have made a great magazine article but making a book out of it was a bit of a stretch for me. </li>
		<li><i>Where Fate Beckons: The Life of Jean-FranCois de la Perouse</i> by John Dunmore (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=160223003X" target="_blank" class="external">ISBN 160223003X</a>). The voyage of Jean-François de la P&eacent;rouse through the Pacific in the 1780s is historically important even though it ended in disaster but unfortunately this book is more about la P&eacent;rouse the man rather than the voyage that doesn't get underway till about page 180 out of 262. Still, the last bit was fascinating and in particular, I learned of one crew member's overland journey across the full length of Russia and was so impressed I created a Wikipedia article about <a href="http://en.wikipedia.org/wiki/Barth%C3%A9lemy_de_Lesseps" target="_blank" class="external">Barthélemy de Lesseps</a>.</li>
		<li><i>Command of the Ocean: A Naval History of Britain, 1649-1815</i> by N.A.M Rodger (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=0393328473" target="_blank" class="external">ISBN 0393328473</a>). I think I started this in 2006 but only made it halfway through, not because I lost interest but because it is so dense with interesting material. I learned so much European history. Who knew for example that when Scotland was still somewhat independent, it had its own overseas colonies? The <a href="http://en.wikipedia.org/wiki/Darien_scheme" target=_blank" class="external">one in Panama</a> was a disaster and a key factor in the 1707 <a href="http://en.wikipedia.org/wiki/Acts_of_Union_1707" target="_blank" class="external">Acts of Union</a> that created Great Britain. A scant two pages devoted to George Anson's voyage prompted me to read <i>Prize of All the Oceans</i> listed below to get the full account. There is a marvellous <a href="http://www.economist.com/displaystory.cfm?story_id=3398708" target="_blank" class="external">review</a> in <i>The Economist</i> if you have a subscription.</li>
	</ol>
</div>

<h3>2007</h3>
<div class="story">
   <ol>
		<li><i>The Prize of All the Oceans</i> by Glyn Williams  (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=0670891975" target="_blank" class="external">ISBN 0670891975</a>). The incredible but true story of a British naval expedition sent to harrass the Spanish in the Pacific. Under the command of George Anson, six ships and 1900 men set out from England in 1740. Two ships turned back after being unable to round Cape Horn and of the others, only the flagship, the <i>Centurion</i> made it back to England in 1744. Three-quarters of the men were lost, mainly to disease compounded by starvation. Despite all this, they managed to capture a Spanish treasure ship sailing from Mexico to the Philippines and so they received a rapturous welcome on their return. I was so in awe that I wrote an <a href="http://en.wikipedia.org/wiki/George_Anson's_voyage_around_the_world" target="_blank" class="external">article in Wikipedia</a> about it but also astonished that I had never heard about it.</li>
		<li><i><a href="http://en.wikipedia.org/wiki/The_Prince" target="_blank" class="external">The Prince</a></i> by Niccolò Machiavelli (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=0143036335" target="_blank" class="external">ISBN 0143036335</a>*). An early and influential book on politics. I read it wanting to find the context of &quot;Never interrupt your enemy while he is busy destroying himself&quot; but I didn't see it. I learned later that the quote is actually attributed to <a href="http://en.wikipedia.org/wiki/Napoleon" target="_blank" class="external">Napoleon</a>.</li>
		<li><i><a href="http://en.wikipedia.org/wiki/Brave_new_world" target="_blank" class="external">Brave New World</a></i> by Aldus Huxley (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=0060809833" target="_blank" class="external">ISBN 0060809833</a>*). When I was in high school, I thought the <i>only</i> worthwhile book of those I was forced to read was George Orwell's <a href="http://en.wikipedia.org/wiki/Nineteen_Eighty-Four" target="_blank" class="external">1984</a>. I was aware that there were some similarities but I didn't know of the great differences. The brave new world is to be full of everything wonderful but should anything unpleasant come about, there is a drug to make you happy; by contrast, the world of 1984 is run by state terror. The wikipedia article mentions social critic Neil Postman writing, &quot;In short, Orwell feared that what we hate will ruin us. Huxley feared that what we love will ruin us.&quot;. Apparently Postman has written a book <i>Amusing Ourselves to Death: Public Discourse in the Age of Show Business</i> which &quot;alludes to how television is goading modern Western culture to be like what we see in Brave New World, where people are not so much denied human rights such as free speech and expression as they are conditioned to not care&quot;. Frighteningly true.</li>
		<li><i><a href="http://en.wikipedia.org/wiki/One_Day_in_the_Life_of_Ivan_Denisovich" target="_blank" class="external">One Day in the Life of Ivan Denisovich</a></i> by Aleksandr Solzhenitsyn (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=0451523105" target="_blank" class="external">ISBN 0451523105</a>). I read this short classic of Soviet literature while I was at school and didn't appreciate it at the time but thought it would be interesting to reread as an adult now that I know much more about the Soviet Union. It's portrayal of life in the <a href="http://en.wikipedia.org/wiki/Gulag" target="_blank" class="external">gulag</a> is on one hand distressing for the bleak conditions and yet it was published in the USSR, perhaps because of the ultimately positive sense of achievement Ivan feels at the end of the day's hard labor.</li>
		<li><i>The Stormy Voyage of Father's Day</i> by Hugo Vihlen (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=0943400910" target="_blank" class="external">ISBN 0943400910</a>). West-to-east across the Atlantic in a 5ft 4in (1.6m) boat in 1993. In fact, having sailed east-to-west in a 5ft 11in (1.8m) boat in 1968, he had the record for the smallest boat to cross until briefly losing to Tom McNally in 1993. It should be noted though that Tom's 5ft 4½in (1.6m) boat did not carry an engine.</li>
		<li><i>A Voyage for Madmen</i> by Peter Nichols (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=0060957034" target="_blank" class="external">ISBN 0060957034</a>). Following Chichester's return, the remaining grand goal of sailing was a solo, non-stop circumnavigation. A British newspaper set up a race and nine men took the challenge. A gripping story of triumph and tragedy result.</li>
		<li><i>Maiden Voyage</i> by <a href="http://en.wikipedia.org/wiki/Tania_Aebi" target="_blank" class="external">Tania Aebi</a> (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=0345410122" target="_blank" class="external">ISBN 0345410122</a>). Since she had no interest in getting a tertiary education, her father hoped to give her life some direction by offering her a boat and her job was to sail around the world. After what I consider a reckless lack of preparation on her father's part, she made it home aged 21. Since she carried a passenger between nearby Pacific islands, her voyage does not technically count as solo.</li>
		<li><i>By Way of Cape Horn</i> by <a href="http://en.wikipedia.org/wiki/Alan_Villiers" target="_blank" class="external">Alan Villiers</a>, published 1952. Alan wanted to record life on the last of the working sailing ships so in 1929 he and fellow-reporter Ronald Walker took a job on the <i>Grace Harwar</i> carrying wheat from Australia to England. It took 138 days and even then they only made it to Queenstown, now Cobh, Ireland. During that time, Ronald was killed by an accident in the rigging, another sailor was washed overboard but amazingly was recovered and the second mate had a nervous breakdown. The voyage was so long that they ran out of food so had to stop a passing steamer and the cargo began to rot. Ronald had taken a movie camera to document the voyage so Alan took over that task in very difficult conditions. For two months the men kept the same wet clothing on; outside temperatures fell as low as -15&deg;C/5&deg;F and yet the men's sleeping quarters were unheated. Being on a sailing ship is dangerous work but I was surprised that in 1929 some relatively simple safety measures were not taken and that the foul-weather clothing was so ineffective. You can see a little of Alan's later film on <a href="http://www.youtube.com/watch?v=ufNzunuXMCc" target="_blank" class="external">YouTube</a>.</li>
		<li><i><a href="http://www.businessweek.com/1997/39/b3546030.htm" target="_blank" class="external">Cod: A Biography of the Fish That Changed the World</a></i> by Mark Kurlanski (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=0140275010" target="_blank" class="external">ISBN 0140275010</a>). Fascinating. I had no idea the fish was so important to the development of this country and this book is relevant to current issues too. If you want to read how governments, scientists and business interests dealt with a looming trans-national environmental crisis of which they had decades of warning, I highly recommend this book. (They failed completely . <a href="http://www.greenfacts.org/en/ecosystems/figtableboxes/figure3-4-collapse-cod.htm" target="_blank" class="external">Read more</a>.)</li>
		<li><i>Salt: A World History</i> also by Mark Kurlanski (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=0802713734" target="_blank" class="external">ISBN 0802713734</a>). After reveling in <i>Cod</i>, I was excited about being immersed in <i>Salt</i> but I have to agree with this <a href="http://www.eyrie.org/~eagle/reviews/books/0-8027-1373-4.html" target="_blank" class="external">book review</a>, that the book would have been better titled <i>Salt: A Collection of Historical Anecdotes</i>. In <i>Cod</i>, there was a build-up to a catastrophic ending but this book meanders and reaches no real punch-line.</li>
	</ol>
</div>

<h3>2003 &ndash; 2006</h3>
<div class="story">
   <ol>
      <li><i><a href="http://natstone.net/index.shtml" target="_blank" class="external">On the Water: Discovering America in a Row Boat</a></i> by Nat Stone (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=0767908422" target="_blank" class="external">ISBN 0767908422</a>). This wonderful book tells how Nat, in small, manageable jumps rowed from New York north up the Hudson River, west along the Erie Canal and Great Lakes, south down the Mississippi River system, east and then north along the Intracoastal Waterway passing New York and ending in Maine. However, it is as much about the people he met along the way as the voyage.</li>
      <li><i>A speck on the sea : epic voyages in the most improbable vessels</i> by William H Longyard (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=0071413065" target="_blank" class="external">ISBN 0071413065</a>). A comprehensive history of small boat voyages.</li>
      <li><i><a href="http://en.wikipedia.org/wiki/Guns_Germs_and_Steel" target="_blank" class="external">Guns, Germs, and Steel: The Fates of Human Societies</a></i> by Jared Diamond (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=0393038912" target="_blank" class="external">ISBN 0393038912</a>). Hand on heart, I say that <i>everyone</i> should read this book as it will change how you view the world. This book is astonishing in its breadth. Covering 13,000 years of human history Jared Diamond tries to answer the question of why some societies have come to dominate others. The answer are not what you might think and indeed he makes the case that Europeans and to an extent Asians, are probably NOT as smart as the peoples they conquered. Here is a 6 page <a href="http://www.edge.org/3rd_culture/diamond/diamond_p1.html" target="_blank" class="external">summary</a>.</li>
      <li><i>Alone at Sea</i> by <a href="http://en.wikipedia.org/wiki/Hannes_Lindemann" target="_blank" class="external">Dr. Hannes Lindemann</a> (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=3925660275" target="_blank" class="external">ISBN 3925660275</a>). Just in case crossing the Atlantic in a dugout canoe wasn't sufficiently unusual, he did it again in a folding canoe!</li>
      <li><i>Arctic Crossing: A Journey Through the Northwest Passage and Inuit Culture</i> by Jonathan Waterman (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=0375404090" target="_blank" class="external">ISBN 0375404090</a>). Across the top of Canada by sea kayak. The Inuit commiunities were at times very depressing.</li>
      <li><i>Paddle to the Amazon: The Ultimate 12,000-Mile Canoe Adventure</i> by Don Starkell (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=0771082568" target="_blank" class="external">ISBN 0771082568</a>). A man and his two sons get in their canoe in Winnepeg, Canada and keep paddling until they get to Belem, Brazil at the mouth of the Amazon! I think he took some stupid risks. As well as the ocean, there were bandits to contend with along the coast of Central America and Columbia.</li>
      <li><i>Stalin's Spy: Richard Sorge and the Tokyo Espionage Ring</i> by  (<a href="http://en.wikipedia.org/w/index.php?title=Special:Booksources&isbn=1860640443" target="_blank" class="external">ISBN 1860640443</a>). The incredible story of Soviet spy <a href="http://en.wikipedia.org/wiki/Richard_Sorge" target="_blank" class="external">Richard Sorge</a> who while based in Tokyo under cover of a reporter, managed to gain the confidence of top officials at the German embassy and passed back military intelligence that greatly influenced the outcome of WW2.</li>
      <li><i>Tinkerbelle</i> by <a href="http://en.wikipedia.org/wiki/Robert_Manry" target="_blank" class="external"></a>Robert Manry. West-to-east across the Atlantic in a 13½ft (4.1m) boat in 1965.</li>
      <li><i>Alone Against the Atlantic</i> by <a href="http://en.wikipedia.org/wiki/Gerry_Spiess" target="_blank" class="external"></a> (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=0898935067" target="_blank" class="external">ISBN 0898935067</a>). West-to-east across the Atlantic in a 10ft (3m) boat in 1979. Two years later he crossed the Pacific in the same boat arriving on about the day I started my final high school exams. If it was reported on the news, I was too busy to notice.</li>
      <li><i>Sailing Alone Around the World</i> by <a href="http://en.wikipedia.org/wiki/Joshua_Slocum" target="_blank" class="external">Joshua Slocum</a> (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=1590302664" target="_blank" class="external">ISBN 1590302664</a>*). A sailing ship captain made redundant by the rise of steam powered ships makes the first solo circumnavigation in 1893/94. He did it the hard way travelling east mainly against the prevailing winds.</li>
      <li><i>40,000 Miles in a Canoe</i> by John Voss (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=0071414266" target="_blank" class="external">ISBN 0071414266</a>). Having seen the fame that Slocum had gained after his voyage, Voss set out to outdo him by using a smaller boat. While the term &quot;canoe&quot; is misleading as it was a 38ft (11.6m) long, the <i>Tilikum</i> was indeed a native-American dugout canoe but fitted with a small cabin, 3 masts and a keel. While there is some dispute over his ethics (an accompanying journalist may have been pushed overboard and by not rounding Cape Horn, he did not complete a circumnavigation as claimed), there is no doubt that Voss was a master of small boat handling. After arriving in Melbourne, his boat was dropped while it was out of the water for display and maintenance. He completed his voyage in 1904.</li>
      <li><i>Ice Bird</i> by David Lewis (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=0713664118" target="_blank" class="external">ISBN 0713664118</a>). Sailing a yacht to Antactica. He made it but it nearly killed him after being knocked down and dismasted.</li>
      <li><i><a href="http://theopencritic.com/?p=11" target="_blank" class="external">Gipsy Moth Circles the World</a></i> by <a href="http://en.wikipedia.org/wiki/Francis_Chichester" target="_blank" class="external">Francis Chichester</a> (<a href="http://en.wikipedia.org/w/index.php?title=Special%3ABooksources&isbn=0071414282" target="_blank" class="external">ISBN 0071414282</a>). An old man sets off alone in a yacht to retrace the path of the clipper ships and to do it in similar time. Broke records and inspired many. A quarter of a million turned out to welcome him home. He turned 65 while at sea and thinking about his age says, &quot;Our only purpose in life, if we able to say such a thing, is to put up the best performance we can – in anything, and only in doing so lies satisfaction in living.&quot; He certainly did.</li>
   </ol>
   <p>Two books whose names I can't remember: one on some Canadians taking a canoe trip and another on what happened to a crew after their yacht sank (not for the easily intimidated). Also one I wish I hadn't wasted my time on, &quot;A job worth doing, the sub-Artic voyage of the Aqua Star&quot; which covered more of the crew's bickering than actual sailing.</p>
   <p class="endText">* Other versions available. Most likely this book is past copyright protection so anyone can publish it but they may also be available online at <a href="http://www.gutenberg.org/wiki/Main_Page" target="_blank" class="external">Project Gutenberg</a>.</p>
 </div>






